ktlint-ruleset-standard/src/main/kotlin/com/gihub/shyiko/ktlint/ruleset/standard/NoWildcardImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoWildcardImportsRuleTest.kt
pom.xml

According to codestyle, it allows to have wildcard imports for Kotlin Android Extensions:
```xml
<JetCodeStyleSettings>
<option name="PACKAGES_TO_USE_STAR_IMPORTS">
<value>
<package name="kotlinx.android.synthetic" withSubpackages="true" static="false" />
</value>
</option>
<option name="NAME_COUNT_TO_USE_STAR_IMPORT" value="2147483647" />
<option name="NAME_COUNT_TO_USE_STAR_IMPORT_FOR_MEMBERS" value="2147483647" />
</JetCodeStyleSettings>
```
This PR excludes imports of kotlin android extensions from being detected as 'Wildcard import'.
Plus, includes a fix for minor typo issue in pom.xml

Exclude Kotlin Android extensions from Wildcard import rule

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt

ModifierOrderRule was added to release notes but not enabled, I think this was a mistake? This PR resolved the issue.
If this wasn't a mistake please close this PR.

Enable ModifierOrderRule

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundKeywordRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundKeywordRuleTest.kt

And no space if property accessor has no block body. See https://kotlinlang.org/docs/reference/properties.html
```kotlin
var setterVisibility: String = "abc"
private set
```

Space after property accessor

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRuleTest.kt

**Why**
The error message was hardcoded to 4 so read incorrectly when a custom indent size was used.

Fix misleading indent lint error message

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCurlyRuleTest.kt

Kotlin supports named blocks in cases where you want to return early or return from an inner block without returning a function, the syntax is as so:
```kotlin
fun printNFromList(list: List<*>, count: Int) {
list.mapIndexed a@{ item, index ->
if (index > count) return@a
println(item)
}
}
printNFromList(listOf(1, 2, 3), 2)
```
obviously that's contrived because `return@map` would suffice as well, but our code sometimes requires operations like `.map { .map { } }` which means `return@method` doesn't work, named blocks are required.

allow for named blocks

---

.travis.yml
ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt
pom.xml

Using an older version of kotlin should not be an issue when using ktlint as a standalone tool. However when using the core engine embedded in a gradle plugin an upgrade is necessary to avoid a breaking change in `KotlinCoreEnvironment`. Reference:
https://github.com/jeremymailen/kotlinter-gradle/issues/13
Thanks!

Upgrade to kotlin 1.1.3-2

---

README.md
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoBlankLineBeforeRbraceRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoBlankLineBeforeRbraceRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoConsecutiveBlankLinesRuleTest.kt

Closes #65 as IDEA's formatter is now able to detect blank lines before `}`. 
Please note that additionally to the case described in the issue 
```
fun main() {
fun a() {
}
}
``` 
The rule also prohibits the following construction: 
```
fun a() {
}
```
and formats it to 
```
fun a() {
}
```

Detect needless blank lines

---

ktlint-intellij-idea-integration/src/main/resources/config/codestyles/ktlint.xml

As requested in #65 this PR update `ktlint-intellij-idea-integration` according to new added rule in #92.

Update intellij idea integration with no blank line before rbrace rule

---

.gitignore
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRuleTest.kt

closes #76 
In my project, indent size is 4, but continuation size is 6. It means, that condition `line.length % indent != 0` always fails.
Rule now calculates indent size relatively to parent element and compares it to expected indent size. Rule knows several cases when continuation indent should be used. For sure, it's not a complete list of cases. These are emerged during testing on my code base and I expect to see more of them when other people start to use it.
Continuation indent size can be specified via `continuation_indent_size` from `.editorconfig`. By default, regular indent size is used.
Due to the fact, that previous implementation was too permissive, I expected that current rule can find some new violation. But for well formatted code, it should return same result. Of course, …

Respect continuation indent size, make IndentationRule more intelligent

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRuleTest.kt

Line break is allowed only after assignment (eg. equals sign)
Auto formatting is supported via simplistic approach by putting
same line break with same indent from left side to right side of assignment
Closes shyiko/ktlint#105

new Rule: No line break before assignment

---

ktlint-core/src/test/kotlin/com/github/shyiko/ktlint/core/KtLintTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoLineBreakAfterElseRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoMultipleSpacesRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoTrailingSpacesRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoLineBreakAfterElseRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/package-test.kt
ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt
ktlint/src/main/kotlin/com/github/shyiko/ktlint/internal/MavenDependencyResolver.kt

Reports line breaks after "else" clause. Supports auto format by replacing linebreak with space.
Doesn't take into account maximum line length.
closes https://github.com/shyiko/ktlint/issues/122

new rule: NoLineBreakAfterElse

---

ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt

Because `EnvironmentConfigFiles.EMPTY` is removed in 1.2.20
This is copy-paste of the similar change from Kotlin itself
https://github.com/JetBrains/kotlin/commit/afc9d3ef8b5bd4f2db44823f4eb62c3ce7d5dfd1#diff-0326941c85afd979faa6998b7b95bff8R55
fixes #131
Commit message from kotlin repository says
>Drop EnvironmentConfigFiles.EMPTY and replace its only usage in
preprocessor with JVM_CONFIG_FILES: it's easier and won't affect
anything
Unfortunately, I have no idea if the same reasoning applies to KtLint or not. My feeling says yes, because `KtLint` and `Preprocessor` classes look very very similar.

Use JVM_CONFIG_FILES instead of EMPTY

---

README.md
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.kt
ktlint/src/main/kotlin/com/github/shyiko/ktlint/internal/IntellijIDEAIntegration.kt

This reverts commit ed261175241807e0f7bb0428db8f2d0c253f6e5e.
As per discussion from the GitHub issue [1], the default continuation
indent for Android should be 8 rather than 4. This matches the Android
Kotlin style guide.
[1] https://github.com/shyiko/ktlint/issues/120

Revert "Changed continuation_indent_size to 4"

---

README.md
ktlint/pom.xml
pom.xml

Use HTTPS for links in README
Use HTTPS for JCenter
Upgrade Maven plugins and dependencies

Use HTTPS and upgrade Maven plugins/dependencies

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/IndentationRuleTest.kt

Corrected whitespace should be equal to expected indent + previous indent
Fixes #116 
@shyiko Would it be possible to release 0.15.1 fix with these changes?
PS. 
While testing I've found some cases when `IndentionRule` doesn't report violation. Also on my code base I had to apply `detektFormat` twice. 
These two are not trivial to fix. I'll describe them later in a separate issue.

IndentationRule: fix auto correction

---

build.gradle
ktlint-reporter-plain/build.gradle
ktlint-test/build.gradle
ktlint/build.gradle

- Add new dependencies needed to build/test ktlint
(missed these due to my branch being out of date)
- Set jar target level be java 8.
- Added shadowjar plugin that allows to build uber jar
for running ktlint.
Use: ./gradlew shadowJar
Then use ktlint/build/libs/ktlint-all.jar

Complete gradle build of ktlint.

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

I noticed a bug with the unused import rule when I initially integrated in KtLint into one of my projects. It erroneously detected custom componentN operators as unused (which the auto formatter ended up removing and breaking my build :()
The Kotlin std library by default only provides `component1()` up to `component5()`, meaning that you can only destructure up to 5 values by default. See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/index.html and search for "component5" for reference
So if someone wants to destructure six values, i.e.:
`(one, two, three, four, five, six) = someList`
... the IDE will throw an error since `component6()` doesn't exist. To get around this you can write your own component6() method pretty easily:
`inline operator fun <T> …

Fix erroneous unused import flagging on custom destructure operators

---

snap/snapcraft.yaml

This package will let you publish the latest ktlint in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

Add the packaging metadata to build the ktlint snap

---

snap/snapcraft.yaml

Remove the hard-coded arch path to find the java bin.

snap: move java to an arch independent dir

---

ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/KtLint.kt

Adds custom `CompilerConfiguration` so that KtLint can be run using Java 9. 
This was suggested in a Kotlin compiler bug report [KT-21995](https://youtrack.jetbrains.com/issue/KT-21995). This should fix #152.

Fix Java 9 compatibility

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ClassAndFunctionHeaderFormatRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ClassAndFunctionHeaderFormatRuleTest.kt

Fixes StringIndexOutOfBoundsException that can happen for class without body when max line length is specified.
Fixes line size calculation for secondary constructor and function.
How fix works: Just take entire line size, without any attempt to understand where is primary constructor, secondary constructor or class body. If line doesn't fit, than we should break parameter list definition into several lines.

Improve line length calculation in ClassAndFunctionHeaderFormatRule

---

ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt

A bug in JDK-9 ([JDK-8190987](https://bugs.openjdk.java.net/browse/JDK-8190987)) caused `Package.getImplementationVersion()` to return null. This commits adds code to read the Manifest file from the JAR to get the Implementation Version when it's not possible to retrieve the version through the normal way.
This PR contributes to #152

Fix version returning null when running on Java 9

---

README.md

This took me longer than I'm willing to admit to realize the mistake when trying to run this example locally. :/

Fix syntax of main method in AST section of README

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ModifierOrderRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ModifierOrderRuleTest.kt

Annotations should precede all modifiers according to: https://kotlinlang.org/docs/reference/coding-conventions.html#modifiers
(It might make sense in the future to forbid having multiple annotations on the same line as the declaration per the link above. Not sure if that should be a new rule or not though; at the very least this should be an improvement over the existing check)
Had quite a bit of difficulty implementing the auto-format since annotation entries are a different type than all the other modifiers. I'm open to feedback on how to clean it up. :)

Update ModifierOrderRule to include annotations as part of its checks

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

Resolves #96
This commit applies `parameter-list-wrapping` and its associated linting/formatting when `max_line_length` is exceeded by a function or class declaration due to its parameter list being too long. It will also apply for nested function declarations.

Apply `parameter-list-wrapping` when `max_line_length` is exceeded

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

Noticed a dev in my team writing code like this that passed Ktlint, so adding a quick fix here for it.
Sidenote: It feels like identifying dangling left parens should be part of a broader rule. Right now, the following code is valid according to Ktlint (athough I think it'd be pretty rare to see a dev actually write something like this, Ktlint should still probably catch it):
```
if
(someCondition) {
doSomething()
}
```
However, given that this error is likely a lot more common in class/function headers I just added the fix there for now (also because we're handling right paren formatting in it). Let me know what you think though!

Fix ParameterListWrappingRule to correctly identify misplaced left parens

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRuleTest.kt

Is there any magic that one needs to do in order to execute the tests?
`gradle test` didn't quite work.

CommentSpacingRule: Exclude //noinspection.

---

ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt
ktlint/src/main/kotlin/com/github/shyiko/ktlint/internal/EditorConfigFinder.kt

* Adds the ability to user to specify the `.editorconfig` path.
I setup ktlint in my [project](https://github.com/charbgr/cliffhanger) and then I installed the [pre-commit](https://github.com/shyiko/ktlint/blob/master/ktlint/src/main/resources/ktlint-git-pre-commit-hook.sh) hook. "Real" code is under `cliffhanger/` folder and the `.editorconfig.` is placed under that folder. 
The issue is that pre-commit hook is being installed in the parent git directory (where not "Real" code exists) and the `.editorconfig` is placed in a different folder, resulting to wrong lint warnings.
With this fix I can modify my pre-commit hook and set editoconfig path by
```
$ git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --relative . --editorconfig-path="cliffhanger/"
```
Let me …

Add ability to specify editorconfig path

---

README.md
ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt
ktlint/src/main/resources/ktlint-git-pre-push-hook-android.sh
ktlint/src/main/resources/ktlint-git-pre-push-hook.sh

Added a pre push hook, in case someone wants to run ktlint only before pushing.
It compares files that changed from remote to local branch.
You can install it with:
```bash
$ ktlint --install-git-pre-push-hook
```

Adds pre-push hook

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/FilenameRule.kt

Changed the link to a rule showcase to point to a spicific commit, rather than to master, because the version of a file at the head of branch can change as new commits are made and the file contents might not be the same when someone looks at it later.

Use permanent link to file as FilenameRule showcase reference

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/PackageNameRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/PackageNameRuleTest.kt

Hi, Thank you for review #228 #243 
And I develop #238 
And then, I noticed bellow coding style rules. This PR includes addtional rule.
- package name should not contians UpperCase characters and UnderScore.
https://android.github.io/kotlin-guides/style.html#package-names
Thanks!

Issues#238 Rule About package name

---

ktlint-reporter-json/src/main/kotlin/com/github/shyiko/ktlint/reporter/json/JsonReporter.kt
ktlint-reporter-json/src/test/kotlin/com/github/shyiko/ktlint/reporter/json/JsonReporterTest.kt

Fixes #256 
I've ensured that the generated json regarding the LinterError is correctly escaped according to the json specification. I've also included a unit test to verify this new behaviour.

Fix escape characters in the generated json.

---

README.md

"We respect you .editorconfig ... " to "We respect your .editorconfig ..."

minor typo correction in readme.md

---

README.md

"The very first ktlint gradle plugin" doesn't reflect what plugin actually supports and do.

Update ktlint-gradle plugin info in README.

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRuleTest.kt

In our code base, we have some block comments in the form of:
```
////////////////
// functionName
////////////////
```
Previously, ktlint would insert spaces, turning that block into:
```
// //////////////
// functionName
// //////////////
```
This PR fixes that.

Fixing issue with CommentSpacingRule which would insert a space into a comment that was all forward slashes

---

ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt

Before this change, all the repositories that have been used to resolve rulesets have downloaded those rulesets over HTTP instead of HTTPS. This leaves the user wide open to system compromise via a Man In The Middle (MITM) attack. This isn't just theoretical; POC code exists already.
See:
- https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/
- https://github.com/mveytsman/dilettante
I will file for a CVE number after this is merged and a release has been published.
This vulnerability has a CVSS v3.0 Base Score of 8.1
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H

[SECURITY] Resolve dependenices over HTTPS instead of HTTP

---

build.gradle
pom.xml

**Why**
Fixes runtime error caused by `LONG_STRING_TEMPLATE_ENTRY` changing from a `KtNodeType` to the more generic `IElementType`.

Upgrade to Kotlin 1.3.20

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundColonRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt

There were missing formatting and linting over `KtTypeConstraint` and `KtConstructor`, I've added them + patched some tests (Closes #315). As per [documentation](https://kotlinlang.org/docs/reference/coding-conventions.html#colon).

Fix constructor's colon-spacing lint and format

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt

I've just noticed that the latest release was missing the latest added rules in the standard ruleset. I've added them, but you'd probably need to release again, right?

Add missing rules to ruleset

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ImportOrderingRuleTest.kt
ktlint-ruleset-standard/src/test/resources/spec/import-ordering/lint.kt.spec

The `testFormatBlankLines` and `testFormatBlankLinesForMajorGroups` tests would have failed without the new `hasTooMuchWhitespace` check inside the rule.

ImportOrderingRule didn't remove blank lines when order was already correct

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/NoSemicolonsRuleTest.kt

```
/**
* x;
*/
```
was working fine because the text was processed as "x;" but
```
/**
*/
```
failed because the left bracket, the identifier, and the right racket were processed as separate nodes, and then the node with the single ";" text was checked and failed.
Simply opting out of the check for all KDOC_TEXT seems fine.
Fixes #362.

Fix failing on KDoc semicolon after other nodes.

---

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

Fix an issue where the `Exceeded max line length` rule is always trying to put parameters on separate lines, even when there are no parameters, causing the rule `Missing newline before ")"` to break.
Fixes #327

Fix 'Missing newline before ")"' when no params

---

build.gradle
ktlint-core/src/main/kotlin/com/github/shyiko/ktlint/core/ast/ElementType.kt
ktlint-ruleset-template/build.gradle
pom.xml

Update compiler dependencies. Will fix jeremymailen/kotlinter-gradle#93
Had to remove unused and obsolete `SELF_TYPE` removed in https://github.com/JetBrains/kotlin/commit/a5f96d6470c6b2b5c5ed10f235d3e5e414cfa9b9#diff-ea2f6c02e3b56913b28804fec405288e
Thank you!

Upgrade to kotlin 1.3.30

---

jitpack.yml

**Why**
See https://jitpack.io/docs/BUILDING/
Since both gradle and maven build files are present, jitpack defaults to using the gradle build and the install target does not work there.
Errors from previous build: https://jitpack.io/com/github/shyiko/ktlint/0.29.0/build.log
**What**
- add jitpack.yml to specify that the maven build should be used instead
**Testing**
- validate by jitpack'ing repo with this change
- tested here and it works: https://jitpack.io/#jeremymailen/ktlint/jitpack-compat-SNAPSHOT

Make build compatible with jitpack

---

CHANGELOG.md

Looks like the group id is just `com.pinterest` rather than `com.pinterest.ktlint`. 
After merging, this should be also fixed in releases tab.

Fix groupID in CHANGELOG

---

ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleExtension.kt

Doing `mvn clean verify` on Windows actually does not work - due to `\r\n` usage in spec files, it fails to parse them. So I just replace it with `\n`.

Make spec file parsing working on Windows

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow.kt.spec

Fixing a bug we noticed in our own code base where:
```
when {
1, // first element
2 // second element
-> true
}
```
would become:
```
when {
1, // first element
2 // second element
-> 
true
}
```

Fixing bug where ktlint would unexpectedly force a newline after an ->

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRuleTest.kt

Disable autocorrection for comma spacing rule if comma on newline preceded by // comment.
Fixes #367

fix SpacingAroundCommaRule when comma goes after comment

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundUnaryOperatorsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundUnaryOperatorsRuleTest.kt
ktlint-ruleset-standard/src/test/resources/spec/unary-op-spacing/format-expected.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/unary-op-spacing/format.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/unary-op-spacing/lint.kt.spec

Added a rule, that check spacing around unary operators according to kotlin style guide (addresses an issue #412).

Added unary-op-spacing rule

---

README.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt

Bandaid for https://github.com/pinterest/ktlint/issues/48

Disable no wildcard rule

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRuleTest.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-dot-qualified-expression-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-eq-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-property-accessor-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-raw-string-trim-indent-expected.kt.spec
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

* Fixes https://github.com/pinterest/ktlint/issues/368 and https://github.com/pinterest/ktlint/issues/380
* Kotlin styleguide: https://kotlinlang.org/docs/reference/coding-conventions.html#chained-call-wrapping
* Says 'The first call in the chain usually should have a line break before it, but it's OK to omit it if the code makes more sense that way.'

Remove code that was inserting newline after = in a chained call

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ImportOrderingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ImportOrderingRuleTest.kt

Fixes #408 
Refusing to auto-import seemed much easier than trying to figure out which imports the comments were attached to.

Don't autoformat imports if the import list contains top-level comments

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

This PR fixes the issue [#405](https://github.com/pinterest/ktlint/issues/405)
- While traversing nodes and building `ref`,  built a set of non redundant imports which omits the imports where parent reference is already present.
- Imports with aliases should contain both name and alias in the importSet
- Static function call and variable have been distinguised

Report unused import when parent reference is already present

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/test/resources/spec/max-line-length/lint.kt.spec

Normally we only allow comments to exceed the max line length if they're the only thing on the line, but we should add an exception for `// ktlint-disable` since that can be used to suppress a rule on a single line, and we don't have control over the line length.

Allow // ktlint-disable directives to exceed the max line length

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/EditorConfig.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRuleTest.kt

Enable final new line by default

---

.travis.yml

#445 
@shashachu 
This PR adds caching for maven(while we have it) and gradle(what we are moving to). I also formatted the travisci.yml to be more readable.
References:
- https://docs.travis-ci.com/user/languages/java/
- https://docs.travis-ci.com/user/caching/

Process of migrating to gradle - improve caching

---

build.gradle
ktlint-core/build.gradle
ktlint-reporter-checkstyle/build.gradle
ktlint-reporter-json/build.gradle
ktlint-reporter-plain/build.gradle
ktlint-ruleset-experimental/build.gradle
ktlint-ruleset-standard/build.gradle
ktlint-test/build.gradle
ktlint/build.gradle

#445
@shashachu
Clean up and organize Gradle dependencies across the project. This is similar to other open source Gradle projects such as https://github.com/JakeWharton/SdkSearch/blob/master/build.gradle#L18.

Process of migrating to gradle - organize gradle dependencies

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ReporterProvider.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/RuleSetProvider.kt
ktlint-ruleset-template/build.gradle
ktlint-ruleset-template/src/test/kotlin/yourpkgname/NoVarRuleTest.kt
ktlint/build.gradle

#445
@shashachu 
From `com.github.shyiko.ktlint.Main` to `com.pinterest.ktlint.Main`

Process of migrating to gradle - Fix main class name for this project

---

build.gradle
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
pom.xml

This dependency provides support for parsing command line arguments  and printing help message.
IMHO, most interesting changes since current version, that I would like to add in followup PRs:
- [Improved help message layout](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-improved-usage-help-message-layout)
- [Help command](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-help-command)
- [Standard help options](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-standard-help-options)
- [Programmatic api](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#-programmatic-api)
- [Command aliases](https://github.com/remkop/picocli/blob/master/RELEASE-NOTES.md#command-aliases)
- [Option completion …

Update picoli depenedency to 3.9.6 version.

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/MavenDependencyResolver.kt

- print warning message with link to the issue #451, when resolver is used
- hide related command-line options
- remove mentioning from project readme
To see warning message run:
```sh
$ ./ktlint/target/ktlint --debug --reporter=html,artifact=me.cassiano:ktlint-html-reporter:0.2.3,output=ktlint.html ktlint/src/**/*.kt
```
On using direct jar file, message should not be visible:
```sh
$ ./ktlint/target/ktlint --debug --reporter=html,artifact=~/.m2/repository/me/cassiano/ktlint-html-reporter/0.2.3/ktlint-html-reporter-0.2.3.jar,output=ktlint.html ktlint/src/**/*.kt
```

Deprecate MavenDependencyResolver.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/NoFirstLineBlankInMethodBlockRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/NoFirstLineBlankInMethodBlockRuleTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/EditorConfig.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/MavenDependencyResolver.kt

This experimental rule addresses issue Issue [#440](https://github.com/pinterest/ktlint/issues/440)
In addition to checking for first line blank in a method block, it will check for any first blank line in code blocks of the method.Please let me know if the subsequent code blocks in the method need to be ignored from this check.
Due to this new rule, there were violations reported in the code. Have fixed them also.
This is same as PR [#461](https://github.com/pinterest/ktlint/pull/461).

Adding experimental rule for detecting first line blank in method block

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

This flags were deprecated in version 0.9.0 and safe to remove:
https://github.com/pinterest/ktlint/blob/master/CHANGELOG.md#090---2017-07-23

Remove deprecated command line flags.

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ByteArrayExt.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/CommandLineExt.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitPreCommitHookSubCommand.kt

Move old one `--install-git-pre-commit-hook` option to be a ktlint
subcommand - new syntax: `ktlint installGitPreCommitHook`. Old option
`--install-git-pre-commit-hook` is still working, but deprecated.
This sub command acts as a separate action, that is not running checks, and should not confuse users oppose to option.

Add "installGitPreCommitHook" sub command.

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitHookInstaller.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitPrePushHookSubCommand.kt

Move old one (`--install-git-pre-push-hook`) option to be a ktlint
subcommand - new syntax: `ktlint installGitPrePushHook`. Old one
`--install-git-pre-commit-hook` is still working, but deprecated.
Unified code between commit and push hooks subcommands to actually
install git hook in `GitHookInstaller`.

Add "installGitPrePushHook" sub command.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRuleTest.kt

Fixes the issue [#490](https://github.com/pinterest/ktlint/issues/490)
Annotation rule looks for element type belonging to `MODIFIER_LIST`. The keyword `data` also falls under this element type. Excluding it explicitly from the list.

Excluding the keyword data from annotation rule

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/PrintASTSubCommand.kt

Move old one (--print-ast) option to be a ktlint sub command - new syntax:
`ktlint printAST`. Old one `--print-ast` is still working, but
deprecated.

Add "printAST" sub command.

---

ktlint/build.gradle

@shashachu 
Closes https://github.com/pinterest/ktlint/pull/489
If you run `gradlew build`, it will generate the following:
```
$ ls ktlint/build/libs/ktlint-0.34.0-SNAPSHOT
ktlint-0.34.0-SNAPSHOT-all.jar      ktlint-0.34.0-SNAPSHOT-sources.jar  
ktlint-0.34.0-SNAPSHOT-javadoc.jar  ktlint-0.34.0-SNAPSHOT.jar
```
You can do `java -jar ktlint/build/libs/ktlint-0.34.0-SNAPSHOT-all.jar`  to run ktlint

Try publishish ktlint-all.jar

---

.editorconfig
ktlint-core/build.gradle
ktlint-core/pom.xml
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/EditorConfig.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigInternal.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/DisabledRulesTest.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/ErrorSuppressionTest.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/KtLintTest.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigInternalTest.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleExtension.kt
ktlint/build.gradle
ktlint/pom.xml
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/IntellijIDEAIntegration.kt

Fixes #208
* Takes in a comma-separated list of rule ids, with namespaces (e.g. `experimental:indent`)
* Re-enabled `NoWildcardImports`, `PackageNameRule`
* Un-commented `AnnotationRule`, `MultiLineIfElseRule`, and `NoItParamInMultilineLambdaRule`, and moved disabling into default `.editorconfig`
* Moved `.editorconfig` parsing into `ktlint-core` so that plugins that don't invoke ktlint on the command line can take advantage of rule disabling
* Also cleaned up params passed to lint and format

Add support for disabled_rules property in .editorconfig for globally disabling rules

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRuleTest.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/479

Fixing bug with extra indentation after lambda arrow

---

ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProviderTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProviderTest.kt
ktlint-test/build.gradle
ktlint-test/pom.xml
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleSetProviderTest.kt

This is a follow up for #476. I would suggest merging this after the `.ktlintignore` landed on `master`. Or I could also implement ignores list for this kind of tests for now, but I would rather wait for global ignores. It just grabs the source files from the specified location and then checks that all of them are being returned from the specified ruleset.

Add tests for missing rules in a ruleset

---

.editorconfig
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRuleTest.kt

Return if there's no annotations found instead of throwing an exception
Fixes https://github.com/pinterest/ktlint/issues/490 and https://github.com/pinterest/ktlint/issues/502

Fix AnnotationRule exception

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

Fixes https://github.com/pinterest/ktlint/issues/506

Allow unreferenced provideDelegate if there is a by keyword in the file

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationRuleTest.kt

Closes #498 
Edit: Well after reading the property name again, do we want single parameter annotations also be on separate lines?
Imo the checks need a `it.valueParameters.size > 1`.

Consider comments when searching for multiline annotations

---

ktlint/build.gradle

This task behaves similar to https://github.com/brianm/really-executable-jars-maven-plugin maven plugin - it creates unix runnable file, that executes `ktlint-all.jar` without need of additional shell script.
Generated file could be checked by executing `ktlint/build/run/ktlint --help` command.
Additional flag `-Xmx512m` was added as per current maven configuration: https://github.com/pinterest/ktlint/blob/e5fd74cba3cb8c12bbd81b8103c5db82f75c6c68/ktlint/pom.xml#L347

Add task "shadowJarExecutable" to generate self-running ktlint jar.

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/PrintASTSubCommand.kt

* Fixes https://github.com/pinterest/ktlint/issues/528
* Also properly pass through `--debug` flag from `printAST` command
* Small cleanup of unused variable

Properly handle --stdin flag for printAST command

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-supertype-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-supertype.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/518

Fixing bug with improper indentation for enums with multi-line initializers

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Fixes https://github.com/pinterest/ktlint/issues/538

Only set disabled_rules in userData if not empty

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ApplyToIDEAGloballySubCommand.kt

This subcommand replaces `--apply-to-idea` command line option. Option itself is still supported, but deprecated.

Introduce "applyToIDEA" subcommand.

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Unblocks using them on on java 9+.
Base on ideas discussed in #495 and #573 PRs.
To test - execute following steps:
```bash
$ ./gradlew :ktlint-ruleset-template:jar
...
$ ./gradlew sJE
...
$ docker run --rm -ti -w "/command" -v `pwd`:/command openjdk:11-jdk-slim ./ktlint/build/run/ktlint --debug --experimental --ruleset=ktlint-ruleset-template/build/libs/ktlint-ruleset-template.jar
[DEBUG] Discovered ruleset with "standard" id.
[DEBUG] Discovered ruleset with "custom" id.
[DEBUG] Discovered ruleset with "experimental" id.
[DEBUG] Discovered reporter with "checkstyle" id.
[DEBUG] Discovered reporter with "json" id.
[DEBUG] Discovered reporter with "plain" id.
[DEBUG] Initializing "plain" reporter with {verbose=false, color=false}
[DEBUG] Checking …
```

Proper loading of 3rd party rulesets and reporters.

---

ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporter.kt
ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterProvider.kt
ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/internal/Color.kt
ktlint-reporter-plain/src/test/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterProviderTest.kt
ktlint-reporter-plain/src/test/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

This resolves the issue discussed here, that the default DARK_GRAY background color was hard to read against dark terminals: #582 
I made sure this was a non breaking change by allowing the current usage of KtLint to behave the way it does now. For example:
- ./ktlint 
- Will output without color as it does now
- ./ktlint --color
- Will color the output in DARK_GRAY as it does now
- ./ktlint --color --color-name="RED"
- Will color the output in RED, or whatever was supplied.
I've added unit tests to `PlainReporterTest` to validate the colored output. I also added `PlainReporterProviderTest` which ensures the input for a color maps to the expected output. 
I also ran this manually. Here is KtLint with no command args:
Here it is with `--color`:
Here it is with `--color --colorName="RED"`:

Added support for customizing the output color for #582.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRuleTest.kt

Fix https://github.com/pinterest/ktlint/issues/564
Remove spacing after "}" when it's map key.
```kotlin
// Missing spacing after "}"
fun main() { map[1 + list.count { it != true }] = 1 }
```
```kotlin
// No error
fun main() { map[1 + list.count { it != true }] = 1 }
// Unexpected space after "}"
fun main() { map[1 + list.count { it != true } ] = 1 }
```

Remove spacing between "}" and "]"

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-arrow.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/586
Do not insert newline after arrow, when following expression is one-line.
```kotlin
fun test(status: A): B {
return when (status) {
A.A,
// Missing newline after "->"
A.B -> B.A
}
}
// Formatted
fun test(status: A): B? {
return when (status) {
A.A,
A.B ->
B.A
}
}
```
```kotlin
fun test(status: A): B {
return when (status) {
A.A,
//  No error
A.B -> B.A
}
}
```

No newline after arrow when the expression is one-line

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundOperatorsRule.kt
ktlint-ruleset-standard/src/test/resources/spec/op-spacing/lint.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/576
Inserts space around the multiplication operator, but not for spread operator.
```kotlin
// No error
fun main() {
test(*array)
test(1, *array, 2)
test(1*value)
test.run { 1*value }
}
```
```kotlin
fun main() {
test(*array)
test(1, *array, 2)
// Missing spacing around "*"
test(1*value)
// Missing spacing around "*"
test.run { 1*value }
}
// Formatted result
fun main() {
test(*array)
test(1, *array, 2)
test(1 * value)
test.run { 1 * value }
}
```

Insert space around the multiplication operator

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/lint-property-accessor.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/550
Fix indent before get/set in case of variable assignment is in separated line, to follow IDEA's formatting.
```kotlin
object TestObject {
var value: String =
"tooooooooooooooooo looooooooooooooooooooooooooong line"
// Unexpected indentation (8) (should be 12)
private set
}
```
```kotlin
object TestObject {
var value: String =
"tooooooooooooooooo looooooooooooooooooooooooooong line"
// No error
private set
}
```

Fix indent with get/set and line-separated variable assignment

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoEmptyClassBodyRule.kt
ktlint-ruleset-standard/src/test/resources/spec/no-empty-class-body/lint.kt.spec

Fixes https://github.com/pinterest/ktlint/issues/411
keep empty brace of companion object from removing, because the removing causes compile error.
```kotlin
class test {
// Unnecessary block ("{}")
companion object {}
enum class ExampleEnum {
EXAMPLE
}
}
// Formatted
class test {
companion object
enum class ExampleEnum {
// Compile error
EXAMPLE
}
}
```
```kotlin
class test {
// No error
companion object {}
enum class ExampleEnum {
EXAMPLE
}
}
```

Keep empty brace of companion object

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

Fixes https://github.com/pinterest/ktlint/issues/559
Insert spacing after annotation.
```kotlin
// No error
data class A(
@Annotation(0)val property: Type 
)
```
```kotlin
data class A(
// Missing spacing after @Annotation(0)
@Annotation(0)val property: Type 
)
// Formatted
data class A(
@Annotation(0) val property: Type 
)
```

Insert spacing after annotation

---

README.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Mention Ktlint uses .gitignore pattern style syntax.

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ApplyToIDEACommandHelper.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ApplyToIDEAProjectSubCommand.kt

Removed all related code from `Main.kt` file and share the commmand-line code between apply to IDEA globally and to project subcommands.

Add "applyToIDEAProject" subcommand.

---

ktlint-core/build.gradle
ktlint-ruleset-experimental/build.gradle
ktlint-ruleset-standard/build.gradle
ktlint-ruleset-template/build.gradle
ktlint-test/build.gradle

This should allow to produce similar to Maven build artefacts from Gradle build.

Align dependencies scopes in Gradle configuration with Maven.

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

The goal of this PR to make code more readable and specific `run()` method inside `KltintCommandLine`. The logic behind the code should not be changed.

Reorganize run() method in KtlintCommandLine class.

---

ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitHookInstaller.kt

Very minor convenience improvement.
Previously we assumed that we were always in the root of the repo for
installing Git hooks. Instead, call `rev-parse --show-toplevel` to
discover the root of the repo, which lets us call
`--install-pre-{commit,push}-hook` from anywhere inside a Git repository.

Try to discover `.git` instead of hardcoding.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

Resolve #625 
Fix error on formatting annotation for primary constructor.
Formatting following code causes the error.
```kotlin
class Foo @Inject internal constructor()
```
```stacktrace
com.pinterest.ktlint.core.RuleExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:384)
at com.pinterest.ktlint.core.KtLint$format$1.invoke(KtLint.kt:41)
at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:279)
at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke(KtLint.kt:41)
at com.pinterest.ktlint.core.KtLint.visit(KtLint.kt:536)
at com.pinterest.ktlint.core.KtLint.visit(KtLint.kt:537)
at com.pinterest.ktlint.core.KtLint.visit(KtLint.kt:537)
at …
```

Fix error on formatting annotation for primary constructor

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt
ktlint-ruleset-experimental/src/test/resources/spec/indent/format-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/format.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/indent/lint-string.kt.spec

Resolve #622
```kotlin
// 5:1: Unexpected indentation (16) (should be 12)
// 6:1: Unexpected indentation (12) (should be 8)
class Example {
fun example() {
Integer
.parseInt("32").let {
println("parsed $it")
}
}
}
// Formatted
class Example {
fun example() {
Integer
.parseInt("32").let {
println("parsed $it")
}
}
}
```
```kotlin
// No Error
class Example {
fun example() {
Integer
.parseInt("32").let {
println("parsed $it")
}
}
}
```

Fix indentation with lambda argument, Fix #622

---

ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigInternalTest.kt
ktlint-reporter-plain/src/test/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterTest.kt

Fix build/tests on Windows

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt

This fixes #272 by adding explicit removal of the UTF-8 BOM from the content of the files being parsed; it also introduces a minor refactoring that reduces code duplication.
Note that this also removes the BOM from the output when formatting files; it shouldn't be a big deal, as UTF-8 files can work without it and it is in fact suggested not to include it.

Added utf-8 BOM removal

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

Resolve #556 and #608. 
As I mentioned in the issue in the [official styleguide](https://kotlinlang.org/docs/reference/coding-conventions.html#annotation-formatting) there's nothing about single-line annotations on method/constructor parameters. Also extended it a little, to allow the same thing in arguments' annotations (e.g. when you have a `@Retention(SOURCE) @Target(EXPRESSION)` for the annotation class)

Allow single-line annotations in parameters/arguments

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRuleTest.kt

Allow new-line after lambda return type

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/NoEmptyFirstLineInMethodBlockRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/NoEmptyFirstLineInMethodBlockRuleTest.kt

Allow empty first line in function that returns anonymous object

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

Allow annotations within angle brackets to be placed on same line

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/EnumEntryNameCaseRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/EnumEntryNameCaseRuleTest.kt

Resolve #635 
Implement an experimental rule to lint enum entry name.
This rule enforces enum entry names to 
1. contains no lower case letter if it contains under score.
2. starts with upper case if it contains lower case letter.
So, "ENTRY_NAME" and "EntryName" are valid, "Entry_Name", "entry_name" and "entryName" are invalid.
Currently auto-format will convert entry name to all upper case, but this behavior is highly debatable.
```kotlin
enum class FirstEnum {
enum_entry
}
enum class SecondEnum {
entry
}
```
```kotlin
enum class FirstEnum {
ENUM_ENTRY
}
enum class SecondEnum {
ENTRY
}
```

Implement a rule to lint enum entry name

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/CommentSpacingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRuleTest.kt

Fix #653.
Technically, IDEA actually allows both
```
System.out.println( // 123
"test single comment"
)
```
And
```
System.out.println(// 123
"test single comment"
)
```
This PR is only targeting to fix the former case, whilst the latter will still be violated by the `comment-spacing` rule. I think it's a good tradeoff between readability and compatibility with idea. Let me know, if you think we should also change `comment-spacing` to allow both cases.

Allow whitespace after lpar followed by a comment

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRuleTest.kt

Fix #671
Error: `7:43: Missing spacing after "when"`
```kotlin
package pckg.name.testcommon
import org.mockito.Mockito
import org.mockito.stubbing.OngoingStubbing
/**
* Convenience wrapper around [Mockito.when] to avoid special `when` notation.
*/
fun <T> whenever(call: T): OngoingStubbing<T> = Mockito.`when`(call)
```
No error with same code

Allow keyword without back quote in KDoc

---

ktlint-ruleset-experimental/build.gradle

Move it from compile scope to test scope.
Partial fix for #678

Fix exerimental ruleset dependency on ktlint-test.

---

ktlint-ruleset-standard/build.gradle

Move it from compile scope to test scope.
See #678 & #679

Fix standard ruleset dependency on ktlint-test

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ParseException.kt

For build environments where normal exception printing is all we can see, this info is getting lost...

Add line and column to ParseException message

---

README.md

Fixed broken link in README.md about custom ruleset.
I think it's related with a29bee62477219e42b4adc7472ed67292995f104

Fix broken link in REAMDE.md

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingAroundDoubleColonRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingAroundDoubleColonRuleTest.kt
ktlint-ruleset-experimental/src/test/resources/spec/spacing-around-double-colon/format-expected.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/spacing-around-double-colon/format.kt.spec
ktlint-ruleset-experimental/src/test/resources/spec/spacing-around-double-colon/lint.kt.spec

I've noticed there wasn't a rule for linting a double-colon (`::`) operator, so decided it's worth the effort to introduce it to experimental ruleset :)
Links to [android](https://developer.android.com/kotlin/style-guide#horizontal) and [kotlin](https://kotlinlang.org/docs/reference/coding-conventions.html#horizontal-whitespace) styleguides, where you can find the guidelines for this operator.

Introduce SpacingAroundDoubleColonRule

---

build.gradle

Integrated https://github.com/BreadMoirai/github-release-gradle-plugin gradle plugin. This plugin creates new Github release and populates release notes from project `CHANGELOG.md`. Related task is triggered by "publishNewRelease" task.
To check how release notes will look change `dryRun` to `true` and run `./gradlew githubRelease`.

Add plugin to sync changelog to Github releases.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRuleTest.kt

Allow annotated function types in paren-spacing rule

---

README.md

Noticed this was deprecated https://github.com/mcassiano/ktlint-html-reporter as it was moved into ktlint 🥳

REAME update - html reporter promoted to first party!

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

AnnotationRule: don't report if a comment is placed after the last annotation

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCurlyRuleTest.kt

This is a potential fix for #728. When pulling a left curly brace up to previous line, move EOL comment after curly brace.

Move EOL comment after left curly brace so code remains compilable

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt

In order to avoid duplicating code, make these functions public for use
by tools that use KtLint programmatically and need to convert an offset
to line / column, like detekt.

KtLint: Make functions needed to calculate line / column public

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ast/package.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/DumpAST.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Add file annotations rule

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRuleTest.kt

This fixes the autocorrect functionality in MultiLineIfElseRule that was partially implemented but commented out. It should resolve #174.

Fix autocorrect for single line if/else expressions

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithAnnotationsRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithAnnotationsRuleTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRuleTest.kt

See https://youtrack.jetbrains.com/issue/KT-35106 and https://youtrack.jetbrains.com/issue/KT-35088
Fixes #721

Adding two new experimental rules that follow new formatting rules introduced in Kotlin 1.3.70.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRuleTest.kt

Fixing ClassCastException with NoLineBreakBeforeAssignmentRule when there is no space after assignment

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/IntellijIDEAIntegration.kt

Introduce additional parameter `isStdIn` to indicate properties are loaded for code that is coming from input.
Previous approach used `<stdin>` as a last path segment. Apparently `<` or `>` is illegal characters on windows filesystem.
Fixes #761

Fix loading .editorconfig properties on windows fs fails.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/resources/spec/indent/format-raw-string-trim-indent-expected.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/indent/format-raw-string-trim-indent.kt.spec

This PR is aiming to allow any indentation within raw strings for now, will come up with something better later (perhaps new indentation rules that could handle `trimIndent`, `trimMargin` and plain raw strings differently)
Fix #682

IndentationRule: Allow free-form text inside raw strings

---

ktlint/build.gradle

Close #695. Uses a [plugin](https://github.com/gradle/gradle-checksum) from Gradle itself for generating checksums.

Add checksum generation task for executable

---

ktlint-reporter-html/src/main/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporter.kt

Command `gradlew.bat test` fails on Windows with HtmlReporterTest.
Changed `\n` to `System.lineSeparator()` in HtmlReporter. Other newlines were generated by `println()`, and in the test expected data has separator explicitly changed to platform-specific.
Now `gradlew.bat test` succeeds on Windows.

Fixed HtmlReporterTest failing on windows

---

CHANGELOG.md
build.gradle
gradle/verification-metadata.xml

This update resolves few issues reported in #790:
- allow empty `.editorconfig` file in the path
- print path to failed `.editorconfig` on parsing

Update ec4j to 0.2.2 version.

---

CHANGELOG.md
ktlint/src/main/resources/config/codestyles/ktlint.xml
ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml

Set continuation indent to 4 in codestyle for IDE.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

This PR fixes #688 
In essence, we should not have empty lines between an annotation and the thing that it's "annotating". 
My fix adds an extra check in the annotation file that will ensure there is no duplicate spaces between Annotations and the elements that they are annotating. In addition, a suite of new tests have verified this assertion and the auto correct.

AnnotationRule: disallow empty line between annotation and annotated target

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRuleTest.kt

MultiLineIfElseRule: don't insert unnecessary empty lines

---

ktlint-reporter-html/src/main/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporter.kt
ktlint-reporter-html/src/test/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporterTest.kt

Hi guys, I've made a fix for https://github.com/pinterest/ktlint/issues/814. Please let me know what you think.
P.S. This is my first PR here, might have forgotten something 😄

Escape special html symbols in the html reporter (#814)

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRuleTest.kt

Fixes https://github.com/pinterest/ktlint/issues/803
The following exception was produced in case when a program starts with multiple spaces:
```java
Caused by: java.lang.IllegalStateException: node.treePrev must not be null
at com.pinterest.ktlint.ruleset.standard.NoMultipleSpacesRule.visit(NoMultipleSpacesRule.kt:17)
```

Fix internal error on "no-multi-spaces" rule

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

IndentationRule: Indent brace-less if-else bodies starting with parens correctly

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

IndentationRule: Indent if-condition with multiline call expression inside correctly

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

Fixes #836 
Some code that was meant to handle redundant static imports was removing an import for an extension function because the name of the variable we were calling the extension function on happened to match a sub-package name.

Fixing false-positive Unused Import with extension function

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/resources/spec/indent/format-raw-string-trim-indent-expected.kt.spec

Fixes #711 
@shashachu I saw you've introduced this change in https://github.com/pinterest/ktlint/pull/387/commits/b54ea782bc5ee776efc69830e7c903523fc89178 but I think we should just leave raw strings alone because IDEA also does nothing about them (at least I haven't found any pattern) neither there are any mentions about it in the style guides

IndentationRule: Do not enforce raw strings opening quote to be on a separate line

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

Correctly indent parameters when having multiline type parameter list in function signature

---

ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

Add the test case that was breaking defining the bug: formatting does not play well with other rules (in this case parameter wrapping) that change the number of lines in the file

Sample PR to test breaking rule

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt

Only when debug flag is enabled.
Should simplify debugging issues.

Print loaded .editorconfig content when debug flag is enabled.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRuleTest.kt

NoSemicolonsRule: don't report when semicolon is before annotation/comment/kdoc and lambda

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt
ktlint-ruleset-standard/src/test/resources/spec/string-template/lint.kt.spec

StringTemplateRule: don't report when template expression is keyword

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt

Fix alternative .editorconfig path is ignored on stdin input.

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/RuleSet.kt

In some cases some custom rule sets need to have different implementation of RuleSet. For example in the diktat (https://github.com/cqfn/diKTat) project it is used to pass ruleset specific configuration in the rules (config files). This should not affect anything and simply gives developers a chance to customise rule sets more.

Opening class RuleSet so it can be inherited.

---

CHANGELOG.md
buildSrc/src/main/kotlin/ktlint-publication.gradle.kts
ktlint/build.gradle

Automated publishing to Github release should now also upload generated ktlint cli signature.
Fixes #895

Publish ktlint CLI signature to Github release.

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

NoUnusedImportsRule: fix false positive with imported sub classes are used in DOT_QUALIFIED_EXPRESSION

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/resources/spec/indent/lint-when-expression.kt.spec

Fix false positive `Missing newline after "->"` when `when` entry has if/else block

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt

AnnotationRule: receiver target annotation with parameter should not be separated line

---

README.md

Continuation from https://github.com/pinterest/ktlint/issues/912. Added a section with ktlint online demo. This can attract more users to ktlint. As now they can see how powerful ktlint is without installing it to your PC.

Adding links to ktlint demo to the README.md

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GenerateEditorConfigSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/RuleSetsLoader.kt

Initial implementation of `.editorconfig` Kotlin section generation via CLI subcommand. For now it just outputs generated content to stdout.
Part of #701 issue.

Add 'generateEditorConfig' CLI subcommand.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt

ArgumentListWrappingRule: don't report it when line breaks is inside a lambda

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt

ArgumentListWrappingRule: fix wrong indentation in `if` condition

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGenerator.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGeneratorTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GenerateEditorConfigSubCommand.kt

Allow on '.editorconfig' file generation to use different default values for android code style.
Part of #701

Allow to have different default value for android code style.

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ast/package.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt

ArgumentListWrappingRule: Fix false positive for method after string template

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportSorter.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleAsciiTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleCustomTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleIdeaTest.kt

Add editorconfig value generation support to 'import-ordering' rule.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRuleTest.kt

Fixes #865
- Fix false positives when a comment is not between declarations (#865)
- Fix false negatives when declarations is in class

SpacingBetweenDeclarationsWithCommentsRule: fix false positives/negatives

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

IndentationRule: don't insert unnecessary spacings inside multiline if-else condition

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

ParameterListWrappingRule: correctly indent primary constructor parameters when class has multiline type parameter

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRuleTest.kt

NoSemicolonsRule: don't report when semicolon is between empty enum entry and member

---

README.md
build.gradle
ktlint-baseline.xml
ktlint-reporter-baseline/build.gradle
ktlint-reporter-baseline/gradle.properties
ktlint-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/reporter/baseline/BaselineReporter.kt
ktlint-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/reporter/baseline/BaselineReporterProvider.kt
ktlint-reporter-baseline/src/main/resources/META-INF/services/com.pinterest.ktlint.core.ReporterProvider
ktlint-reporter-baseline/src/test/kotlin/com/pinterest/ktlint/reporter/baseline/BaselineReporterTest.kt
ktlint/build.gradle
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/BaselineUtils.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/BaselineTests.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/internal/BaselineUtilsKtTest.kt
ktlint/src/test/resources/TestBaselineExtraErrorFile.kt
ktlint/src/test/resources/TestBaselineFile.kt
ktlint/src/test/resources/test-baseline.xml
settings.gradle

Adds in a new flag, `baseline`, that allows you to specify a baseline to check again when running your report.
The functionality is similar to [Android lint's baseline](https://developer.android.com/studio/write/lint#snapshot). It creates a snapshot file of the current errors in the project on the first run using the checkstyle reporter. On all following runs it checks against that baseline file and only reports errors that do not exist inside that file.

Add baseline functionality to ktlint

---

ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRuleTest.kt

We are getting reports of `no-consecutive-blank-lines` just because we have an empty line after package declaration. According to the code style guidelines, there should be 1 space after package name. 
I'm opening this PR just to have the conversation with ktlin team + verify this behavior with tests.

Empty space after package name

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

ParameterListWrappingRule: fix wrong indentation when function has multiline TYPE_ARGUMENT_LIST

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRuleTest.kt

NoLineBreakBeforeAssignmentRule: fix wrong formatting when a assignment has comments

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRuleTest.kt

NoSemicolonsRule: don't report semicolon for control flow with empty body

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

IndentationRule: Fix incorrect indentation for multi-line call expressions in conditions

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRuleTest.kt

A follow-up for #982 - figured out [here](https://kotlinlang.org/docs/reference/grammar.html) that there might be more cases, when trailing comma can have no spaces on the right (in particular before RBRACKET and GT), also added a changelog entry for #982.

SpacingAroundCommaRule: Add more cases 

---

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GenerateEditorConfigSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/RuleSetsLoader.kt

Adding special option `disable-standard-rules` that is extremely useful and needed when `ktlint` is used as a framework for static analysis. In some cases when `custom ruleset` is used - there is no need to use `standard ruleset` as it can lead to conflicts.
In this case we need a mechanism to disable standard rules. This change will not break any API and the default behavior will remain the same.

Adding new option disable-standard-rules

---

README.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportLayoutParser.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportLayoutParserTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleCustomTest.kt

Part of #753 - also updated documentation and tests that were no failing apparently, even when I changed the pattern 🤷 Now they are properly testing it :) 
Source of truth - https://github.com/JetBrains/intellij-kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/formatter/KotlinPackageEntryTableAccessor.kt

ImportOrderingRule: update how alias pattern is represented

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRuleTest.kt

 NoConsecutiveBlankLinesRule: report blank line between class name and primary constructor

---

README.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportLayoutParser.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportLayoutParserTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleCustomTest.kt

Am not sure why they use a double star to indicate "with subpackages" behavior, and also, even when I specified a full path without subpackages and exported the `.editorconfig` file in IDEA, it still had a single star in it:
```
ij_kotlin_imports_layout = *,java.**,javax.**,kotlin.**,java.nio.file.Paths.*,^
```
Maybe this means "all members of an import" - don't know.
As usual source of truth: https://github.com/JetBrains/intellij-kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/formatter/KotlinPackageEntryTableAccessor.kt

Align with kotlin plugin on how subpackages are represented

---

ktlint/build.gradle

According to https://github.com/johnrengelman/shadow/issues/586 the fat jar is now automatically published, so we do not need to specify it explicitly (this was causing the issue of multiple artifacts with the same classifier). Tested locally with publishToMavenLocal task.

Fix snapshot publishing

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGenerator.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportSorter.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/PatternEntry.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingEditorconfigTest.kt

@Tapchicoma not sure why you converted the properties to `List<PatternEntry>` but writing to editorconfig didn't work properly, because:
- PatternEntry's `toString` method was messed up
- By default `List<PatternEntry>.toString()` returns something like `[*,kotlin.**,java.**,^]` - mind the braces. This is an incorrect value if we wanna write to the standard `ij_kotlin_imports_layout`, to properly generate it we would need to use `joinToString` but we don't know the type in the `getEditorConfigValue`..
So the easiest path I found is to revert properties to be strings, but not sure if it's the best approach. Maybe we could introduce some interface like `EditorconfigWriteable` which has a `toString` method and put it as an upper bound for generic `EditorConfigProperty<T : …

Fix import-ordering editorconifg generation

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FilenameRuleTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/IntellijIDEAIntegration.kt

Previously, when ktlint failed to find '.editorconfig', file path was not passed to the rules. This lead for wrong "filename" rule behaviour.
Fixes #997

Always pass file path via user data properties.

---

README.md

To clarify how the IntelliJ IDEA code style setting configuration process works, add an brief explanation about what each command does and clarify that the code samples are command line calls, not config file entries

Add clarification for IDEA setup in README

---

.editorconfig
CHANGELOG.md
README.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleAsciiTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleIdeaTest.kt

Deprecate shorcuts for import-ordering

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/KtLintTest.kt
ktlint-core/src/test/resources/spec/format-unicode-bom.kt.spec

Retain the UTF8 BOM (Byte Order Mark) in case present in original code

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRuleTest.kt
ktlint-ruleset-standard/src/test/resources/spec/string-template/format-expected.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/string-template/format.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/string-template/lint.kt.spec

Given code example below:
```
fun getDrafts(val draftsIds: List<Long>) {
println("draftIds=[${'$'}{draftsIds.toString()}]")
}
```
Formatting with autocorrect of this code fails on the no-unused-imports rule as the dot-expression node still exists but the toString invocation was already removed.
Resolves #996

Fix string-template for dot-expression from which the  toString() is removed

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt

Fix false positive when argument list is after multiline dot-qualified expression

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Closes #918 
Other issues reported in the comments were already fixed.

Fix indentation for function types after a newline

---

README.md

Should reduce confusion when `.editorconfig` properties are not picked up by ktlint (Related to #762)

Add to README section about IDEA .editorconfig autoformat issue.

---

README.md

New PR to replace #948  :) 
ktlint page in Mega-Linter documentation is the following: https://nvuillam.github.io/mega-linter/descriptors/kotlin_ktlint/
Please notify me if you have any suggestion to improve it :)

Add CI & Mega-Linter link in README

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoLineBreakBeforeAssignmentRuleTest.kt

Don't remove the equals sign for a default argument (`no-line-break-before-assignment`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StringTemplateRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetIntegrationTest.kt

Fixes #1040
Test code to reproduce in master (780d11a2c1539f8011a6271b2cc97806d0c90aa8):
```kotlin
@Test
fun test() {
val actual = KtLint.format(
KtLint.Params(
text = """
fun foo() = 1
fun test() {
println("${'$'}{foo().toString()}")
}
""".trimIndent(),
ruleSets = listOf(StandardRuleSetProvider().get()),
cb = { _, _ -> }
)
)
assertThat(actual).isEqualTo(
"""
fun foo() = 1
fun test() {
println("${'$'}{foo()}")
}
""".trimIndent()
)
}
```

Fix internal error in `no-unused-imports`

---

build.gradle

ec4j 0.3.0 removes the length limit of key, value and section name in editor config files.
Fixes #739.

Upgrade ec4j to latest version

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithCommentsRuleTest.kt

Fix false positives when declaration has tail comments (`spacing-between-declarations-with-comments`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundColonRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt

Fix formatting with comments (`colon-spacing`)

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRuleTest.kt

Fix formatting in arguments (`multiline-if-else`)

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRuleTest.kt

There was a bug with the experimental annotation-spacing-rule where it would flag a comment separating an annotation from the annotated construct, but fail to autocorrect it.
This fixes the bug as well as clarifies the error message.
- [x ] tests are added
- [x ] `CHANGELOG.md` is updated

Annotation spacing fix

---

CHANGELOG.md
README.md
build.gradle
ktlint/build.gradle
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/PrintASTSubCommand.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/internal/FileUtilsFileSequenceTest.kt

Migrate method to get all mathing globs files to use internally `PathMatcher` and `FileVisitor` instead of using klob dependency.
Fixes #999

Fix negated globs passed to CLI are no longer worked.

---

CHANGELOG.md
ktlint-core/build.gradle
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/OptInFeatures.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/PatternEntry.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GenerateEditorConfigSubCommand.kt

Add new parameter to add/replace loaded values from `.editorconfig` files.
Fixes #1016

Allow to add/replace loaded values from '.editorconfig' files

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/LintError.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ReporterProvider.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/RuleSetProvider.kt
ktlint-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/reporter/baseline/BaselineReporterProvider.kt
ktlint-reporter-checkstyle/src/main/kotlin/com/pinterest/ktlint/reporter/checkstyle/CheckStyleReporterProvider.kt
ktlint-reporter-html/src/main/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporterProvider.kt
ktlint-reporter-json/src/main/kotlin/com/pinterest/ktlint/reporter/json/JsonReporterProvider.kt
ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-template/src/main/kotlin/yourpkgname/CustomRuleSetProvider.kt

Required for better Gradle plugin support.

ReporterProvider, LintError and RuleSetProvider now implement Serializable interface

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/BaselineSupport.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/BaselineSupportTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Makes it easier to add baseline support for 3rd party tools ([for example](https://github.com/JLLeitschuh/ktlint-gradle/issues/414))

Move baseline utils into 'ktlint-core' package.

---

CHANGELOG.md

Setting up changelog for 0.41.0
- [ x ] `CHANGELOG.md` is updated

prep CHANGELOG for 0.41.0

---

gradle/verification-metadata.xml

I thought all of the jetbrains artifacts had been migrated to new servers, but that's not the case. Some are still signed with the old Bintray key.

Fix snapshot builds

---

ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt

This PR proposes a solution for the performance issue described in #1135.
When ktlint gets a bunch of absolute paths there is no need to walk through the file system and search for them, we can just resolve and analyze them directly.
Before:
```
➜  android-listeners git:(rc/kitlint) ktlint -F --debug --relative MyFile.kt
[DEBUG] Discovered ruleset with "standard" id.
[DEBUG] Discovered reporter with "baseline" id.
[DEBUG] Discovered reporter with "checkstyle" id.
[DEBUG] Discovered reporter with "json" id.
[DEBUG] Discovered reporter with "html" id.
[DEBUG] Discovered reporter with "plain" id.
[DEBUG] Initializing "plain" reporter with {verbose=true, color=false, color_name=DARK_GRAY}
[DEBUG] Checking MyFile.kt
Loaded .editorconfig: [insert_final_newline: true, max_line_length: 200] …
```

Improve ktlint performances when the input patterns are absolute paths

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix false positive with 'by lazy {}' (`indent`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/resources/spec/indent/format-argument-list-expected.kt.spec

Fix false positive with value argument list has lambda (`indent`)

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt

Fix false positive in lambda in dot qualified expression (`argument-list-wrapping`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix false positive with multiline expression with elvis operator in assignment (`indent`)

---

CHANGELOG.md
gradle/verification-metadata2.xml
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportSorter.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleAsciiTest.kt

Backticks are now ignored when ordering imports
- [ x ] tests are added
- [ x ] `CHANGELOG.md` is updated

Ignore backticks when ordering imports. Fixes #1106

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ChainWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ChainWrappingRuleTest.kt

Fix false positive with elvis operator and comment (`chain-wrapping`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ChainWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ChainWrappingRuleTest.kt

Fix false negative in when conditions (`chain-wrapping`)

---

CHANGELOG.md
ktlint-reporter-html/src/main/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporter.kt
ktlint-reporter-html/src/test/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporterTest.kt

Fixes #1140 .
Insert
```
<meta http-equiv="Content-Type" Content="text/html; Charset=UTF-8">
```
to ktlint.html head.
And update HtmlReporterTest.

Fix The Html reporter Chinese garbled.

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix false positive with delegated properties (`indent`)

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

- Used imports state has to be reset per-file
- A regression was introduced to the `no-unused-imports` rule where it would report false positives 
- Add auto-correction to the case of repeated imports

Re-apply #1129 with fixes for regressions

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix false positive with lambda argument and call chain (`indent`)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoTrailingSpacesRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoTrailingSpacesRuleTest.kt

Closes #1197
The trailing spaces rules only looked as PsiWhiteSpace elements. Now also the PsiComment element is inspected and fixed if needed. Rule has been refactored entirely to make it more readable and to explain why the last line of a PsiWhiteSpace element is ignored.

Lint and format trailing spaces inside block comments

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundParensRuleTest.kt

Closes #1207
Add condition for primary constructor in oarrn-soacing rule

Remove spaces before primary constructor

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix #850 
The space before the continuation and end of a KDoc line is now preserved in case the tab indentation style is used.
Fixes https://github.com/pinterest/ktlint/issues/850

Fix KDOC indentation for tab indentation style

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/trailingcomma/TrailingCommaRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/TrailingCommaRuleTest.kt

Closes #1280
The property setter has exactly 1 argument. As a result a special kind of parameter list is provided, which resulted in a NoSuchElementException.  The same construct which caused this exception is used in other cases in this rule as well. However, I as not able to construct any tests in which that would lead to an error as well.

Fix NoSuchElementException in trailing-comma rule in property accessor

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/trailingcomma/TrailingCommaRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/TrailingCommaRuleTest.kt

The code previously contained special handling for case below:
```
@Annotation([
"something",
])
```
This special case however was also triggered in case of:
```
@Annotation(
foo = [
"something"
],
bar = "some-bar"
)
```
In this case the normal handling of value argument lists should be used once for the outer value argument list (containing elements foo and bar) and once for the inner value argument list of parameter foo (containing element "something"). So in example above, a trailing comma has to be added to both the outer and the inner value argument list.
Closes #1297

Do not remove trailing comma in value argument list in annotation

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

Fix indentation of secondary constructor
The call to `super` needs an additional indent compared to other situation in which a colon is found. Resulting code now looks like:
```
class Issue1222 {
constructor(string1: String, string2: String2) :
super(
string1, string2
) {
// do something
}
}
```
Closes #1222

Fix indentation of secondary constructor

---

CHANGELOG.md
build.gradle
gradle/verification-metadata.xml
ktlint/build.gradle
ktlint/src/test/kotlin/com/pinterest/ktlint/BaseCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/SimpleCLITest.kt
ktlint/src/test/resources/cli/no-code-style-error/main.kt
ktlint/src/test/resources/cli/too-many-empty-lines/main.kt

These tests are using command line artifact to validate it is working. Additionally test are taking into account current test JVM toolchain to find 'java' executable.
Fixes #540

Add basic CLI tests.

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/trailingcomma/TrailingCommaRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/TrailingCommaRuleTest.kt

Fix alignment of arrow when trailing comma is missing in when entry.
Closes #1312

Fix alignment of arrow when trailing comma is missing in when entry

---

README.md

Fix for the example gradle config, because JavaExec main = "xxx" is deprecated and should be replaced with mainClass Property.

Fix warn in gradle config ex. replace main > mainClass

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitHookInstaller.kt

It is not worth it to ensure that the git hook installation is completely fool proof. I have just added a small note which is displayed on successful install of the git hook:
```
Be aware that this hook assumes to find ktlint on the PATH. Either
ensure that ktlint is actually added to the path or expand the ktlint command in the hook with the path.
```
It is reasonable to expect from a developer that (s)he knows how to fix the path.
Closes #634

Display explanatory note about path after installing a git hook

---

CHANGELOG.md
ktlint/build.gradle

Conditionally add `--add-opens` flag based on java version
Fixes https://github.com/pinterest/ktlint/issues/1195
- [ x ] `CHANGELOG.md` is updated

Fix for Java 16+ CLI

---

CHANGELOG.md
build.gradle
buildSrc/src/main/kotlin/ToolchainForTests.kt
gradle/verification-metadata.xml
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/7.4/release-notes.html
The [Version catalogs](https://docs.gradle.org/7.4/userguide/platforms.html) is promoted to a stable feature.

Adopt Gradle 7.4

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/EditorConfig.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/IndentConfig.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt

As described in #1255, the code below execeeds the max line length:
```
var changesListener: ((width: Double?, depth: Double?, length: Double?, area: Double?) -> Unit)? = null
```
and got formatted as:
```
var changesListener: (
(
width: Double?,
depth: Double?,
length: Double?,
area: Double?
) -> Unit
)? = null
```
When the nullable type is removed from the original example:
```
var changesListener: (width: Double?, depth: Double?, length: Double?, area: Double?) -> Unit
```
it gets formatted as:
```
var changesListener: (
width: Double?,
depth: Double?,
length: Double?,
area: Double?
) -> Unit
```
So, it turned out that the nullable type around function type `(width: Double?, depth: Double?, length: Double?, area: Double?) -> Unit` was the real cause of the problem. Both the nullable …

Wrapping of function type inside nullable type

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ReporterProvider.kt
ktlint-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/reporter/baseline/BaselineReporterProvider.kt
ktlint-reporter-checkstyle/src/main/kotlin/com/pinterest/ktlint/reporter/checkstyle/CheckStyleReporterProvider.kt
ktlint-reporter-html/src/main/kotlin/com/pinterest/ktlint/reporter/html/HtmlReporterProvider.kt
ktlint-reporter-json/src/main/kotlin/com/pinterest/ktlint/reporter/json/JsonReporterProvider.kt
ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterProvider.kt
ktlint-reporter-plain/src/test/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterProviderTest.kt
ktlint-reporter-sarif/src/main/kotlin/com/pinterest/ktlint/reporter/sarif/SarifReporterProvider.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Return subtypes when invoking `get()`

Add a generic type to ReporterProvider

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt

Cleanup unused parameter editorConfig in indentation rule

Cleanup unused parameter editorConfig

---

CHANGELOG.md
ktlint-reporter-plain/src/main/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporter.kt
ktlint-reporter-plain/src/test/kotlin/com/pinterest/ktlint/reporter/plain/PlainReporterTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt

The rule id was printed in by the PlainReporter only when the verbose mode was enabled. Now it will also be printed in case the verbose mode is not enabled. In this way it is easier to discover the correct rule id which is to be used to suppress a lint violation.

Print the rule id in the PlainReporter

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRuleTest.kt

Change message from "Unnecessary space(s)" to "Unnecessary long whitespace". The length of the whitespace element is considered while it is not checked whether the whitespace actually contains spaces only. However, it still make sense to replace a non-indent whitespace which is too long, by a single space.
Closes #1394

Change message from "Unnecessary space(s)" to "Unnecessary long whitespace"

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRuleTest.kt
ktlint-ruleset-standard/src/test/resources/spec/indent/format-multiline-string-expected.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/indent/format-multiline-string.kt.spec
ktlint-ruleset-standard/src/test/resources/spec/indent/format-raw-string-trim-indent-expected.kt.spec

Do not indent raw string literals that are not followed by either trimIndent() or trimMargin()

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt

There is no reliable way to determined whether a wildcard import is actually used
in the file. The AST does not seem to contain information about the actuall class
that an identifier refers to. It is preferred to not remove unused imports than
that needed imports are removed.
Revert #1256
Closes #1277
Closes #1393

Revert removal of unused wildcard imports (#1256) as it can lead to removal of required imports

---

CHANGELOG.md
README.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/CommentWrappingRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/KdocWrappingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/CommentWrappingRuleTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/KdocWrappingRuleTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoSemicolonsRule.kt

Add new experimental rules for wrapping of block comments and KDoc comments. Both block comments as well as KDoc comments should always start and end on a line which does not contain any other element (except the whitespace for indentation). Block comments at the end of a line and which are preceded by another element, are automatically converted to an EOL comment.
Closes #1329

Wrapping block and kdoc comments

---

CHANGELOG.md

Fix changelog so that changes are listed in correct version.
- [N/A] `README.md` is updated
- [N/A] Rule has been applied on Ktlint itself and violations are fixed

Fix changelog, some entries were merged with 0.44.0 version instead 0f 0.45.0 version

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/KotlinPsiFileFactory.kt

Explicitly dispose the disposable which is created in initPsiFileFactory to prevent leakage of memory. I do not claim to understand or be 100% sure that this resolves #1216 but results on the local machine looked promising. For this I temporarily modified the lint-method so that it continuously kept on scanning the same file. 
```
@OptIn(FeatureInAlphaState::class)
internal fun lintFile(
fileName: String,
fileContents: String,
ruleSets: Iterable<RuleSet>,
visitorProvider: VisitorProvider,
userData: Map<String, String> = emptyMap(),
editorConfigPath: String? = null,
debug: Boolean = false,
lintErrorCallback: (LintError) -> Unit = {}
) {
repeat(1_000_000) {
KtLint.lint(
KtLint.ExperimentalParams(
fileName = fileName,
text = fileContents,
ruleSets = ruleSets,
userData = userData,
script = …
```

Memory leak in initPsiFileFactory

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLintKLoggerInitializer.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Initialize the logger in Main only after the CLI parameters have bee parsed parsed. Also, propagate the log level correctly to the KLogger.
Closes #1412

Initialize the logger in Main only after the CLI parameters have bee parsed

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ModifierListSpacingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ModifierListSpacingRuleTest.kt

Fix bug. Do not distinct between ANNOTATION and ANNOTATION_ENTRY.
Closes #1414

An annotation array may be placed on a separate line

---

CHANGELOG.md
buildSrc/src/main/kotlin/ToolchainForTests.kt
buildSrc/src/main/kotlin/ktlint-kotlin-common.gradle.kts

Tests should run on all supported Java versions. So added JDK 17. 

Add tests based on JDK 17

---

build.gradle
ktlint-core/build.gradle
ktlint-reporter-baseline/build.gradle
ktlint-reporter-checkstyle/build.gradle
ktlint-reporter-html/build.gradle
ktlint-reporter-json/build.gradle
ktlint-reporter-plain/build.gradle
ktlint-reporter-sarif/build.gradle
ktlint-ruleset-experimental/build.gradle
ktlint-ruleset-standard/build.gradle
ktlint-ruleset-template/build.gradle
ktlint-ruleset-test/build.gradle
ktlint-test/build.gradle
ktlint/build.gradle
settings.gradle

https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors
Ref https://github.com/detekt/detekt/pull/3742

Enable type-safe project accessors

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLintKLoggerInitializer.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

* The default loggerModifier can only be set once.
* It is still possible to override the loggerModifier for a specific class by passing a loggerModifier to initKtLintKLogger.
* When initKtLintKLogger is called without parameter, the defaultLoggerModifier is applied when set.

Allow to set a default logger modifier

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLintKLoggerInitializer.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleExtension.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt

Hide variable defaultLoggerModifier and enforce that it can be set via function setDefaultLoggerModifier only. In this way, a warning can be printed if it is set more than once which could lead to unpredictable behavior.

1421 logger initialization improvement

---

CHANGELOG.md
ktlint-core/build.gradle
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/EditorConfigOverride.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/KtLintTest.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/TrailingCommaRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoWildcardImportsRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleAsciiTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleCustomTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleIdeaTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleExtension.kt

* Deprecate data class 'Params' as it only provides the userData parameter  which prohibits API Consumers to split the '.editorconfig' properties  from the other user data.
* Deprecate function 'toExperimentalParams' to force API Consumers to  start using the 'ExperimentalParams'.
* In ExperimentalParams clarify that 'userData' should not contain any  '.editorconfig' properties. Now also a runtime error is thrown  whenever the lint/format methods are called and 'userData' contains  '.editorconfig' properties.
* Remove confusing TODO's about moving methods 'lint' and 'format' to  the 'ktlint-test' module.
* Update deprecation messages to clarify intention.
* The 'lint' and 'format' methods in module 'ktlint-core' no longer  call the 'VisitorProvider' with parameter 'isUnitTestContext' …

Fix backward incompatibility issues released via KtLint 0.45.0 and 0.45.1

---

README.md

I recently wrote a new custom ktlint reporter and this pull request adds a link to it in the README

Add new link to third-party reporter

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/TypeParameterListSpacingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/TypeParameterListSpacingRuleTest.kt

Do not add a space after the typealias name (`type-parameter-list-spacing`)

---

CHANGELOG.md
buildSrc/build.gradle.kts

https://github.com/JetBrains/kotlin/releases/tag/v1.7.0-Beta

Bump Kotlin dev version to 1.7.0-Beta

---

CHANGELOG.md
README.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ExperimentalRuleSetProvider.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionStartOfBodySpacingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/EditorConfigTestRule.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

This rule rewrites the function signature to a single line when possible (e.g. when not exceeding the "max_line_length" property) or a multiline signature otherwise. In case of function with a body expression, the body expression is placed on the same line as the function signature when not exceeding the "max_line_length" property. Optionally the function signature can be forced to be written as a multiline signature in case the function has more than a specified number of parameters (".editorconfig" property "ktlint_function_signature_wrapping_rule_always_with_minimum_parameters")
Fixed the FunctionStartOfBodySpacingRule to add the missing space before start of the block body before the BLOCK element type instead of as first element inside the BLOCK element.
Closes #1341 
In case of …

Add new experimental rule "function-signature"

---

CHANGELOG.md
README.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoBlankLinesInChainedMethodCallsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoBlankLinesInChainedMethodCallsRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRuleTest.kt

Closes #1248
There's a lot of discussion in the issues as to the right approach, but here's my proposal for a fix. Given the rule is intended to detect "consecutive" blank lines, I've made sure a single blank line is allowed in a chained expression (but that multiple is still disallowed and formats correctly). This will allow for the "blank line followed by a comment" examples brought up in the issue and keeps the whitespace rules consistent between regular statements and chained expressions.
The reasoning behind arguing for blank lines to be allowed in chained expressions is that there's nothing about disallowing them in either the [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html) or the [Android Kotlin style …

Allow a single whitespace line in chained expressions

---

CHANGELOG.md
buildSrc/build.gradle.kts

https://github.com/JetBrains/kotlin/releases/tag/v1.7.0-RC2

Bump Kotlin dev version to 1.7.0-RC2

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/UsesEditorConfigPropertiesTest.kt

Fixes https://github.com/pinterest/ktlint/issues/1485.

Fix crash when indentSize isn't set to an Int.

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleSetProviderTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt

Ensure that rules in non-standard rulesets are prefixed with the rulesetId

Ensure that rules in non-standard rulesets are prefixed with the rulesetId

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ParameterListSpacingRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ParameterListSpacingRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Allow a function signature containing an EOL comment at the place of he parameter list to precede the EOL comment with a space as this is required by the 'comment-spacing' rule
```
data class Foo @JvmOverloads constructor( // ktlint-disable annotation
)
@JvmOverloads fun foo1( // ktlint-disable annotation
)
```

Allow space before EOL comment in function parameter list

---

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt

* Reformat to a multiline function signature when at least one parameter annotation is not on the same line as the parameter identifier.
* Reformat a single line function signature which fits on a single line in case the function has too many parameters

Reformat to a multiline function signature fixes

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FilenameRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FilenameRuleTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ApplyToIDEAGloballySubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/ApplyToIDEAProjectSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GenerateEditorConfigSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitPreCommitHookSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/GitPrePushHookSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/LoadRuleSets.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/PrintASTSubCommand.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/PrintCommandLineHelpOrVersionUsage.kt

As result of an earlier refactor of this rule to comply with the Pascal Case Convention, the rule no longer enforced naming of files containing a single top level declaration for an object, type alias and function.
A file containing only one (non private) top level declaration (class, interface, object or type alias) must be named after that declaration. The name also must comply with the Pascal Case convention. The same applies to a file containing one single top level class declaration and one ore more extension functions for that class.

Filename should not be restricted to top level class declarations

---

.github/workflows/gradle-docs-publish.yml
doc/docs/index.md
doc/mkdocs.yml
doc/readme.md

Replace old github pages documentation with mkdocs-material. This PR only configuration the build pipeline and replaces the old documentation with a temporary placeholder. Once it is verified that the pipeline works, we can start writing the new documentation.
Most likely, some additional steps are needed:
* [Configure the branch](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) for which admin settings are required
* Disabling publication of old site

Setup publication of documentation with mkdocs-material to github pages

---

CHANGELOG.md
buildSrc/src/main/kotlin/ktlint-kotlin-common.gradle.kts

Using K2 means library consumers must also use the new compiler (and may not be ready to), otherwise they will have errors like "\<classname> is compiled by the new Kotlin compiler frontend and cannot be loaded by the old compiler"

Use stable Kotlin compiler frontend

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/VisitorProvider.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/VisitorProviderTest.kt

IntelliJ reformats the disabled_rules of the editor config and adds spaces between the entries.
For example:
```properties
[*]
disabled_rules = import-ordering,filename,trailing-comma
```
Will be reformatted to:
```properties
[*]
disabled_rules = import-ordering, filename, trailing-comma
```
With the whitespace included, ktlint does not pick up these rules.
This PR accounts for these white spaces and modifies the existing tests to also cover this scenario.

Account for separating spaces when parsing the disabled rules.

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

A delegate property which starts on the same line as the property declaration should not have an extra indentation. This fixes a regression bug introduced by the fix of #1340.
Closes #1510

Fix regression bug caused by #1340

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/SimpleCLITest.kt

Fix regression on command line argument "--disabled_rules" and align code other unit tests
Closes #1520

Fix regression on command line argument "--disabled_rules"

---

README.md

When this rule was promoted to the standard rule set it was not added to the standard rule list

Add traling-comma rule in the standard rule list in README

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/KtLintTest.kt

The callback function provided as parameter to the format function is now called for all errors regardless whether the error has been autocorrected. Existing consumers of the format function should now explicitly check the `autocorrected` flag in the callback result and handle it appropriately (in most case this will be ignoring the callback results for which `autocorrected` has value `true`).  
Closes #1491

Call callback on all errors

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt

Prevent class cast exception when retrieving ktlint_code_style property from ".editorconfig"
Closes #1559

Prevent class cast exception when retrieving ktlint_code_style property

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/SuppressionLocatorBuilder.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/AnnotationSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MultiLineIfElseRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/MultiLineIfElseRuleTest.kt

Add missing whitespace when else is on same line as true condition
Closes #1560
Report violations for:
```
if (true) 50
.toString()
if (true) 50
else 55
```
Closes #828

Add missing whitespace when else is on same line as true condition

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt

Merge first line of body expression with function signature only when it fits on the same line.
Closes #1527

Merge first line of body expression with function signature

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRuleTest.kt

Fix indent of when entry with a dot qualified expression (for example a qualified enum value) instead of simple value when trailing comma is required:
```
fun bla(value: Test) = when (value) {
Test.TEST_1,
Test.TEST_2, -> {
println("1, 2")
}
Test.TEST_3 -> {
println("3")
}
}
```
and format as:
```
fun bla(value: Test) = when (value) {
Test.TEST_1,
Test.TEST_2,
-> {
println("1, 2")
}
Test.TEST_3 -> {
println("3")
}
}
```
If whitespace after trailing comma is missing or does not contain a newline:
```
fun bla(value: Test) = when (value) {
Test.TEST_1,
Test.TEST_2, -> {
println("1, 2")
}
Test.TEST_3,
Test.TEST_4,-> {
println("3,4")
}
Test.TEST_5 -> {
println("5")
}
}
```
then format as:
```
fun bla(value: Test) = when (value) {
Test.TEST_1,
Test.TEST_2,
-> {
println("1, 2")
}
Test.TEST_3, …
```

Improve trailing comma in when entry

---

.announce
CHANGELOG.md
RELEASING.md

Update `.announce` to set the version number in the mkdocs documentation whenever publishing/announcing a new release.
Closes #1575 

Set version number in documentation when publishing/announcing a new release

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRuleTest.kt

Prevent false positive in parameter list for which the last value parameter is a destructuring declaration followed by a trailing comma
Closes #1578

Fix false postive when wrapping destructuring declaration followed by trailing comma

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/ThreadSafeEditorConfigCache.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/ThreadSafeEditorConfigCacheTest.kt

Some API Consumers keep a long-running instance of the KtLint engine alive. In case an `.editorconfig` file is changed, which was already loaded into the internal cache of the KtLint engine this change would not be taken into account by KtLint. One way to deal with this, was to clear the entire KtLint cache after each change in an `.editorconfig` file.
Now, the API consumer can reload an `.editorconfig`. If the `.editorconfig` with given path is actually found in the cached, it will be replaced with the new value directly. If the file is not yet loaded in the cache, loading will be deferred until the file is actually requested again.

Reload ".editorconfig"

---

docs/rules/experimental.md

This experimental rule is currently not listed in the docs.

Add `experimental:type-argument-list-spacing` rule to docs

---

docs/rules/standard.md

This standard rule is currently not listed in the docs.

Add `wrapping` rule to docs

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt

Set property "ktlint_disabled_rules" instead of "disabled_rules" when using CLI parameter as otherwise the deprecation warning is displayed
Closes #1599

Set property "ktlint_disabled_rules" with CLI "--disabled-rules"

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/EditorConfigDefaultsLoaderCLITest.kt
ktlint/src/test/resources/cli/editorconfig-path/project/editorconfig-boolean-setting

Fix class cast exception when specifying a non-string editorconfig setting in the *default* `.editorconfig`. When reading the *default* `.editorconfig` the property can not yet be matched with any on the properties defined in the rulesets. As a result the type of the property is unknown (null). When retrieving a value from a property with type `null` this resulted in a class cast exception whenever a value of another type than `String` is expected. In this change, the `null` type is detected and the proper `type` is determined by reading the property type from the properties which are registered in the rule.
Closes #1627

Fix class cast exception caused by default ".editorconfig"

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/internal/FileUtilsTest.kt

Globs always use a "/" as directory separator on all OS's. Input patterns containing a "\" on Windows OS are transformed to "/" as users on Windows more likely would assume that the "\" may be used.
On WindowsOS, transform "\" in the filepath to "/" before comparing the filename with the regular expression (of the glob) which always uses "/" as separator.
Refactor all logic which create globs based on an input path.
- If a path (absolute or relative) point to a directory, that path is expanded to the default globs (*.kt, *.kts) in that specific directory or any of its subdirectories.
- If a path (absolute or relative) does not point to a directory, e.g. it
  points to a file, or it is a pattern. See "**" replacement below.
- On Windows OS patters containing a "*" (or "**") can not be …

Fix traversing the directory hierarchy on WindowsOS / Ant-style path matching

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/BaseCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/EditorConfigDefaultsLoaderCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/SimpleCLITest.kt

Display warning instead of error when no files are matched, and return with exit code 0.
Closes #1624 

Warn on no files matched

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRuleTest.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt

Fix indentation before semi-colon when it is pushed down after inserting a trailing comma
Closes #1609 

enum trailing comma

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/SuppressionLocatorBuilder.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/KtLintTest.kt

Apply `@file:Suppress` on all toplevel declarations

---

.homebrew

When doing the 0.47.1 release, the homebrew step failed due to bump-formula-pr erroring out saying it needed a formula name.

brew bump-formula-pr needs a formula name now

---

docs/install/cli.md

This PR simply fixes a typo in the cli docs.

Fix typo: maxOC -> macOS

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleExecutionContext.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/SuppressHandler.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/ast/PackageKtTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt

fix ktlint indentation rule has problems with ignoring braces #1644

fix indentation rule has problems with ignoring braces

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRuleTest.kt

* Do not add a trailing comma in a function call if a newline character is only found inside a multiline argument. Only in case a newline character is found between arguments, this should be taken into account to add a trailing comma.
* Refactor and cleanup unused branches in isMultiline method
Closes #1642

Newline inside value argument should not trigger trailing comma rule

---

build.gradle
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/RuleExtension.kt

* Do not run ktlint check with option "--verbose" or "-v" as the lint violations are difficult to spot between the amount of debug output lines
* Run lint and formatting from RuleExtension always with debug enabled so that order in which rules are executed is visible in logging
* Fix non-existing reference to method
- [N/A] PR description added
- [N/A] KtLint has been applied on source code itself and violations are fixed
- [N/A] [documentation](https://pinterest.github.io/ktlint/) is updated
- [N/A] `CHANGELOG.md` is updated

Housekeeping

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRuleTest.kt

Wrap start/end of an element of type BLOCK in case the line containing that element exceeds the max line length or in case the block contains a newline
Closes #1643

Wrapping element of type BLOCK

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigFinder.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/ThreadSafeEditorConfigCache.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigFinderTest.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/ThreadSafeEditorConfigCacheTest.kt

The list of files which will be accessed by KtLint when linting or formatting a given path can now be retrieved with the new API `KtLint.getInputPaths(path: Path): List<Path>`. Currently, the `.editorconfig` files are the only files which will be accessed during linting or formatting in addition to the source files itself. 
This API can be called with either a file or a directory. It's intended usage is that it is called once with a directory path before actually linting or formatting files. When called with a directory path, all `.editorconfig` in the directory or any of its subdirectories (except hidden directories) are returned. In case the given directory does not contain an `.editorconfig` file or if it does not contain the `root=true` setting, the parent directories are scanned as …

Add API for retrieving the list of files that will be accessed

---

CHANGELOG.md
docs/install/cli.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt
ktlint/src/main/resources/ktlint-git-pre-commit-hook-android.sh
ktlint/src/main/resources/ktlint-git-pre-commit-hook.sh
ktlint/src/main/resources/ktlint-git-pre-push-hook-android.sh
ktlint/src/main/resources/ktlint-git-pre-push-hook.sh
ktlint/src/test/kotlin/com/pinterest/ktlint/BaseCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/EditorConfigDefaultsLoaderCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/RuleSetsLoaderCLITest.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/SimpleCLITest.kt

This PR adds the option~~s~~ `--patterns-from-stdin[=<delimiter>]` ~~and `-z`~~ that'll read patterns separated by a delimiter (default is newline, giving an empty string ~~or using the `-z` option~~ is `NUL` byte) and add them to the patterns given on the command line.
Since the `--stdin` option would already read from `stdin`, it'll throw an exception if both `--stdin` and `--patterns-from-stdin`~~/`-z`~~ are given.
These options were primarily added to update the Git hook scripts.  
The main problems with the old ones were that files with special characters (e.g.: newline) in the name would not be passed along correctly (since Git quotes those filenames without the `-z` option) and that the `--no-run-if-empty` hack wouldn't work on non-GNU systems. (since that option is a GNU …

Option `--patterns-from-stdin` and Git hook scripts update

---

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigFinder.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigFinderTest.kt

Attempt to improve performace of API with caching. See #1659 for context.

Improve caching of API for retrieving the list of files that will be accessed

---

CHANGELOG.md
docs/faq.md
docs/rules/configuration-ktlint.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGeneratorTest.kt

`editorConfigProperties` seemed to be missing the newly created `ktlintDisabledRulesProperty`. For any downstream plugins that rely on this value to know what properties are valid for ktlint, they may filter out anything but these properties. 
Ultimately, this could leads to errors like the following if that's the only editor config override provided:
>Can not create an EditorConfigOverride without properties. Use 'emptyEditorConfigOverride' instead.
Or if it's not, I can safely assume that the disabled rules will be ignored if `disabled_rules` aren't provided as well.
Currently, `disabled_rules` still works but it spams a lot of messages stating that it is disabled. I find this to be an unpleasant developer experience and also leads to confusion for a developer who is simply switching to …

Register missing ktlint_disabled_rules in editorConfigProperties

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt

Handle function signature preceded by an annotation array similar to function preceded by a singular annotation
Closes #1690

Function signature preceded by an annotation array

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ast/package.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRuleTest.kt

Do not add a second trailing comma, if the original trailing comma is followed by a KDOC
Closes #1676

Trailing comma followed by a KDOC

---

CHANGELOG.md
docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt

[Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html#trailing-commas) says:
>  The Kotlin style guide encourages the use of trailing commas at the declaration site
But ktlint's default config for this rule enforces no comma which directly conflicts with the coding conventions which _encourages_ trailing commas.

Enforce trailing commas at declaration site by default

---

CHANGELOG.md
gradle/libs.versions.toml

https://github.com/JetBrains/kotlin/releases/tag/v1.7.21

Bump Kotlin to 1.7.21

---

CHANGELOG.md
gradle/libs.versions.toml

https://github.com/JetBrains/kotlin/releases/tag/v1.8.0-Beta

Bump Kotlin dev version to 1.8.0-Beta

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/KtLintRuleException.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt

Refactor exception handling during lint and format. Reduce length of stacktrace by propagating root cause only. Add filename to exception message.

Refactor exception handling during lint and format

---

CHANGELOG.md
gradle/libs.versions.toml

https://github.com/JetBrains/kotlin/releases/tag/v1.8.0-RC

Bump Kotlin dev version to 1.8.0-RC

---

.gitignore
RELEASE_TESTING.MD
docs/contributing/guidelines.md
docs/extensions/custom-reporter.md
docs/extensions/custom-rule-set.md
docs/index.md
docs/install/cli.md
docs/readme.md
docs/rules/dependencies.md
docs/rules/standard.md

[The website's front page](https://pinterest.github.io/ktlint/) has a few broken links. They use anchors (e.g. `#editorconfig`), but clicking them doesn't do anything.
I tried to fix them by changing them to absolute links. I considered using relative links, but saw that that page also has other absolute links to the documentation itself.
I wasn't sure where to link the `#editorconfig` to, because there are multiple places where EditorConfig is discussed in different ways. In the end I just guessed which one would be more appropriate, but maybe the right answer was to remove the link?
PS: I just noticed there are also other dead links on the website :/
PPS: In the [rule configuration section](https://pinterest.github.io/ktlint/install/cli/#rule-configuration-editorconfig), there is a link …

Fix links on main doc page

---

build.gradle.kts

Previously, the task would throw an error:
```
$ ./gradlew githubRelease
Type-safe project accessors is an incubating feature.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':githubRelease'.
> Cannot query the value of this provider because it has no value available.
```
Tested via a dry run:
```
./gradlew githubRelease
Type-safe project accessors is an incubating feature.
> Task :githubRelease
Execution optimizations have been disabled for task ':githubRelease' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/Users/shasha/code/ktlint/ktlint/build/run'. Reason: Task ':githubRelease' uses this output of task ':ktlint:shadowJarExecutableChecksum' without declaring an …
```

Fix githubRelease script

---

build.gradle.kts

My previous fix for the githubRelease task didn't work, so temporarily hardcoding the files to upload.
cc @Goooler 
Despite the output being wrapped in a provider, if you clean first, running githubRelease as it was (both before and after my fix) results in the following error:
```
./gradlew githubRelease
Type-safe project accessors is an incubating feature.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':githubRelease'.
> Cannot query the value of this provider because it has no value available.
```
Do you think this needs to be fixed in the plugin or on our side? It seems to be querying the `releaseAssets` files at config time.
Dry run output:
```
> Task :githubRelease
:githubRelease [This task is a dry run. All API calls that …
```

Temporarily hardcode the list of files to upload to github

---

.announce

- Deleted updates to ktlint.github.io since it now redirects to pinterest.github.io/ktlint
- Made the script more robust

Announce script cleanup

---

.announce
.github/workflows/release.yml
RELEASING.md
build-logic/src/main/kotlin/ktlint-publication.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

Moving releases to GH Actions so that @shashachu isn't as much of a release bottleneck.
A test release on my fork:
https://github.com/shashachu/ktlint/releases/tag/0.49.3
A Homebrew PR:
https://github.com/Homebrew/homebrew-core/pull/118545
- [ x ] PR description added

Move release process to GitHub Actions Workflow

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt
ktlint/src/test/kotlin/com/pinterest/ktlint/SimpleCLITest.kt

Disable the `standard:filename` rule whenever Ktlint CLI is run with option `--stdin
Closes #1742 

Disable the `standard:filename` rule whenever Ktlint CLI is run with option `--stdin

---

CHANGELOG.md
ktlint-api-consumer/build.gradle.kts
ktlint-api-consumer/gradle.properties
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/KtlintApiConsumer.kt
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/Main.kt
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/rules/CustomRuleSetProvider.kt
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/rules/NoVarRule.kt
ktlint-api-consumer/src/main/readme.md
ktlint-api-consumer/src/test/kotlin/com/pinterest/ktlint/api/consumer/ApiTestRunner.kt
ktlint-api-consumer/src/test/kotlin/com/pinterest/ktlint/api/consumer/KtLintRuleEngineTest.kt
ktlint-api-consumer/src/test/readme.md
ktlint-api-consumer/src/test/resources/api/no-code-style-error/Main.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleExecutionContext.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/ast/PackageKtTest.kt
settings.gradle.kts

Add API so that KtLint API consumer is able to process a Kotlin script snippet without having to specify a file path
Closes #1738

Add API to process a Kotlin script snippet

---

CHANGELOG.md
ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintCommandLine.kt

Fix initialization of the logger when `--log-level` is specified. Throw exception when an invalid value is passed.
Closes #1749 

Fix initialization of the logger

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRule.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionSignatureRuleTest.kt

The FunctionSignature rule would assume multiline mode when exceeding the maxLineLength, but this isn't always the case.
Given a long function name (as found in test cases for example) with an expression body and no parameters:
```kotlin
fun `a very long function name as found in a test case`() =
"some-result"
```
The function name here exceeds the maxLineLength of the FunctionSignatureRule but not the overal MaxLineLength.
The ktlint error would suggest to put the expression body on the same line:
`First line of body expression fits on same line as function signature [FunctionSignature]`
Which obviously won't fit. The code would calculate the remaining space based on multiline mode (assuming the line length is just `) =`). This fix checks if there are parameters on the function and if …

Add check for presence of parameters before assuming multilinemode

---

CHANGELOG.md
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/VisitorProvider.kt
ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/VisitorProviderTest.kt

Solving issue: https://github.com/pinterest/ktlint/issues/1771#issue-1528688024
Not sure about how to organise the tests file. It was covered by existing tests but I also added a new test.

Ensure that enabling the ktlint_disabled_rules property doesn't accidentally enable all experimental rules

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/WrappingRuleTest.kt

Detect new lines inside string template before wrapping
Closes #1776

Detect new lines inside string template before wrapping

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/internal/importordering/ImportLayoutParser.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportLayoutParserTest.kt

This MR fixes a typo in `parseImportsLayout(String)` that causes the `.editorconfig` property `ij_kotlin_imports_layout` to be parsed incorrectly when it contains spaces after commas (e.g. `*, ^`). This issue is particularly annoying given IntelliJ adds spaces by default when its "Reformat Code" action is used.

Fix bug in parseImportsLayout: trim spaces in entries

---

CHANGELOG.md
ktlint-api-consumer/build.gradle.kts
ktlint-api-consumer/src/test/kotlin/com/pinterest/ktlint/api/consumer/KtLintRuleEngineTest.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/editorconfig/RuleExecutionEditorConfigProperty.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleExecutionContext.kt

Starting with Ktlint `0.48.x`, rule and rule sets can be enabled/disabled with a separate property per rule (set). Please read [deprecation of (ktlint_)disable_rules property](https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this) for more information.
API Consumers that provide experimental rules to the KtLintRuleEngine, must also enable the experimental rules or instruct their users to do so in the `.editorconfig` file. From the perspective of the API Consumer it might be confusing or unnecessary to do so as the experimental rule was already provided explicitly.
Ktlint wants to provide the user (e.g. a developer) a uniform and consistent user experience. The `.editorconfig` becomes more and more central to store …

Clarify why API Consumers have to enable experimental rules

---

CHANGELOG.md
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ClassNamingRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionNamingRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/PropertyNamingRule.kt
ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/internal/RegExIgnoringDiacriticsAndStrokesOnLetters.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ClassNamingRuleTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionNamingRuleTest.kt
ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/PropertyNamingRuleTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/PackageNameRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/PackageNameRuleTest.kt

Allow diacritics in names of classes, functions packages, and properties
Closes #1757

Allow diacritics in names of classes, functions packages, and properties

---

.github/workflows/gradle-pr-build.yml

non-snapshot builds sign the release, so we need to pass the proper signing key env variables.

Fix PR builds when version is non-SNAPSHOT

---

docs/install/cli.md

Using `!` with double quotes in bash causes an expansion.

Use single quotes for CLI glob bash sample

---

CHANGELOG.md
RELEASING.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Do not report an "unnecessary semicolon" after adding a trailing comma to an enum class containing a code element after the last enum entry `trailing-comma-on-declaration-site` 
Closes #1786 

Prevent false-positive "unnecessary semicolon" after adding trailing comma in enum

---

docs/rules/standard.md

[From Kotlin Slack](https://kotlinlang.slack.com/archives/CKS3XG0LS/p1674804306134669)
If wrapping rule is disabled then trailing comma on call site & trailing comma on declaration site is disabled, because w/o wrapping trailing commas can produce weird formattings. (see 10cb29caf2c36bf5a8aac8d3cce38314c6671f71)
But there are no descriptions in rule documents about existence of this dependency and why exists. It may confuse users, so I added it.

Add documents about trailing comma is disabled when wrapping is enabled

---

CHANGELOG.md

Some GitHub issue links are broken so the not found page shows up when anyone clicks it.

fix: broken github issue link in CHANGELOG.md

---

docs/rules/configuration-ktlint.md

Fix documentation - trailing comma's are enabled by default except for android codestyle
fixes https://github.com/pinterest/ktlint/issues/1810#issuecomment-1419866153

Fix documentation trailing comma's

---

docs/faq.md
docs/rules/configuration-ktlint.md

This PR fixes EditorConfig property names for custom rule set in docs as they seem to be wrong considering their description.

Fix EditorConfig property names for custom rule set in docs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/new_rule_proposal.md
.github/PULL_REQUEST_TEMPLATE.md

This PR fixes typos in GitHub templates.

Fix typos in GitHub templates

---

build-logic/src/main/kotlin/ktlint-publication.gradle.kts

This PR makes it possible to disable code signing for release builds. This is primarily useful for package maintainers building the project from source. In this scenario, ktlint's own signing is not necessary, since the resulting package will be signed anyway. The property `ktlint.disable-signing` (name open for discussion) is introduced, which when set during release builds, skips the signing.
Fixes #1817

Allow disabling signing

---

CHANGELOG.md
docs/rules/configuration-ktlint.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigProperty.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/IndentSizeEditorConfigPropertyTest.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigPropertyTest.kt

When generating the `.editorconfig` the default value of property `max_line_length` is set to `-1` for code style `official`. This value is not recognized by IntelliJ IDEA and has negative effect on code formatting in IntelliJ. The value `off` has to be generated instead to disable the maximum line length check.
Closes #1824 

Map property max_line_length to "off" instead of "-1"

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

Do not throw exception when enum class does not contain entries `trailing-comma-on-declaration-site`
Closes #1711

Exception in trailing-comma-on-declaration-site on empty enum class

---

CHANGELOG.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigProperty.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigPropertyTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FinalNewlineRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt

The value '-1' is not a value which is accepted by the property type which only accepts positive integer value or the special value 'off' to denote that no maximum line length is applicable. Also, using value 'Int.MAX_VALUE' results in more readable code.

Change 'max_line_length' value '-1' to 'Int.MAX_VALUE'

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionReturnTypeSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionReturnTypeSpacingRuleTest.kt

Replacing a whitespace containing a newline after the return type may not result in a max-line-length violation
In case the whitespace contains a newline than replacing it with a single space results in merging the lines to a single line. This rule allows this only when the merged lines entirely fit on a single line.
Suppose that code below does not fit on a single line than this rule no longer emits a violation:
fun foo():
String = "some-looooooooooooooooong-string"
See FunctionSignatureRule for reformatting the function like below:
fun foo(): String =
"some-looooooooooooooooong-string"
Closes #1764

experimental:function-return-type-spacing should not violate max-line rule

---

CHANGELOG.md
docs/rules/standard.md
ktlint-cli-reporter-format/src/test/kotlin/com/pinterest/ktlint/cli/reporter/format/FormatReporterTest.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRuleTest.kt

Add new rules for wrapping of properties and value parameters in case the maximum line length is exceeded.
Use a continuation indent inside a value parameter in case code style `ktlint_official` is used
Closes #1775

Wrapping value parameter and property

---

CHANGELOG.md
docs/rules/experimental.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TryCatchFinallySpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TryCatchFinallySpacingRuleTest.kt

Add new experimental rule `try-catch-finally-spacing` for `ktlint_official` code style. Partly it overlaps with existing rule `keyword-spacing`. Next to this, it reformats single line `try { ... } catch (...) { .. } finally { ... }` to multiline statements.

Try catch finally rule

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Fix indentation of try-catch-finally when catch or finally starts on a newline
Fix indentation of a multiline typealias
Closes #1788 

Indent fixes

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenDeclarationsWithAnnotationsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenDeclarationsWithAnnotationsRuleTest.kt

Fix false positive when multiple KDOCs exists between a declaration and another annotated declaration
Closes #1802

Fix false positive when multiple KDOCs exists between declarations

---

.editorconfig
CHANGELOG.md
docs/rules/standard.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoWildcardImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoWildcardImportsRuleTest.kt

For the new code style `ktlint_official`, do not allow wildcard imports `java.util` and `kotlinx.android.synthetic` by default.
When generating the `.editorconfig` file generate value `unset` for property `ij_kotlin_packages_to_use_import_on_demand` in case the list of on demand imports is empty.
Also, set `ij_kotlin_packages_to_use_import_on_demand` to `unset` in the KtLint project `.editorconfig` itself to comply with this new default and resolve lint violation.
Closes #1797

Do not allow any wildcard import in code style `ktlint_official`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt

Fix false positive when a single line statement containing a block having exactly the maximum line length is preceded by a blank line
Closes #1808 

Wrapping false positive for line with max line length

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Fix false positive when a single line contains multiple dot qualified expressions and/or safe expressions
Closes #1830

Fix false positive when a single line contains multiple dot qualified expressions and/or safe expressions

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ImportOrderingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/importordering/ImportOrderingRuleCustomTest.kt

Fix false positive when `.editorconfig` property `ij_kotlin_imports_layout` contains a `|` but no import exists that match any pattern before the first `|`
Closes #1845

Fix false positive in import ordering

---

CHANGELOG.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ElementType.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundRangeOperatorRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundRangeOperatorRuleTest.kt

Enforce spacing around rangeUntil operator `..<` similar to the range operator `..` in `range-spacing`
Closes #1858

Enforce spacing around rangeUntil operator `..<`

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt

Add the default include patterns when only negate patterns are specified in Ktlint CLI
Closes #1847

Add default include patterns when only negate patterns are given

---

CHANGELOG.md
docs/rules/experimental.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/api/Baseline.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/ReporterAggregator.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/Rule.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/RuleSetProviderV2.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/IndentConfig.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/Rule.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/RuleProvider.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/EditorConfigProperty.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeReferenceSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoBlankLineInList.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCommaRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenFunctionNameAndOpeningParenthesisRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoBlankLineInListRuleTest.kt

Add new experimental rule `no-blank-line-in-list` for `ktlint_official` code style
This rule disallows blank lines to be used in super type lists, type argument lists, type constraint lists, type parameter lists, value argument lists, and value parameter lists.
Closes #1224
Closes #1781

Add rule no-blank-line-in-list

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt

Do not remove newlines from multiline type parameter lists and wrap each type parameter in a multiline type parameter list.
Closes #1867

Type parameter list spacing and wrapping

---

CHANGELOG.md
docs/rules/experimental.md
ktlint-cli/build.gradle.kts
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/EditorConfigTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoader.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoaderTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Add new experimental rule `string-template-indent` for `ktlint_official` code style
This rule forces multiline string templates which are post-fixed with `.trimIndent()` to be formatted consistently. The opening and closing `"""` are placed on separate lines and the indentation of the content of the template is aligned with the `"""`.
Closes #925

Add new experimental rule `string-template-indent`

---

ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoaderTest.kt

Verifies that `.editorconfig` properties are loaded via the EditorConfigDefaults.load(...) when a `Code.fromSnippet(...)` is being passed to the `ktlintRuleEngine`.

Unit test for loading properties from editorConfigProperties for snippet

---

.github/workflows/gradle-pr-build.yml
build.gradle.kts

Gradle Daemon was disabled for PR Build jobs in #1584 as some there were flaky tests on Windows, re-enable it for now.

Try to enable Gradle Daemon again

---

CHANGELOG.md
docs/faq.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoader.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/FormatterTags.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoaderTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt

Respect formatter tags when enabled
Closes #670
Closes #1163

Respect formatter tags when enabled

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts
build-logic/src/main/kotlin/ktlint-publication.gradle.kts
ktlint-cli/build.gradle.kts

The `gradleProperty` method was introduced in Gradle 6.2 and improves compatibility with Gradle's configuration cache.
https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html

Use modern API to get Gradle property values

---

build-logic/src/main/kotlin/ktlint-publication.gradle.kts

Follow up #1898, I mis-converted `System.getEnv` to `providers.systemProperty`.

Fix publishcation env variables

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

Remove trailing comma if last two enum entries are on the same line and trailing commas are not allowed
Closes #1905

Remove trailing comma if last two enum entries are on the same line

---

CHANGELOG.md
docs/rules/experimental.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleProviderSorter.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumWrappingRuleTest.kt

Add new experimental rule `enum-wrapping` for all code styles. An enum should either be a single line, or each enum entry should be defined on a separate line
Closes #1903
Fix bug in RuleProviderSorter. A rule marked with RunAsLateAsPossible should never be run before a rule not having any Rule.VisitorModifier.

Add new experimental rule `enum-wrapping`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

Wrap annotated function parameters to a separate line in code style `ktlint_official` only
Closes #1908
Wrap annotated projection types in type argument lists to a separate line `annotation`
Closes #1909

Wrap annotated function parameters and type projections

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

Add newline after adding trailing comma in parameter list of a function literal
Closes #1911

Add newline after adding trailing comma in parameter list of a function literal

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/api/Baseline.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRuleTest.kt
ktlint-ruleset-test-tooling/src/main/kotlin/com/pinterest/ruleset/testtooling/DumpASTRule.kt

Wrap annotations before class constructor in code style `ktlint_official`
Closes #1916
Annotations on type projections should be wrapped in same way as other annotations
Close #1917
Fix annotated expression inside function literal
Fix closing angle bracket on type argument list
Fix warning about count of records in baseline.xml which are not prefixed with rule set id

1916 wrap annotations before constructor

---

CHANGELOG.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt

Pass filepath to PsiFileFactory so that it can be retrieved inside a rule
Closes #1921

Pass filepath to PsiFileFactory so that it can be retrieved inside a rule

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRuleTest.kt

An if-else followed by an elvis operator should not be wrapped in an else-block
Closes #1904

An if-else followed by an elvis operator should not be wrapped in an else-block

---

docs/install/integrations.md

Follow up #1884, missed updating Gradle task names in that PR.

Fix typos in Gradle integration doc

---

build-logic/src/main/kotlin/ktlint-publication.gradle.kts
ktlint-cli/gradle.properties

Follow up #1898, we preferred root Gradle properties over current project's in that PR, the current group of `ktlint-cli` should be `com.pinterest` instead of `com.pinterest.ktlint`, we can remove this workaround whenever releasing version 1.0, to unify all group to `com.pinterest`.

Correct the group of ktlint-cli

---

ktlint-cli/build.gradle.kts

Fix order of build tasks for publication to maven central

Fix order of build tasks for publication to maven central

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlockCommentInitialStarAlignmentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlockCommentInitialStarAlignmentRuleTest.kt

Fix a typo in BlockCommentInitialStarAlignmentRule message output.

Fix typo in BlockCommentInitialStarAlignmentRule message output

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/api/Baseline.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/api/BaselineCLITest.kt
ktlint-cli/src/test/resources/cli/baseline/some/path/to/TestBaselineExtraErrorFile2.kt.test
ktlint-cli/src/test/resources/cli/baseline/some/path/to/TestBaselineFile2.kt.test
ktlint-cli/src/test/resources/cli/baseline/test-baseline.xml

Store path of file containing a lint violation relative to the path of the baseline file itself
Closes #1962 

Store relative path in baseline file

---

gradle.properties

The configuration cache is not yet supported by all tasks used in the build pipelines. For all github workflows the configuration-cache was already disabled. But also on the local machine, this now causes a simple task like `gradlew test` to fail as the `shadowJar` task is invoked which fails with error:
```
- Task `:ktlint-cli:shadowJarExecutable` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
```

Disable the gradle configuration cache

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/api/Baseline.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/api/BaselineCLITest.kt
ktlint-cli/src/test/resources/cli/baseline/config/test-baseline.xml

It is the responsibility of the Ktlint CLI to consistently store, retrieve and handle the path of the file in which the error is found.
Closes #1962 

Return the unmodified filename from the baseline

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt

Handle parameter `--code-style=android_studio` in Ktlint CLI identical to deprecated parameter `--android`
Closes #1982

Handle parameter `--code-style=android_studio` in Ktlint CLI

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/api/BaselineCLITest.kt

Print absolute path of file in lint violations when flag "--relative" is not specified in Ktlint CLI
Closes #1983 

Print absolute path of file in lint violations

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Prevent nullpointer exception (NPE) if or operator at start of line is followed by dot qualified expression
Closes #1993

Fix NPE if or operator at start of line followed by dot qualified expression

---

CHANGELOG.md
docs/rules/configuration-ktlint.md
ktlint-api-consumer/src/test/kotlin/com/pinterest/ktlint/api/consumer/KtLintRuleEngineTest.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/ec4j/EditorConfigProperty.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/EditorConfigTest.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/IndentSizeEditorConfigPropertyTest.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigPropertyTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoader.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigProperty.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Allow to 'unset' the `.editorconfig` property `ktlint_function_signature_rule_force_multiline_when_parameter_count_greater_or_equal_than` when using `ktlint_official` code style `function-signature`
Closes #1977

Disable wrapping of parameters (ktlint_official)

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Ktlint `0.48.2` and older allowed for an asymmetrical form of aligning the opening and closing quotes. E.g., if the opening quotes are after but on the same line as the assignment operator, and the closing quotes are on a next line, then the closing quotes may be aligned with the start position of the statement.
In `0.49.x` the check of the closing quotes has accidentally been changed for all code styles while it should only have veen changed for the new `ktlint_official` code style only. As the `ktlint_official` code style will allways wrap multiline expression to start on a new line (via rule `standard:multiline-expression-wrapping`) the formatting will be consistent for both functions and properties.
Closes #1971

Restrict indentation of closing quotes to `ktlint_official` code style

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

Fix indentation of multiline parameter list in function literal

---

CHANGELOG.md
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/ThreadSafeEditorConfigCacheTest.kt
ktlint-ruleset-standard/build.gradle.kts
ktlint-test/build.gradle.kts

Clean up unwanted dependencies below:
* ktlint-ruleset-standard has an unneeded implementation dependency on io.github.microutils:kotlin-logging-jvm:3.0.5 and ktlint-rule-engine has a testImplementation dependency on ktlint-ruleset-standard.
* ktlint-test has an api dependency on logback which is only needed for a unit test. The ktlint-rule-engine has a test implementation dependency on ktlint-test.
Closes #1998

Clean up logging dependencies

---

docs/rules/standard.md

It appears that the sample codes provided for the rule ID "no-empty-first-line-in-method-block" in [standard.md](https://github.com/pinterest/ktlint/blob/master/docs/rules/standard.md#no-leading-empty-lines-in-method-blocks) have been mistakenly interchanged, which could lead to confusion for viewers.

Fix interchanged sample code

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt

Fix directory traversal for patterns referring to paths outside of current working directory or any of it child directories
Closes #2002

Fix directory traversal for patterns outside workdirectory

---

CHANGELOG.md
docs/rules/experimental.md
docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSingleLineBlockCommentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSingleLineBlockCommentRuleTest.kt

Extract rule `no-single-line-block-comment` from `comment-wrapping` rule
Closes #1980

Extract rule `no-single-line-block-comment` from `comment-wrapping` rule

---

.github/workflows/release.yml
CHANGELOG.md
docs/install/cli.md
gradle/libs.versions.toml
ktlint-cli/build.gradle.kts

Follows the process laid out in the SDKMan [vendor onboarding process](https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process) and [gradle plugin](https://github.com/sdkman/sdkman-vendor-gradle-plugin) to push releases of ktlint to SDKMan.
Fixes https://github.com/pinterest/ktlint/issues/1363

Release to SDKMan when publishing a release

---

.github/workflows/build-pull-request.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/publish-release-build.yml
.github/workflows/publish-release-docs.yml
.github/workflows/publish-snapshot-build.yml
.github/workflows/publish-snapshot-docs.yml

* Align naming and formatting of Github workflows
* Restrict publish-snapshot-build workflow to builds containing code related files

Rename Github workflows and restrict publish-snapshot-build to code files

---

CHANGELOG.md

Fix reference to compare 0.49.0 with 0.49.1 release

Fix reference to compare 0.49.0 with 0.49.1 release

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Do not flag a (potential) mutable extension property in case the getter is annotated or prefixed with a modifier
Closes #2024

Naming (potential) mutable extension property

---

CHANGELOG.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/Rule.kt

Fix Java interoperability issues with `RuleId` and `RuleSetId` classes. Those classes were defined as value classes in `0.49.0` and `0.49.1`. Although the classes were marked with `@JvmInline` it seems that it is not possible to uses those classes from Java base API Consumers like Spotless. The classes have now been replaced with data classes.
Closes #2041

Fix Java interoperability issues with `RuleId` and `RuleSetId`

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Added sample code for Rule id: wrapping in the standard.md file to enhance user comprehension of the rule.

Add sample code for Rule id: wrapping

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Do not merge an annotated expression body with the function signature even if it fits on a single line
Closes #2043

Do not merge an annotated expression body with the function signature even if it fits on a single line

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Filter the `serialversionUID` from the analysis
Fixes https://github.com/pinterest/ktlint/issues/2017

Fixes/2017/ignore serial version UI d

---

.github/workflows/pull-request-with-code.yml
.github/workflows/pull-request-without-code.yml

Rename 'build-pull-request.yml'  to 'pull-request-with-code.yml' and add 'pull-request-without-code.yml' to make it possible that PR with and without code have distinct workflows. Important: they need to share the same "name".
Solution is based on https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Split workflow for pull request with(out) code

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyFileRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyFileRuleTest.kt

Add new experimental rule no-empty-file for all code style.
This rule disallow empty files.
Close 1074
NOTE: replacement for PR #1963 in which rebase potentially got wrong

Add new experimental rule no-empty-file #1963

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/KotlinPsiFileFactory.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoLineBreakBeforeAssignmentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoTrailingSpacesRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRuleTest.kt

In Kotlin 1.9 the extension points of the embedded kotlin compiler will change. Ktlint only uses the `org.jetbrains.kotlin.com.intellij.treeCopyHandler` extension point. This extension is not yet supported in 1.9, neither is it documented ([#KT-58704](https://youtrack.jetbrains.com/issue/KT-58704/Support-and-document-extension-point-org.jetbrains.kotlin.com.intellij.treeCopyHandler)). Without this extension point it might happen that your custom rules will throw exceptions during runtime. See [#1981](https://github.com/pinterest/ktlint/issues/1981).
In Ktlint, 7 out of 77 rules needed small and sometimes bigger changes to become independent of the extension point `org.jetbrains.kotlin.com.intellij.treeCopyHandler`. The impact on your custom rules may vary dependent on the way the …

Disable extension point org.jetbrains.kotlin.com.intellij.treeCopyHandler

---

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/IndentConfig.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrapping.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyFirstLineInClassBodyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TryCatchFinallySpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

* Extract method noNewLineInOpenRange as counter partner for noNewLineInClosedRange
* Add methods `childIndentOf`, `siblingIndentOf` and `parentIndentOf` to `IndentConfig` to improve readability

AstNodeExtensions && EditorConfig

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Add experimental rule `binary-expression-wrapping`. This rule wraps a binary expression in case the max line length is exceeded.
Closes #1940

Add experimental rule `binary-expression-wrapping`

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-cli-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/cli/reporter/baseline/BaselineReporterProvider.kt
ktlint-cli-reporter-checkstyle/src/main/kotlin/com/pinterest/ktlint/cli/reporter/checkstyle/CheckStyleReporterProvider.kt
ktlint-cli-reporter-core/src/main/kotlin/com/pinterest/ktlint/cli/reporter/core/api/ReporterProviderV2.kt
ktlint-cli-reporter-html/src/main/kotlin/com/pinterest/ktlint/cli/reporter/html/HtmlReporterProvider.kt
ktlint-cli-reporter-json/src/main/kotlin/com/pinterest/ktlint/cli/reporter/json/JsonReporterProvider.kt
ktlint-cli-reporter-sarif/src/main/kotlin/com/pinterest/ktlint/cli/reporter/sarif/SarifReporter.kt
ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ReporterProvider.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/KotlinPsiFileFactory.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/PositionInTextLocator.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RunAfterRuleFilter.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleProviderSorterTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/ThreadSafeEditorConfigCacheTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt

Add new experimental rule `blank-line-before-declaration`. This rule requires a blank line before class, function or property declarations
Closes #1939

Add new experimental rule `blank-line-before-declaration`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

Prevent incorrect reporting of violations in case a nullable function type reference exceeds the maximum line length `parameter-list-wrapping`
Closes #1324

Function type in nullable type exceeding max line length

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRuleTest.kt

Only ignore the chain or binary call when the parent of that call is `if`(when present inside `else if`). This solves the false -ve on those cases
This fixes https://github.com/pinterest/ktlint/issues/2057

Fix false -ve on else with single line binary or chained call

---

documentation/release-latest/docs/rules/experimental.md
documentation/snapshot/docs/rules/experimental.md

Clarify property naming documentation, add examples of backing properties
Closes #2078

Clarify property naming documentation, add examples of backing properties

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Changed the rule description of Rule id: enum-entry-name-case. 
The rule allows to have upper camel-case separated enum names, but not mentioned in the documentation. Hence, added that for clear understanding for the users.

Change rule description

---

CHANGELOG.md
RELEASE_TESTING.MD
documentation/snapshot/docs/rules/experimental.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/Code.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-ruleset-standard/build.gradle.kts
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt

Run format up to 3 times in case formatting introduces changes which also can be autocorrected
Closes #2084
The change above, resulted in the discovery of some problems wich are resolved as well:
* Do not require a blank line between the class/method signature and a nested declaration in rule blank-line-before-declaration.
* Allow branches with empty blocks in if-else.
* Emit violation which can not be autocorrected in case wrapping the operator reference in a binary expression would still violate the max-line-length.
* Only emit violation in if-else-wrapping rule in case a newline is missing. An incorrect indent should not lead to a violation about a missing newline.
* Swap the order in which the binary-expression-wrapping and argument-list-wrapping rules run. Binary expressions …

Repeat format run multiple times + fix for integration test bugs

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt

Inform user about using `--format` option of KtLint CLI when finding a violation that can be autocorrected
Closes #1071

Inform user about using `--format` option of KtLint CLI

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRuleTest.kt

Fix indent when property value is wrapped
Closes #2095

Fix indent when property value is wrapped

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Do not indent class body for classes having a long super type list in code style `ktlint_official` as it is inconsistent compared to other class bodies `indent`
Closes #2115

Do not indent class body for classes having a long super type list

---

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rules/InternalRule.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleProviderSorterTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/InternalRuleProvidersFilterTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RunAfterRuleFilterTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Follow-up on #2115. Fix indent of explicit constructor.

Fix indent of explicit constructor

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRuleTest.kt

Fix spacing around colon in annotations
Closes #2093

Fix spacing around colon in annotations

---

CHANGELOG.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Display log message `Format was not able to resolve all violations which (theoretically) can be autocorrected in file ... in 3 consecutive runs of format` only when after the third consecutive run still a violation exists that can be autocorrected.
Closes #2129
x wrapping of function signature in case the opening brace of the function body block exceeds the maximum line length. Fix upsert of whitespace into composite nodes.
Closes #2130

Fix solving problems in 3 consecutive runs

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingTest.kt

Fix indent of IS_EXPRESSION, PREFIX_EXPRESSION and POSTFIX_EXPRESSION in case it contains a linebreak
Closes #2094

Fix indent of IS_EXPRESSION, PREFIX_EXPRESSION and POSTFIX_EXPRESSION

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Do not wrap a binary expression after an elvis operator in case the max line length is exceeded
Use sets internally in KtlintAssertThat rather than lists for storage and comparing of LintViolations. Like the KtlintRuleEngine duplicate violations are to be ignored.
Closes #2128

Do not wrap a binary expression after an elvis operator

---

CHANGELOG.md
build.gradle.kts
gradle/libs.versions.toml
ktlint-bom/build.gradle.kts
ktlint-cli-reporter-baseline/api/ktlint-cli-reporter-baseline.api
ktlint-cli-reporter-checkstyle/api/ktlint-cli-reporter-checkstyle.api
ktlint-cli-reporter-core/api/ktlint-cli-reporter-core.api
ktlint-cli-reporter-format/api/ktlint-cli-reporter-format.api
ktlint-cli-reporter-html/api/ktlint-cli-reporter-html.api
ktlint-cli-reporter-json/api/ktlint-cli-reporter-json.api
ktlint-cli-reporter-plain-summary/api/ktlint-cli-reporter-plain-summary.api
ktlint-cli-reporter-plain/api/ktlint-cli-reporter-plain.api
ktlint-cli-reporter-sarif/api/ktlint-cli-reporter-sarif.api
ktlint-cli-ruleset-core/api/ktlint-cli-ruleset-core.api
ktlint-cli/api/ktlint-cli.api
ktlint-logger/api/ktlint-logger.api
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-test/api/ktlint-test.api

Closes #2111
I wasn't sure if I should add a Changelog entry, since this does not affect consumers at all 👀 
Binary compatibility validator will compare the commited public API surface with _current_ one. Task `apiCheck` will run on every `check` invocation. 
If the public API changes, the `apiCheck` task will fail and will require dumping a new one with `./gradlew apiDump`. 
I'm proposing to verify binary compatibility of every project that is published (and can be consumed by third party clients)

Add binary compatibility validator

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteral.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

This rule enforces the parameter list of a function literal to be formatted consistently
Closes #2121

Add new experimental rule `function-literal`

---

CHANGELOG.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/CodeStyleEditorConfigProperty.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/EditorConfigTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/EditorConfigLoaderTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoWildcardImportsRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRuleTest.kt

Change default code style to `ktlint_official`
Closes #2143

Change default code style to `ktlint_official`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRuleTest.kt

Fix null pointer exception for if-else statement with empty THEN block
Closes #2135

Fix null pointer exception for if-else statement with empty THEN block

---

CHANGELOG.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteral.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnCallSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/internal/importordering/PatternEntry.kt

Code clean-up as suggested by code inspections

Code clean-up as suggested by code inspections

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-cli-reporter-format/src/main/kotlin/com/pinterest/ktlint/cli/reporter/format/FormatReporterProvider.kt
ktlint-cli-reporter-plain/src/main/kotlin/com/pinterest/ktlint/cli/reporter/plain/PlainReporterProvider.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/RuleProvider.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/EditorConfig.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RunAfterRuleFilter.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rules/KtlintSuppressionRule.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleProviderSorterTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/InternalRuleProvidersFilterTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RunAfterRuleFilterTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBody.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ImportOrderingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/internal/importordering/PatternEntry.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRuleTest.kt
ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt

Add experimental rule `function-expression-body`. This rule rewrites function bodies only contain a `return` or `throw` expression to an expression body.
Closes #2150 

Add function expression body rule

---

documentation/release-latest/docs/api/custom-integration.md
documentation/release-latest/docs/faq.md
documentation/release-latest/docs/rules/code-styles.md
documentation/release-latest/docs/rules/configuration-ktlint.md
documentation/snapshot/docs/api/custom-integration.md
documentation/snapshot/docs/rules/code-styles.md
documentation/snapshot/docs/rules/configuration-ktlint.md

As documentation is now version specific, some reference to version `0.49` are no longer needed.
Closes #2154

Remove references to `0.49` when applicable

---

.editorconfig
.github/actions/setup-gradle-build/action.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/publish-release-build.yml
.github/workflows/publish-snapshot-build.yml
.github/workflows/pull-request-with-code.yml
.github/workflows/pull-request-without-code.yml
CHANGELOG.md
README.md
build-logic/build.gradle.kts
build-logic/settings.gradle.kts
build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts
build-logic/src/main/kotlin/ktlint-publication.gradle.kts
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

Closes #1888
I wanted to open the project, but it failed to sync for me locally (because my defaults point to Java 20), so I decided to make the build more deterministic. I'll comment out all changes in the PR since some of them require your input, but the tl;dr is:
- The project will be built only with a single Java version (that's what the release workflow does)
- Only tests will be invoked on various Java versions (that's what project consumers do)
- The project will compile on Java 20, and if someone doesn't have Java 11 or 20 installed locally, Gradle will fetch missing ones
- I also removed a few of annoying compiler and deprecation warnings  …

Setup toolchains, compile project with Java 20 only, run test on various Java versions

---

documentation/release-latest/docs/install/overview.md
documentation/release-latest/mkdocs.yml
documentation/snapshot/docs/install/overview.md
documentation/snapshot/mkdocs.yml

The online version to compare ktlint and diktat is no longer available. The project (https://github.com/saveourtool/diktat-demo) has been archived since June 8th, 2023.
Closes #2169

Remove install overview page

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Fix alignment of type constraints after `where` keyword in function signature
Closes #2175

Fix alignment of type constraints after `where` keyword in function

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRuleTest.kt

Fix wrapping of multiline postfix expression
Closes #2183

Fix wrapping of multiline postfix expression

---

ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/KtlintApiConsumer.kt
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/GitHookInstaller.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/CommandLineTestRunner.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/SafeEnumValueParser.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

Fix compiler warnings except warning below which will be resolved when migrating to Kotlin 1.9:
```
KotlinPsiFileFactory.kt:137:41 'getRootArea(): ExtensionsArea!' is deprecated. Deprecated in Java
```

Fix compiler warnings

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRuleTest.kt

Do not wrap expression after a spread operator
Closes #2188

Do not wrap expression after a spread operator

---

CHANGELOG.md
build-logic/src/main/kotlin/ktlint-publication.gradle.kts
documentation/snapshot/docs/faq.md
documentation/snapshot/overrides/main.html
gradle.properties
ktlint-cli-reporter-baseline/gradle.properties
ktlint-cli-reporter-checkstyle/gradle.properties
ktlint-cli-reporter-core/gradle.properties
ktlint-cli-reporter-format/gradle.properties
ktlint-cli-reporter-html/gradle.properties
ktlint-cli-reporter-json/gradle.properties
ktlint-cli-reporter-plain-summary/gradle.properties
ktlint-cli-reporter-plain/gradle.properties
ktlint-cli-reporter-sarif/gradle.properties
ktlint-cli/gradle.properties

Update and align Maven coordinates

---

.github/workflows/generate-changelog.yml
CHANGELOG.md

Generate changelog based for unreleased PR's, e.g. PR's between current version (latest release) and HEAD commit.
For now, the changelog should not be added automatically to the release. First, we need to experiment with the process of labeling PR's correctly.

Generate changelog for unreleased PR's

---

CHANGELOG.md
ktlint-api-consumer/build.gradle.kts
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/KtlintApiConsumer.kt
ktlint-api-consumer/src/main/kotlin/com/example/ktlint/api/consumer/rules/CustomRuleSetProvider.kt
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/Rule.kt
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/internal/IdNamingPolicy.kt
ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/EditorConfigOverride.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/EditorConfigPropertyRegistry.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/EditorConfigPropertyRegistryTest.kt

Extend API Consumer example to showcase how EditorConfigOverride can be defined with dynamically loaded rulesets
Closes #2190

Define EditorConfigOverride for dynamically loaded ruleset

---

CHANGELOG.md
documentation/snapshot/docs/rules/experimental.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeModifierSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeModifierSpacingRuleTest.kt

Add `function-type-modifier-spacing` rule
Closes #2202

Add `function-type-modifier-spacing` rule

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt

Given a class with an explicit constructor not having arguments:
```
class Foo constructor() {
fun bar()
}
```
should not result in removal of the parenthesis after `constructor` as it results in a compilation error.

Do not remove parenthesis after explicit class constructor without arguments

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRuleTest.kt

Fix conflict between indentation rule and modifier list spacing rule resulting in cyclic changing of indentation of super type call entry which is annotated:
```
class Foo(
bar: Bar,
) : @Unused
FooBar()
```

Fix conflict between rules due to annotated super type call

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Given a class with a super type preceded by a comment should not result in a violation
```
class Foo(
bar: Bar,
) : // Some comment
@Unused
FooBar(),
FooBar2
```

Fix indentation of super type list of class in case it is preceded by  a comment

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt

A super type list starting with an annotation having a parameters can be on the same line as the closing parenthesis of the enclosing class:
```
class Foo(
bar: Bar,
) : @Suppress("DEPRECATION")
FooBar()
```

Super type list starting with an annotation having a parameters

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StatementWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StatementWrappingRuleTest.kt

Code below should not result in wrapping the enum values `FOO` and `BAR` on separate lines:
```
/**
* Some comment
*/
enum class Foobar { FOO, BAR }
```

Do not wrap values in a single line enum when it is preceded by a comment or an annotation

---

.github/workflows/publish-release-build.yml

Brew formula has been relocated (https://github.com/Homebrew/homebrew-core/pull/139592). The default formula path as resolved by GitHub action is no longer valid and needs to be overridden (https://github.com/mislav/bump-homebrew-formula-action/issues/58).

Add brew formula path

---

.github/workflows/publish-release-build.yml

SDKMan credentials have been updating, so re-enabling for releases

Re-enable releasing to SDKMan

---

.github/workflows/publish-release-build.yml
CHANGELOG.md
RELEASING.md

Release notes for release 1.0.0 were not correct as the changelog heading "## [Unreleased]" was changed to "## Unreleased"
- Fix releasing notes
- Fix changelog.md for next release
- Add check in publish release workflow
Closes #2240

Publish correct release notes

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

Ignore anonymous function in rule `function-naming`
Do not force blank line before function in right hand side of assignment `blank-line-before-declaration`
Closes #2260 

Anonymous function in assignment

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRuleTest.kt

Do not replace function body having a return statement only in case the return statement contains an intermediate exit point
Closes #2269

Do not replace function body with multiple exit points

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

A function override should not be reported as the interface of class that defines the function might be out of scope of the project in which case the function name can not be changed. Note that the function will still be reported at the interface or class itself whenever that interface or class is defined inside the scope of the project.
Closes #2271

Ignore override of function in rule `function-naming`

---

CHANGELOG.md
documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/CommaSeparatedListValueParser.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/CommaSeparatedListValueParserTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

Add `.editorconfig` property `ktlint_function_naming_ignore_when_annotated_with`.
When using Compose, set property `ktlint_function_naming_ignore_when_annotated_with=Composable` to suppress the `function-naming` rule for functions annotated with `@Composable`. A dedicated ktlint ruleset like [Compose Rules](https://mrmans0n.github.io/compose-rules/ktlint/) can be used for checking naming conventions for such Composable functions.
Closes #2259

Suppress `function-naming` based on annotations

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

Follow-up on #2259. Allow to ignore `function-name` rule when annotation is part of array:
```
@[Composable Foo]
fun SomeComposableFoo()
```

Support annotation array when ignoring function-naming rule

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt

Force blank line before object declaration if preceded by another declaration
Closes #2284

Force blank line before object declaration

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRuleTest.kt

Prevent wrapping of nested multiline binary expression before operation reference as it results in a compilation error
Closes #2286
- [ X] PR description added

2286 mulitline expression wrapping

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

Ignore function naming in Kotest classes
Closes #2289

Ignore function naming in Kotest classes

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/DiscouragedCommentLocationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/DiscouragedCommentLocationRuleTest.kt

Improve violation message in `discouraged-comment-location`
Closes #2292
- [ X] KtLint format has been applied on source code itself and violations are fixed

Improve violation message in `discouraged-comment-location`

---

documentation/release-latest/docs/rules/experimental.md
documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/experimental.md
documentation/snapshot/docs/rules/standard.md

Fix names of `.editorconfig` properties that affect wrapping class and function signatures
Closes #2296

Fix names of `.editorconfig` properties in documentation

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRuleTest.kt

Fix malformed AST when `&&` or `||` is at start of line `chain-wrapping`
Closes #2297

Fix malformed AST when `&&` or `||` is at start of line `chain-wrapping`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRuleTest.kt

Do not report false positives `type-argument-list-spacing` and `type-parameter-list-spacing`
Closes #2299

Do not report false positives `type-argument-list-spacing` and `type-parameter-list-spacing`

---

CHANGELOG.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt

Fix chain method continuation for dot qualifying expression containing a call expression returning a (higher order) function `chain-method-continuation`
Closes #2304

Fix chain method continuation containining higer order function call

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRuleTest.kt

Allow spread operator starting on new line (fixes regression of #2300)

Allow spread operator starting on new line (fixes regression of #2300)

---

.github/workflows/generate-changelog.yml
CHANGELOG.md
RELEASE_TESTING.MD
gradle.properties

Prepare release 1.0.1
* Update release testing how-to
* Fix format of generated changelog
* Update changelog with generated changelog

Prepare release 1.0.1

---

.github/workflows/publish-release-build.yml
.github/workflows/publish-relocations.yml
.github/workflows/publish-snapshot-build.yml
build-logic/src/main/kotlin/ktlint-publication.gradle.kts
ktlint-cli-reporter-baseline/build.gradle.kts
ktlint-cli-reporter-checkstyle/build.gradle.kts
ktlint-cli-reporter-core/build.gradle.kts
ktlint-cli-reporter-html/build.gradle.kts
ktlint-cli-reporter-json/build.gradle.kts
ktlint-cli-reporter-plain-summary/build.gradle.kts
ktlint-cli-reporter-plain/build.gradle.kts
ktlint-cli-reporter-sarif/build.gradle.kts
ktlint-cli/build.gradle.kts

Revert publish workflow to "Maven" Publication only. Use a separate GitHub workflow to publish the relocated artifacts

GitHub workflow to publish the relocated artifacts

---

.github/actions/setup-gradle-build/action.yml
.github/workflows/generate-changelog.yml
CHANGELOG.md
gradle/libs.versions.toml

Compile with java 21 instead of 20
Closes #2319 

Compile with java 21 instead of 20

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundAngleBracketsRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnCallSiteRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

De-indent the closing angle bracket of the type argument list and type parameter lists in ktlint_official code style
This makes indentation of parenthesis, brackets and angle brackets consistent. E.g. in multiline format the elements of the list (excluding the closing token) are indented one indent level deep. The closing token is kept at the same indent level as the opening token.
Closes #2299

De-indent the closing angle bracket of the type argument list and type parameter lists in ktlint_official code style

---

documentation/release-latest/docs/index.md
documentation/snapshot/docs/index.md

Fix artifact url of Maven Central Badge in the [ktlint website](https://pinterest.github.io/ktlint/1.0.1/), it is showing the version of previous artifact:

docs: Fix artifact url of Maven Central Badge

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Improve checking on backing property
- Provide better message when the backing property does not have a private modifier
- Check that property correlated with the backing property is public
Closes #2345

Improve checking on backing property

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt

Add "UnusedImport" as @Suppress alias for "ktlint:standard:no-unused-import"

Add "UnusedImport" as @Suppress alias

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Allow backing property to be correlated to a public function
Closes #2332

Allow backing property to be correlated to a public function

---

ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/Code.kt

Add helper function 'fromSnippetWithPath' to create a Code instance that is to be linted/formatted.
Closes #2340

Add helper function 'fromSnippetWithPath' to create a Code instance

---

gradle/libs.versions.toml
ktlint-cli-reporter-baseline/api/ktlint-cli-reporter-baseline.api
ktlint-cli-reporter-baseline/build.gradle.kts
ktlint-cli-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/cli/reporter/baseline/Baseline.kt
ktlint-cli-reporter-baseline/src/test/kotlin/com/pinterest/ktlint/cli/reporter/baseline/BaselineTest.kt
ktlint-cli-reporter-baseline/src/test/resources/baseline-invalid.xml
ktlint-cli-reporter-baseline/src/test/resources/baseline-valid.xml
ktlint-cli-reporter-baseline/src/test/resources/simplelogger.properties
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt

Support logging and exception throwing when loading baseline
The caller should be able to determine how errors while loading the baseline are to be handled. The ktlint CLI expects errors to be printed to the log. The ktlint-intellij-plugin requires exceptions to be thrown as the log is invisible for the plugin.
Closes #2344

Support logging and exception throwing when loading baseline

---

documentation/release-latest/docs/rules/experimental.md
documentation/snapshot/docs/rules/experimental.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

Remove redundant arrow in function literal without parameters
Kotlin allows a function literal to be defined with an empty parameter list and a redundant arrow symbol to divide the parameter list from the body.
Closes #2331
Fix documentation as `function-literal` rule is experimental and not bound to `ktlint_official` code style.

Remove redundant arrow in function literal without parameters / fix documentation

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/internal/Baz.kt

Ignore imports for `rangeUntil` in `no-unused-imports` rule
Removing this import results in compilation error when shorthand `..<` is used instead of function `rangeUntil(..)`.
Closes #2373

Ignore imports for `rangeUntil` in `no-unused-imports` rule

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt

When searching files like this:
```
mkdir .hidden_folder
cd .hidden_folder
touch File.kt
ktlint '*.kt'
```
ktlint reported that it found no files.
The fact that the current directory is hidden should have no effect.

Fix searching from inside a hidden directory

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRuleTest.kt

Prevent unwanted joining of KDoc with preceding type-parameter-list
Closes #2360

Prevent unwanted joining of KDoc with preceding type-parameter-list

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRuleTest.kt

Ignore imports for `assign` in `no-unused-imports` rule
Removing this import results in compilation error when shorthand "=" is used instead of function `assign(..)`.
Closes #2343

Ignore imports for `assign` in `no-unused-imports` rule

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionNamingRuleTest.kt

Ignore invalid function names when importing from "junit.framework"
Closes #2383

Ignore invalid function names when importing from "junit.framework"

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRuleTest.kt

If a file contains multiple function bodies that have to be replaced with a body expression, then all should be replaced with a single run of ktlint.
Closes #2394

Replace all function bodies with body expressions in a single run

---

gradle/libs.versions.toml
renovate.json

Update logback to 1.3.13 and prevent renovate to upgrade to 1.4.x because java8 is to be supported.

fix(deps): update dependency ch.qos.logback:logback-classic to v1.3.13

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FinalNewlineRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FinalNewlineRuleTest.kt

Fix offset for violation (to last character in file) when final newline is missing
Closes #2391

Fix offset for violation when final newline is missing

---

ktlint-cli/src/main/scripts/ktlint.bat

Fix path to ktlint JAR file in `ktlint.bat`
Closes #2402

Fix path to ktlint JAR file in `ktlint.bat`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRuleTest.kt

Set offset of `max-line-length` violation to the last position at which a newline can be inserted to fix the violation

Set offset of `max-line-length` violation to the last position at which a newline can be inserted to fix the violation

---

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintRuleEngineSuppression.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/KtlintSuppression.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rules/KtlintSuppressionRule.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintRuleEngineSuppressionKtTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintSuppressionInserterKtTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/KtlintSuppressionKtTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rules/KtlintSuppressionRuleTest.kt

Adding a ktlint suppression in the AST is not trivial. Not all nodes in the AST can be annotated. The `insertSuppression` extension function on the `ktlintRuleEngine` can be used to add one single suppression at either the file level or at a specific offset. If the AST node at the given offset can not be annotated, then the annotation will be added to the closest parent of the node on which the annotation can be placed.
Most of the logic for the new helper method is extracted from the `KtlintSuppressionRule` which handles the legacy ktlint-directives. The logic regarding insertion/modification of the 'Suppress' annotation has been extracted to an internal class which is used by the new helper function and the `KtlintSuppressionRule`.
KtlintSuppressionRule:
* Fix offsets in some violations …

Add support for API Consumers to add suppressions

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenDeclarationsWithAnnotationsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenDeclarationsWithAnnotationsRuleTest.kt

Fix adding blank line between declaration and an annotated declaration which is preceded by comment
Closes #2416

Fix adding blank line between declaration and an annotated declaration which is preceded by comment

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRuleTest.kt

Disallow `else-if (..) <statement>` as single line construct
Closes #2420

Disallow `else-if (..) <statement>` as single line construct

---

ktlint-cli/src/main/scripts/ktlint.bat

I was trying to use `ktlint.bat` and ran into multiple problems. These few minor changes solve these.
I'll comment on each why it was changed as conversation.

Make ktlint.bat more environment agnostic

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Add cross-references between `parameter-list-wrapping` and `function-signature` rules as both deal with wrapping parameters.
Closes #2424

Add cross-references in documentation for parameter wrapping

---

documentation/release-latest/docs/install/cli.md
documentation/snapshot/docs/install/cli.md

I deleted a duplicate command in the documentation. (`ktlint generateEditorConfig`) I don't believe it was intentional.
I figured the fix was simple enough that adding an extended description to the commit message is not necessary. I can change this, though.
I added the fix to both the snapshot and release documentations. It's not necessarily pressing enough to need being updated in the release version, but I figured it couldn't do too much harm.

Improve generateEditorConfig example in docs

---

documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Suppress property-naming rule via `@Suppress("ConstPropertyName")`
Suppression via `@Suppress("PropertyName")` was already supported before.
Closes #2441 

Suppress property-naming rule via `@Suppress("ConstPropertyName")`

---

documentation/release-latest/docs/install/cli.md
documentation/snapshot/docs/install/cli.md

I found incorrect example in the documentation for the `ktlint generateEditorConfig` command.
The `code-style` parameter defaults to `ktlint_official`, but **there is no default value for the `code-style` parameter**.
```
$ ktlint --version
1.1.0
$ ktlint generateEditorConfig
Exception in thread "main" picocli.CommandLine$MissingParameterException: Missing required parameter: 'code-style'
```
https://github.com/pinterest/ktlint/blob/ebfe2d022ecf082c180e761c8f07f82caebd1561/ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/GenerateEditorConfigSubCommand.kt#L21-L28
[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release …

Fix incorrect generateEditorConfig example in documentation

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/KtlintSuppression.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintRuleEngineSuppressionKtTest.kt

Do not place an annotation on a value argument, value parameter, type parameter, or type projection in case it is a binary expression
Make creation of the annotation more safe by not using a fake top element in the code which is used to generate the AST.
The 'Suppress' annotation has a parameter, which by default is not allowed to be placed inline (it should start on a new line). Just putting it above the binary expression results in it being applied to the first subexpression only instead of on the entire binary expression.
Closes #2462
[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release …

Fix insert of suppression on binary expression

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Loosen dependencies on `value-argument-comment`, `value-parameter-comment`, `type-argument-comment`, and `type-parameter-comment` rules to be disabled
Run `argument-list-wrapping`, `class-signature` and `function-signature` when comment rules above are disabled.
Closes #2445

Run `argument-list-wrapping`, `class-signature` and `function-signature` when comment rules are disabled

---

documentation/release-latest/docs/rules/configuration-ktlint.md
documentation/snapshot/docs/rules/configuration-ktlint.md

Clarify value `default` of `ktlint_function_signature_body_expression_wrapping`
Closes #2471

Clarify value `default` of `ktlint_function_signature_body_expression_wrapping`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt

Loosen dependency between chain-method-continuation and argument-list-wrapping-wrapping
Allow the chain-method-continuation rule to be run when argument-list-wrapping is disabled or not loaded. Whenever both rules are loaded, the argument-list-wrapping takes precedence and runs before the chain-method-continuation.
Closes #2452

Loosen dependency between chain-method-continuation and argument-list-wrapping

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

Keep arrow when both parameter list and block of function literal are empty
Removal of the arrow in this case would lead to a compilation error as the function literal is changed to a normal block when removing the arrow.
Closes #2465

Keep arrow when both parameter list and block of function literal are empty

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt

The binary-expression-wrapping rule is now smarter.
It no longer has a rule dependency on the value-argument-wrapping rule. Instead, if a binary expression is used as value argument, and it causes the max line length to be exceeded, then it wraps the value argument.
```
// $MAX_LINE_LENGTH_MARKER    $EOL_CHAR
val foobar1 = Foo(1 * 2 * 3 * 4)
val foobar2 = Foo(bar(1 * 2 * 3))
val foobar3 = Foo(bar("bar" + "bazzzzzzzzzzz"))
val foobar4 = Foo(bar("bar" + "bazzzzzzzzzzzz"))
```
is formatted as
```
// $MAX_LINE_LENGTH_MARKER    $EOL_CHAR
val foobar1 = Foo(
1 * 2 * 3 * 4
)
val foobar2 = Foo(
bar(1 * 2 * 3)
)
val foobar3 = Foo(
bar(
"bar" + "bazzzzzzzzzzz"
)
)
val foobar4 = Foo(
bar(
"bar" +
"bazzzzzzzzzzzz"
)
)
```
If the left hand side of the binary expression is call expression with a lambda …

Improve wrapping of binary expressions

---

documentation/release-latest/docs/rules/configuration-ktlint.md
documentation/release-latest/docs/rules/experimental.md
documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/configuration-ktlint.md
documentation/snapshot/docs/rules/experimental.md
documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt

Move configuration setting documentation to rule
For settings which are tied to a specific rule, it is more clear to have the setting documented at the same place as the rule. Other generic settings are kept at the configuration page.

Move configuration setting documentation to rule

---

ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRuleTest.kt

Resolve conflict between parameter-list-spacing and parameter-list-wrapping
Closes #2488

Resolve conflict between parameter-list-spacing and parameter-list-wrapping

---

RELEASE_TESTING.MD
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt

Do not wrap binary expression value argument if it is already preceded by a newline
Closes #2492

Do not wrap binary expression value argument if it is already preceded by a newline

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRuleTest.kt

If an operation reference contains an identifier, then it is used in a DSL notation in which the identifier should be separated with a from a parenthesized expression to avoid confusion with a function call. E.g. format as `every { foo() } returns (bar) andThen (baz)`
Offsets for operators having length 2 or more, and not followed by single space were incorrect as length of the operator was not taken into account.
Closes #2459

Fix operator spacing

---

CHANGELOG.md
RELEASE_TESTING.MD
gradle.properties

Prepare 1.1.1 release

---

ktlint-bom/build.gradle.kts

Simplify the code below:
```kt
val internalNonPublishableProjects: Set<String> by rootProject.extra
val excludeList = internalNonPublishableProjects + "ktlint-test-ruleset-provider-v2-deprecated"
```

Simplify BOM exclude list

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt

Break dependency between string-template-indent and multiline-expression-wrapping
If need be, the string-template-indent rule wraps the opening quotes of a multiline raw string literal to a new line. The `string-template-indent` can now be enabled regardless whether `multiline-expression-wrapping` is enabled.
Closes #2504

Break dependency between string-template-indent and multiline-expression-wrapping

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRuleTest.kt

Allow string template to exceed max line length when it is the only element on a line
Closes #2453

Allow string template to exceed max line length when it is the only element on a line

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierOrderRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundKeywordRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt

Add configuration setting for ignoring `argument-list-wrapping` above treshold of parameters
Breaking change: For code style `ktlint_official` the default value for this setting has default `unset` which is different from previous default value `8`. Not wrapping parameters should be a conscious decision of the developer. This can either be done on a case by case basis by suppressing the rule, or by configuring the parameter.
Closes #2461

Add configuration setting for ignoring `argument-list-wrapping` above treshold of parameters

---

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

Ignore EOL comment that causes max_line_length to be exceeded, except in max-line-length rule
Rules should not start wrapping code in case the max_line_length is exceeded because of the EOL comment. The developer should determine whether the EOL comment should be shortened, or be placed on a separate line instead of wrapping via autocorrect.
Closes #2450

Ignore EOL comment that causes max_line_length to be exceeded, except in max-line-length rule

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Remove invalid argumentation why EOL-comments are disallowed
Closes #2513

Remove invalid argumentation why EOL-comments are disallowed

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt

Ignore function which is returned as result in a function body
Closes #2521

Ignore function which is returned as result in a function body

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumWrappingRuleTest.kt

Fix false positive newline expected before comment in enum
Closes #2510

Fix false positive newline expected before comment in enum

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt

Report violation when parameter list is preceded by a comment
Comments are not allowed between a class/function name and the parameter list.
Closes #2535

Report violation when parameter list is preceded by a comment

---

gradle/libs.versions.toml
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyFileRuleTest.kt
ktlint-test/build.gradle.kts

Dependency `org.codehaus.janino:janino` is no longer needed to build the project.

Remove dependency org.codehaus.janino:janino

---

build-logic/src/main/kotlin/ktlint-publication.gradle.kts
documentation/snapshot/docs/rules/experimental.md
documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/MaxLineLengthEditorConfigProperty.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintRuleEngine.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtLintTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRuleTest.kt

KDocs should only be used at locations for which it makes sense to provide (e.g. generate) documentation to be used by other consumers.
Closes #2547

Add new rule for disallowing KDoc at non-whitelisted locations

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintRuleEngineSuppression.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/api/KtlintRuleEngineSuppressionKtTest.kt

Improve insert of suppression:
* Prevent KtlintSuppressionOutOfBoundsException Suppression if offset equals the end the line.
* Insert suppression at parent in case the target location of the suppression is a whitespace.

Improve insert of suppression

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentCommentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterCommentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueArgumentCommentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueParameterCommentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentCommentRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterCommentRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueArgumentCommentRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueParameterCommentRuleTest.kt

Remove logic which was moved to new rule 'kdoc' in #2548.
Relates #2547

Remove logic which was moved to new rule 'kdoc'.

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueArgumentCommentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueParameterCommentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueArgumentCommentRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ValueParameterCommentRuleTest.kt

Ignore EOL comments in `value-argument-comment` and `value-parameter-comment`
EOL comments which are just before or after a value argument or value parameter do not belong to the VALUE_ARGUMENT or VALUE_PARAMETER AST node but to the out LIST element. So this rule only reports comments that are actually inside the VALUE_ARGUMENT or VALUE_PARAMETER node.
Closes #2519

Ignore EOL comments in `value-argument-comment` and `value-parameter-comment`

---

documentation/snapshot/docs/rules/experimental.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Ignore modifier of backing property in `android_studio` code style
Extract `backing-property-name` from `property-naming` rule. This allows users to disable this rule, but keep the `property-naming` rule in place.
For `android_studio` code style the restrictions regarding the modifier of the correlated property or function is ignored entirely as the Android Kotlin Styleguide does not require it to be public.
Closes #2528

Ignore modifier of backing property in `android_studio` code style

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt

Do not indent string template starting at first position of line
Also, the `indent` rule should not change unexpected indentation characters inside a string template but leave this up to the `string-template-indent` rule. As a result the `indent` rule could be a bit simplified.
Closes #2350

Do not indent string template starting at first position of line

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRuleTest.kt

Prevent conflict between `curly-spacing` and `range-spacing` when curly closing brace is followed by range (until) operator
Closes #2539 

Prevent conflict when curly closing brace is followed by range (until) operator

---

gradle/libs.versions.toml
ktlint-test/build.gradle.kts

Janino is required for logback-test.xml conditional configuration so that trace-logging in unit test can be automatically enabled using an environment variable
This (partially) reverts commit a6e6b557396ef7c4a2e884dbac828670d682cd94 (#2545)

Revert "Remove dependency org.codehaus.janino:janino (#2545)"

---

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

Exclude EOL-comments when check whether max line length is exceeded in rules other than max-line-length
Follow up on #2450 / #2516:
- fix exception in `function-literal` in case the literal block just contains an EOL-comment only
- Change function `dropTrailingComment` to private (it was not yet exposed in a released version before)

Exclude EOL-comments when check whether max line length is exceeded in rules other than max-line-length

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt

Simple reference expressions like properties and enum values should be ignored by this rule as they are no method calls.
Closes #2455

Ignore simple reference expressions in `chain-method-continuation`

---

documentation/snapshot/docs/rules/experimental.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditions.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditionsTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt

Resolved bug found during release testing:
* A when-condition preceded by a comment should be treated as a multiline condition and as of that lead to adding blank lines between the when-conditions
* Rename BackingPropertyRuleTest to BackingPropertyNamingRuleTest
* Prevent conflict between string-template-indent and `multiline-expression` when function body expression is a multiline string template

Release testing bugs 1.2.0

---

ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditions.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundSquareBracketsRule.kt

Mark new rules as experimental
Closes #2575

Mark new rules as experimental

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt

Fix null byte as default value for "--pattern-from-stdin"
Closes 2578

Fix null byte as default value for "--pattern-from-stdin"

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt

Do not wrap operation reference after multiline string 
Closes #2577 

Do not wrap operation reference after multiline string template

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Do not merge opening quotes of multiline string template with (single line) function signature
Closes #2592

Do not merge opening quotes of multiline string template with (single line) function signature

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRuleTest.kt

Ignore max line length in case the line contains only a string template followed by a comma
Closes #2597 

Ignore max line length in case the line contains only a string template followed by a comma

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt

Ignore nested reference expressions in `chain-method-continuation`
Given code:
```
fun buildBar1(): Foo.Bar = Foo.Bar.builder().baz().baz.build()
fun buildBar2(): Foo.Bar = Foo.bar.Bar.builder().baz().baz.build()
fun buildBar3(): Foo.Bar = Foo.bar.bar.Bar.builder().baz().baz.build()
fun buildBar4(): Foo.Bar = Foo.Bar.baz.builder().baz().baz.build()
fun buildBar5(): Foo.Bar = Foo.baz().bar.Bar.builder().build()
```
Is now formatted as:
```
fun buildBar1(): Foo.Bar =
Foo.Bar
.builder()
.baz()
.baz
.build()
fun buildBar2(): Foo.Bar =
Foo.bar.Bar
.builder()
.baz()
.baz
.build()
fun buildBar3(): Foo.Bar =
Foo.bar.bar.Bar
.builder()
.baz()
.baz
.build()
fun buildBar4(): Foo.Bar =
Foo.Bar.baz
.builder()
.baz()
.baz
.build()
fun buildBar5(): Foo.Bar =
Foo
.baz()
.bar.Bar
.builder()
.build()
``` …

Ignore nested reference expressions in `chain-method-continuation`

---

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MaxLineLengthRule.kt

Prevent exception in `binary-expression-wrapping` rule in case it is preceded on the same line by a block comment containing a newline character
Function `leavesOnLine` calls function `getFirstLeafOnLineOrSelf` which finds the first leaf on the line by looking for newline character. A block comment containing a newline character resulted in considering that block comment to be the first element on the line, even in case it was preceded by other elements on the same line.
Due to this change, the `max-line-length` rule failed, which has been resolved by refactoring the calculation of the line length.
Closes #2601
[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference …

Prevent exception in `binary-expression-wrapping` rule

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRuleTest.kt

Due to incorrect construction of the string template, it could happen that an import is removed as it was falsely flagged as unused as the "$" was added as prefix in the identifier.

Fix replacement of redundant curly braces

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRuleTest.kt

Adds support for detecting whitespace before a value argument list when it follows the type argument list of a constructor call.
This is needed to correctly detect and remove the excess whitespace in the following sample:
```kotlin
class MyClass : MySuper<String> ("hello")
```

Fix unwanted whitespace between super class constructor and its argument list

---

documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

When Intellij IDEA suppressions `ObjectPropertyName` or `PrivatePropertyName` are used, then also suppress ktlint `property-naming` rule.
Closes #2612

Suppress `property-name` rule for `ObjectPropertyName` or `PrivatePropertyName`

---

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt

If first line in code below ends with a trailing space, an exception was thrown when calling method `lineLengthWithoutNewlinePrefix` for a node on line 2:
```
val foo1 = "foo1"
val foo2 = "foo2"
```

Handle trailing space on preceding line in call to `lineLengthWithoutNewlinePrefix`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRuleTest.kt

Fixes #2652
For the [operator spacing](https://pinterest.github.io/ktlint/latest/rules/standard/#operator-spacing) standard rule, instead of checking for whether any ancestor element is a KtPrefixExpression, check whether the closest ancestor that is a KtOperationExpression is a KtPrefixExpression.
This change will identify the case where the operator is inside a binary expression inside a prefix expression as **not** being a unary operator, and hence subject to the operator spacing checks.
* PREFIX_EXPRESSION
* PARENTHESIZED
* BINARY_EXPRESSION
* OPERATION_REFERENCE
* PsiElement(ELVIS)
The closest ancestor of KtPrefixExpression and KtBinaryExpression seems to be KtOperationExpression, so I've opted to use that as the predicate when searching through the ancestors. KtExpressionImpl seems …

Fix not checking for spacing around binary operators inside unary expression

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

The code example used to demonstrate disallowed code was correctly formatted (i.e., there were blank lines before declarations). This change corrects the example to properly reflect code that violates the rule.

Fix `blank line before declarations` rule code example

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundSquareBracketsRuleTest.kt

Fixes https://github.com/pinterest/ktlint/issues/2675
Fixes the erroneous error for notations like `[{ }]`, as described in the issue.
The `}]` case was already handled by https://github.com/pinterest/ktlint/pull/596, but the `[{` notation needed some additional fix. There was a special exception for `({`, and since this one is similar, I added the case for LBRACKET too.
Two tests were added, one to check that notations like `[{ a -> a }]`, `[{ }]`, and `[{}]` are allowed, and a second one to check that `[ { } ]` is formatted correctly.

Fixed [{ }] notation for issue #2675

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/EditorConfigDefaults.kt

The file path will be checked in `com.pinterest.ktlint.rule.engine.internal.EditorConfigDefaultsLoader.load`, no need to check nullability again.

Simplify default properties loading

---

RELEASE_TESTING.MD
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/CodeFormatter.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FinalNewlineRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeReferenceSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyClassBodyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundAngleBracketsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCommaRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundDotRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundDoubleColonRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundKeywordRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundRangeOperatorRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundSquareBracketsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenFunctionNameAndOpeningParenthesisRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeArgumentListSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TypeParameterListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRuleTest.kt

Regression test before release 1.3.0, and some refactorings.

Regression test before release 1.3.0

---

RELEASING.md
gradle.properties

Set version to 1.3.1-SNAPSHOT

---

.github/workflows/publish-release-build.yml
documentation/release-latest/docs/install/cli.md
documentation/snapshot/docs/install/cli.md
gradle/libs.versions.toml
ktlint-cli/build.gradle.kts

Almost every release, publishing to sdkman resulted in failures. Only a few users seems to depend on it.
Closes #2692

Remove sdkman

---

documentation/release-latest/docs/rules/experimental.md
documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/experimental.md
documentation/snapshot/docs/rules/standard.md

Add "standard:" prefix in rule ids in documentation
Closes #2700 

Add "standard:" prefix in rule ids in documentation

---

documentation/release-latest/docs/rules/experimental.md
documentation/release-latest/docs/rules/standard.md
documentation/release-latest/mkdocs.yml
documentation/snapshot/docs/rules/experimental.md
documentation/snapshot/docs/rules/standard.md
documentation/snapshot/mkdocs.yml

Add reference in documentation for each rule to suppress or adjust `.editorconfig`
Display an annotation for each rule id containing code fragments to:
* suppress the rule via an annotation
* enable the rule in `.editorconfig`
* disable the rule in `.editorconfig` Each of code fragments above contains a "copy to clipboard" button.
The solution now looks as follows:

Add reference in documentation for each rule to suppress or adjust `.editorconfig`

---

CHANGELOG.md

Correct changelog 1.3.0 experimental property to non-experimental links.
- [ x ] PR title is short and clear (it is used as description in the release changelog)
- [ x ] PR description added (background information)

Add link for backing-property-naming, correct binary-expression-wrapping

---

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt
ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt

Prevent inserting a whitespace element as first or last element in a composite node. In such cases insert the whitespace just before or after the composite element (recursively if needed). 
#2688 shows an example in which two different rules were inserting a whitespace at the same position in the code fragment but at different places in the AST. As a result two spaces were added to the formatted code instead of one.
Closes #2688

Do not insert a whitespace element as first or last child inside a composite element

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt

Do not rewrite a class to a single line signature in case it contains an EOL comment.
Closes #2689

Do not rewrite a class to a single line signature in case it contains an EOL comment

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt

Fix suppression handling when 'formatter:on' not properly specified
If the 'formatter:on' tag is not specified in the same scope as the 'formatter:off' tag, then the IndentationRule might throw an exception as the IndentationContextStack is not properly cleaned.
Also, cleaned up of `CommentSuppressionHint.EOL` type as it was not used since replacing the EOL suppression hints in `1.0` release.
Closes #2695

Fix suppression handling when 'formatter:on' not properly specified

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt

Fix false positive when primary constructor has no arguments and a secondary constructor exists
Closes #2690

Fix false positive when primary constructor has no arguments and a secondary constructor exists

---

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/IgnoreKtlintSuppressions.kt
ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rules/KtlintSuppressionRule.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt

Ignore suppressions for no-unused-imports rule
Imports which are only used in code blocks which are suppressed for ktlint should not be reported as unused as removal results in compilation errors.
Refactored the code so that a rule can be marked with interface `IgnoreKtlintSuppressions` to indicate that all suppressions for this rule are to be ignored.
Closes #2696

Ignore suppressions for no-unused-imports rule

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/CodeFormatter.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocator.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorTest.kt

Imports which are only used in code blocks which are suppressed for ktlint should not be reported as unused as removal results in compilation errors.
Refactored the code so that a rule can be marked with interface `IgnoreKtlintSuppressions` to indicate that all suppression for this rule are to be ignored.
The former SuppressionLocator lambda and object SuppressionLocatorBuilder are now replaced with the class SuppressionLocator. Upon each check whether a ASTNode has to be suppressed, it is also determined whether it is needed to rebuild the suppression hints. This is only needed when the code that is represented by the AST has been changed.
The CodeFormatter no longer has to rebuild the suppression locator after autocorrect. This responsibility is now moved into the RuleExecutionContext …

2696 no unused imports

---

ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/api/BaselineCLITest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/CodeFormatter.kt

The warning "Format was not able to resolve all violations" should not be logged in case the code only contains lint violations which may not be autocorrected according to the AutoCorrectHandler.
Closes #2726 

Fix false alert `Format was not able to resolve all violations which (theoretically) can be autocorrected`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt

Fix "unset" value for property ktlint_chain_method_rule_force_multiline_when_chain_operator_count_greater_or_equal_than
When value is set to "unset" the number of chain operators on a single line is not restricted as long as the max line length is not exceeded.
Closes #2712

Fix "unset" value for property ktlint_chain_method_rule_force_multiline_when_chain_operator_count_greater_or_equal_than

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Fix documentation `class-signature`
Closes #2713

Fix documentation `class-signature`

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md

Add missing reference in documentation for each rule to suppress or adjust `.editorconfig`
Closes #2732

Add missing reference in documentation for each rule to suppress or adjust `.editorconfig`

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocator.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

Suppress `backing-property-naming` on `@Suppress("PropertyName")`
Closes #2714

Suppress `backing-property-naming` on `@Suppress("PropertyName")`

---

ktlint-api-consumer/src/test/kotlin/com/pinterest/ktlint/api/consumer/KtLintRuleEngineTest.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/CodeFormatter.kt

When running on Windows, and `end_of_line` property not set in `.editorconfig` the line separators should not be changed from CRLF to LF whenever the file does not contain any lint violation that can be autocorrected.
Closes #2747

Prevent line separators to be changed from CRLF to LF

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

this fixes a problem with the `function-literal` rule removing non-redundant arrows from lambdas that are direct leafs of a when-entry or then/else. Without the arrow, the expression is left as a block instead.

fix: don't remove arrow from lambdas that are when/if leaf nodes

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRuleTest.kt

Replaced occurrences of `int` with `Int` in Kotlin code snippets to align with Kotlin's type system, which uses non-primitive types. The previous examples contained errors due to the use of `int`, which does not exist in Kotlin. This change ensures the code is syntactically correct and consistent with Kotlin's type conventions.

[Bugfix] `int` to `Int` migration

---

documentation/release-latest/docs/rules/experimental.md
documentation/snapshot/docs/rules/experimental.md

Change rule id `blank-lines-between-when-conditions` to `blank-line-between-when-conditions` in documentation.
Closes #2765

Fix rule id in documentation

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSemicolonsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSemicolonsRuleTest.kt

Fix false positive in `no-semi` rule for enum class without enum entries
Closes #2771

Fix false positive in `no-semi` rule for enum class without enum entries

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineExpressionWrappingRuleTest.kt

Prevent conflict between `multiline-expression-wrapping` and `function-signature`
When `function-signature` rule is configured with `ktlint_function_signature_body_expression_wrapping` set to `default` then the first line of a multiline expression body should be kept on the same line as the end of function signature, as long as max line length is not exceeded. In this case the `multiline-expression-wrapping` rule has to ignore the multiline function expression body.
Closes #2650

Prevent conflict between `multiline-expression-wrapping` and `function-signature`

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocator.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRuleTest.kt

Suppress `backing-property-naming` rule with `@Suppress("LocalVariableName")`
Closes #2779

Suppress `backing-property-naming` rule with `@Suppress("LocalVariableName")`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRuleTest.kt

Fix false positive in `class-signature` when EOL comment is between a class annotation and other class modifier
Closes #2755

Fix false positive in `class-signature` when EOL comment is between a class annotation and other class modifier

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt

Fix globs ending with `**`
According to https://git-scm.com/docs/gitignore a trailing `**` in a glob has to match with any file in the directory that matches the glob without that trailing `**`.
Given glob "**/Test*/**" the file "src/Foo/TestFoo.kt" should not be matched, and file "src/TestFoo/FooTest.kt" is matched. If the original pattern would be expanded with additional pattern "**/Test*" then both files would have been matched.
Closes #2781
- [X Commit message are well written. In addition to a short title, the commit message also explain why a change is made.
[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release …

Fix globs ending with `**`

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt

Revert changing log level in FileUtils.kt
Follow up on #2787

Revert changing log level in FileUtils.kt

---

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt

Return exit code 1 in case violations have been found but file is unchanged
In very rare cases it is possible that Lint violations are detected while formatting but that they have opposite effects and the file gets not altered at all. As the logging already might contain the message "Format was not able to resolve all violations which (theoretically) can be autocorrected in file ..." the format may not return with exit code 0.
Closes #2795

Return exit code 1 in case violations have been found but file is unchanged

---

ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/CodeFormatter.kt

Do not repeat formatting if file is unchanged
Closes #2804

Do not repeat formatting if file is unchanged

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListSpacingRuleTest.kt

Ignore missing whitespace after trailing comma in single line parameter value list
Closes #2794

Ignore missing whitespace after trailing comma in single line parameter value list

---

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ElementType.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierOrderRule.kt

Remove calls to `KtTokens.HEADER_KEYWORD` & `KtTokens.IMPL_KEYWORD`. These have been removed from Kotlin effective Kotlin 2.1.0-Beta1.
Without this change, projects that use ktlint-rule-engine-core as a dependency cannot build when upgraded to Kotlin-2.1.0-Beta1.
References:
* https://youtrack.jetbrains.com/issue/KT-52315/Legacy-keywords-header-impl-break-enum-definitions
* https://github.com/JetBrains/kotlin/commit/76592dcb556f811c476fcb3912a910bbd19ffe3b#diff-acd77bf153b196d3b53b21fcd27f3971151fba10645714064933d6a916b2a4b2
[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release documentation](https://github.com/pinterest/ktlint/tree/master …

Remove HEADER_KEYWORD & IMPL_KEYWORD

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRuleTest.kt

Do not remove imports for which the fully qualified path is identical to the package name
In rare cases this could lead to code which no longer can be compiled
Closes #2821

Do not remove imports for which the fully qualified path is identical to the package name

---

documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/RuleExecutionContext.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

Fix indentation of a multiline parameter list inside a function literal for code style `ktlint_official`.
For other code styles the indentation does not comply with Kotlin Coding conventions as other the formatting would conflict with default IDEA formatting.
Closes #2816

Fix indentation of a multiline parameter list inside a function literal for code style `ktlint_official`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRuleTest.kt

Do not insert a trailing comma in a multiline when-entry containing a guard
Closes #2817

Do not insert a trailing comma in a multiline when-entry containing a guard

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

This fixes the wrapping of the expression for code style `intellij_idea` which does not set the `max_line_length` property by default. But it also fixes the wrapping in case the `max_line_length` property contains value `unset` for any of the code styles.
Closes #2827

Fix wrapping of expression body when `max_line_length` not set

---

documentation/snapshot/docs/install/cli.md
ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt
ktlint-rule-engine/api/ktlint-rule-engine.api
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/api/Code.kt

Fixes #1123
Add an optional CLI `--stdin-path` to provide a virtual file location for stdin. This allows for re-enabling the `FilenameRule` as well as supporting custom rules that rely on the file path while still using stdin.

Fixes #1123 - Add --stdin-path to provide a virtual file location for stdin

---

documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/editorconfig/SafeEnumValueParser.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumEntryNameCaseRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/EnumEntryNameCaseRuleTest.kt

This property allows enum entry names to be restricted to:
* `upper_cases`: an enum entry may only contain uppercases, and underscores, and digits, and dicritics on letters and strokes
* `camel_cases`: an enum entry may only contain CamelCase values, including digits, and dicritics on letters and strokes)
* `upper_or_camel_case`: allows both the `upper_cases` and `camel_cases` styles as defined in the Kotlin Coding Conventions
Closes #2835

Add property `.editorconfig` property `ktlint_enum_entry_name_casing`

---

RELEASE_TESTING.MD
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditions.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditionsTest.kt

Small fixes found during integration test prior to release 1.4.0

1.4.0 integration test fixes

---

documentation/snapshot/docs/rules/experimental.md

Fix a typo in the docs regarding the `when-entry-bracing` rule.

Fix typo `when-entry-spacing` → `when-entry-bracing`

---

documentation/release-latest/docs/rules/experimental.md

Add when-entry-bracing rule to release docs

Add when-entry-bracing rule to release docs

---

documentation/release-latest/docs/rules/configuration-ktlint.md
documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/configuration-ktlint.md
documentation/snapshot/docs/rules/standard.md

Fix documentation import layouts
Closes #2866 

Fix documentation import layouts

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRuleTest.kt

Ignore multi dollar string interpolation prefix in `string-template-indent` rule.
Closes #2885

Ignore multi dollar string interpolation prefix in `string-template-indent` rule

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRuleTest.kt

Wrap the expression body in case `.editorconfig` property `ktlint_function_signature_body_expression_wrapping` is set to `always`. This setting should precedence above merging the first line of the expression body with the closing parenthesis of a function without return type.
Closes #2872

Wrap the expression body in case `.editorconfig` property `ktlint_function_signature_body_expression_wrapping` is set to `always`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunKeywordSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunKeywordSpacingRuleTest.kt

Add missing space between `fun` keyword and identifier when latter is wrapped between backticks
Closes #2879

Add missing space between `fun` keyword and identifier when latter is wrapped between backticks

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/UnnecessaryParenthesesBeforeTrailingLambdaRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/UnnecessaryParenthesesBeforeTrailingLambdaRuleTest.kt

Fix false positive when empty parameter list is in between trailing lambda's of a nested call expression
Given code below:
```
fun fooBar(foo: () -> String): (() -> String) -> String = { bar -> foo().plus("  ").plus(bar()) }
val foobar = fooBar { "Hello" }() { "world" }
```
then the empty parameter list may ot be removed as it results in a compile error.
Closes #2884

Fix false positive when empty parameter list is in between trailing lambda's of a nested call expression

---

documentation/release-latest/docs/rules/standard.md
documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRuleTest.kt

Do not wrap a context receiver in a function parameter type reference
Closes #2854

Do not wrap a context receiver in a function parameter type reference

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRuleTest.kt

Allow comment before parameter list in function literal (`function-literal`)
Merging an EOL comment before the parameter list with the actual parameter list results in code that no longer compiles.
Closes #2850

Allow comment before parameter list in function literal (`function-literal`)

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRuleTest.kt

Allow backing property to be defined in the companion object (`backing-property-naming`)
Closes #2877

Allow backing property to be defined in the companion object (`backing-property-naming`)

---

CHANGELOG.md
gradle.properties

Prepare release 1.5.0

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/ktlint-dokka.gradle.kts
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/KotlinPsiFileFactory.kt

Householding - clean up some simple deprecations in build

Deprecations in 1.5.0

---

.gitignore

I do not know exactly why, but this directory gets created for me when I work on this project. I know a recent kotlin update introduced this directory, but I'm not sure why its not already ignored here.

ignore `.kotlin` directory

---

documentation/release-latest/docs/install/cli.md
documentation/snapshot/docs/install/cli.md

This adds the missing `--code-style` flag from the command line docs.
Currently, running `ktlint generateEditorConfig intellij_idea` will generate error:
```bash
Error: got unexpected extra argument (intellij_idea)
Error: missing option --code-style
```

Add missing --code-style flag in CLI documentation

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt

This PR fixes an issue where PropertyNamingRule correctly enforced PascalCase but incorrectly suggested using ScreamingSnakeCase in the error message.
What was done?
•	Updated the error message in visitConstProperty() to correctly reflect the configured naming style.
•	Updated test accordingly to expect the updated error message.

Fix incorrect error message in PropertyNamingRule when enforcing PascalCase

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt

Add configuration option to handle (certain) annotation with parameters identical to annotations without parameters
Closes #2852

Add configuration option to handle (certain) annotation with parameters identical to annotations without parameters

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSingleLineBlockCommentRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSingleLineBlockCommentRuleTest.kt

Move logic of missing whitespace before block comment to NoSingleLineBlockCommentRule
In #2000 the `NoSingleLineBlockCommentRule` was extracted from the `CommentWrappingRule`. Some logic was left behind in the old rule, causing an exception when running with other code style than `ktlint_official`. As a result, the dependency from `NoSingleLineBlockCommentRule` on `CommentWrappingRule` is also no longer needed.
Closes #2936

Move logic of missing whitespace before block comment to NoSingleLineBlockCommentRule

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundParensRuleTest.kt

Report and fix a single line condition wrapped between parentheses with an unexpected newline
The condition should
* not be preceded, nor followed by whitespace
* be preceded *and* followed by whitespace containing a newline
Closes #2943

Report and fix a single line condition wrapped between parentheses with an unexpected newline

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt

Do not wrap an operation reference after an annotated expression to a separate new line
For most operation references this leads to code that cannot be compiled. For logical operators like && and || it does compile but leads to ugly formatting.
Closes #2955

Do not wrap an operation reference after an annotated expression to a separate new line

---

documentation/release-latest/docs/install/integrations.md
documentation/snapshot/docs/install/integrations.md
gradle/wrapper/gradle-wrapper.properties

Change default maven integration to use `exec-maven-plugin` in favor of `maven-antrun-plugin`
The `exec-maven-plugin` uses the fat jar published by Ktlint instead of relying on `maven-antrun-plugin` to pull all dependencies and built it.
Closes #2993

Change default maven integration to use `exec-maven-plugin` in favor of `maven-antrun-plugin`

---

build-logic/src/main/kotlin/ktlint-publication.gradle.kts
documentation/release-latest/docs/install/snapshot-build.md

OSSRH is being sunset at the end of this month. Following the documents [here](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/) and [here](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/), I am updating the publishing URLs to the OSSRH staging APIs until we can evaluate a new Central Portal gradle plugin to use.
Separately, I will be updating the authentication credentials. (#3007)

Update publishing URLs to point to Central Portal OSSRH staging API

---

.github/workflows/publish-release-build.yml
.github/workflows/publish-snapshot-build.yml
build-logic/src/main/kotlin/ktlint-publication.gradle.kts

(Depends on #3006)
OSSRH is being sunset, so our publishing flows need to be updated to use the username and token generated from Central Portal.
Secrets have already been updated in the repository.

Update publishing credentials to use new Central Portal username/token

---

documentation/snapshot/docs/rules/standard.md

This pull fixes many typos and grammatical errors in the Keyword Spacing, Modifier List Spacing, Nullable List Spacing, Operator Spacing, Parameter List Spacing, Parenthesis Spacing, Range Spacing, Spacing Between Function Name and Open Parenthesis, Try Catch Finally Spacing, Type Argument List Spacing, Type Parameter List Spacing, Unary Operator Spacing, String Template, String Template Indent, Trailing Comma on Call Site, Trailing Comma on Declaration Site, Argument List Wrapping, Comment Wrapping, Enum Wrapping, Multiline Expression Wrapping, Parameter Wrapping, Property Wrapping, and Wrapping descriptions. Some changes were also made to clarify the overall descriptions. …

Fixes to typos and grammatical errors on the Standard rules page.

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverListWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverListWrappingRuleTest.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRuleTest.kt

Similar to `context-receiver-list` but it only wraps when the list contains a context parameter instead of a context receiver
Closes #3029

Add `context-receiver-list-wrapping` rule

---

build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts
build.gradle.kts
documentation/release-latest/docs/install/integrations.md
documentation/snapshot/docs/install/integrations.md
ktlint-cli/build.gradle.kts
ktlint-cli/src/main/scripts/ktlint.bat
ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/CommandLineTestRunner.kt

Follow-up on #2793 (#3040)
The suppression "--sun-misc-unsafe-memory-access=allow" should not override the suppression for "--add-opens=java.base/java.lang=ALL-UNNAMED"
Closes #2793

The suppression "--sun-misc-unsafe-memory-access=allow" should not override the suppression for "--add-opens=java.base/java.lang=ALL-UNNAMED"

---

documentation/snapshot/docs/rules/standard.md
ktlint-rule-engine-core/api/ktlint-rule-engine-core.api
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/Rule.kt
ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RuleExecutionRuleFilter.kt
ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/rulefilter/RuleExecutionRuleFilterTest.kt
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoUnusedImportsRuleTest.kt

Do not run `no-unused-imports` rule by default
Closes #3038

Do not run `no-unused-imports` rule by default

---

build-logic/build.gradle.kts
gradle/libs.versions.toml

For the `build-logic` project `kotlin-dsl` plugin (5.2.0) sets its own recommended kotlin version (`2.0.21`), which is not compatible with latest poko plugin. Our options are:
1. Bump kotlin-dsl plugin to latest [6.1.2](https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl) which hopefully will depend on higher kotlin version - 🔴 doesn't work out of the box, because develocity plugin is not yet compatible
2. Make the build resolve higher kotlin version for the `build-logic` project 
3. Migrate away from kotlin-dsl 😛 This types of incompatibilities is one of the reason why I personally prefer not to use kotlin-dsl 😅 
This PR implements option 2).  …

Bump `poko-gradle-plugin` with a workaround (enforce compatible Kotlin version)

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FilenameRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FilenameRuleTest.kt

Clarify violation message in `filename` rule
Closes #2998

Clarify violation message in `filename` rule

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierOrderRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierOrderRuleTest.kt

Add context receiver list to `modifier-order` rule
Closes #3027

Add context receiver list to `modifier-order` rule

---

.github/workflows/pull-request-with-code.yml
.github/workflows/pull-request-without-code.yml

The https://github.com/pinterest/ktlint/pull/3049 contained commits which I pushed to my fork to test how the build behaves on windows. These can be safely removed now. 
Moreover, after https://github.com/pinterest/ktlint/pull/3035, the build-logic project uses latest kotlin version which supports Java 24, making the extra workaround unnecessary

Cleanup Java 24 bump 

---

build-logic/src/main/kotlin/PublicationPlugin.kt
gradle/README-javadoc.md
gradle/README-sources.md

Central Portal [requires](https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources) source and javadoc jars for every artifact published. Since we have our source code on GitHub and a comprehensive docs site, this PR creates empty placeholder jars which point developers to the proper URLs.

Add tasks to create placeholder docs and sources jars to pass Central Portal Validation

---

.github/workflows/main.yml

The release of 1.7.0 failed at bumping the homebrew version of ktlint. As of that the release process (the announce script) has not run yet.

Add temporary workflow to finish (announce) release 1.7.0

---

build-logic/src/main/kotlin/KotlinCommonPlugin.kt

Fixes #3061
The artifacts produced by the build can useapis available in Kotlin sdlib version 2.2 leading to issues like #3061.
The proposed fix is to lower the apis ktlint's source code can reference to.
|Before|After|
|---|---|
|<img width="586" height="604" alt="image" src="https://github.com/user-attachments/assets/04568526-8965-4ea0-90a4-eabd860eecc5" />|<img width="534" height="484" alt="image" src="https://github.com/user-attachments/assets/13d573f7-f213-44f8-9f45-eabeac6b44ba" />|

Make Ktlint code backwards compatible with lower Kotlin versions (down to 2.0)

---

ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRuleTest.kt

Fix conflict between `modifier-list-spacing` and `context-receiver-list-wrapping`
Wrapping of a context receiver list in `modifier-list-spacing` may not conflict with the wrapping in `context-receiver-list-wrapping`
Closes #3065

Fix conflict between `modifier-list-spacing` and `context-receiver-list-wrapping`

---

gradle/libs.versions.toml
ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/SinceKtlint.kt
ktlint-ruleset-standard/build.gradle.kts
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BackingPropertyNamingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBetweenWhenConditions.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassNamingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassSignatureRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ConditionWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ExpressionOperandWrappingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionLiteralRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeModifierSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeReferenceSpacingRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MixedConditionOperatorsRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineLoopRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoBlankLineBeforeRbraceRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSingleLineBlockCommentRule.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WhenEntryBracing.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SinceKtlintAnnotationTest.kt

Adds comprehensive validation for @SinceKtlint annotations and fixes multiple annotation issues to support the implementation discussed in #3099.
1. Added a unit test to validate all rules follow the @SinceKtlint annotation usage as expected. Checks for missing annotations, proper experimental/stable status alignment, and version format compliance. For this, I had to add kotlin-reflect as a test implementation for proper reflection support.
2. Fixed Version Format Violations (8 rules)
Corrected patch-level versions to major.minor format as required:
• NoBlankLineBeforeRbraceRule: "0.10.2" → "0.10"
• WhenEntryBracing: "1.4.0" → "1.4"
• ConditionWrappingRule: "1.1.0" → "1.1"
• BlankLineBetweenWhenConditions: "1.2.0" → "1.2"
• ExpressionOperandWrappingRule: "1.7.0" → "1.7"
• KdocRule: …

Validate @SinceKtlint annotations with test and uniformize existing rules

---

documentation/release-latest/docs/install/integrations.md
documentation/snapshot/docs/install/integrations.md

Replace link to maven wrapper with link to official apache project.
Closes #3108

Fix link to maven wrapper

---

.github/workflows/generate-changelog.yml
.github/workflows/publish-release-build.yml
.github/workflows/publish-release-docs.yml
.github/workflows/publish-snapshot-build.yml
.github/workflows/publish-snapshot-docs.yml
.github/workflows/pull-request-with-code.yml
.github/workflows/pull-request-without-code.yml

As a result of enabling [code security scanning](https://github.com/pinterest/ktlint/pull/3113), it is advised to restrict access to GitHub token. All workflows (except the code scanning itself) are now restricted to "contents: read". It is to be expected that some workflows (publish of docs, and/or releases) will break when not having enough privileges.

Restrict access to GitHub token to "contents: read"

---

.announce
documentation/release-latest/docs/api/custom-rule-set.md
documentation/snapshot/docs/api/custom-rule-set.md
ktlint-ruleset-template/build.gradle.kts
ktlint-ruleset-template/src/test/kotlin/yourpkgname/NoVarRuleTest.kt

Simply creation of a custom ruleset
* Simplify and document the build file so that it is more convenient to be used to start a new project for a custom ruleset
* Modify the ktlint version in the build file during the release process
* Improve documentation
* Remove outdated comment in NoVarRuleTest.kt
Closes #3048

Simplify creation of a custom ruleset

---

documentation/snapshot/docs/rules/standard.md
ktlint-ruleset-standard/api/ktlint-ruleset-standard.api
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt
ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ThenSpacingRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ThenSpacingRuleTest.kt

Add rule `then-spacing`
Closes #3064

Add rule `then-spacing`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt

Fix indent of function parameter with multiline expression in `android_studio` code style similar to `ktlint_official`.
Closes #3062

Fix indent of function parameter with multiline expression in `android_studio`

---

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt
ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRuleTest.kt

Prevent that an early return followed by lambda expression results in joining the lines
Closes #3125

Prevent that an early return followed by lambda expression results in joining the lines

---

renovate.json

Ignore renovate updates for JUnit v6 as it requires Java17+
Ktlint supports java 8 and 11 during 1.x lifetime

Ignore renovate updates for JUnit v6 as it requires Java17+
