ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundColonRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundColonRuleTest.kt
=> Fix unnecessary space between function signature and return type

README.md
update maven badge uses latest version.
=> README.md update version

README.md
Ref https://github.com/ktlint/ktlint.github.io/pull/1
=> Add task group and description to the Gradle example

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/IfElseMultiLineBlockWithCurlBraceRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt, ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/UseWhiteSpaceInsteadOfTabRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/UseWhiteSpaceInsteadOfTabRuleTest.kt
Hi, Thank you for developing wonderful tool. I use ktlint heavily in my project!
Fix issue of https://github.com/shyiko/ktlint/issues/214. If you have free time, Cloud you review this PR?
=> Issue#214 Add UseWhiteSpaceInsteadOfTabRule

ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt
=> Adding a flag to define the path for the .editorconfig file

ktlint/src/main/kotlin/com/github/shyiko/ktlint/Main.kt
https://github.com/shyiko/ktlint/issues/282
=> Fix for extra newlines when using --stdin

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/MemberOrTypeAnnotationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/MemberOrTypeAnnotationRuleTest.kt
Fixes #258 
For reviewers to double-check:
- Are there any tests I'm missing? I feel like there are probably some more obtuse/strange ways annotations can be placed
=> Create rule+tests to lint/format annotations for members/types

build.gradle, ktlint-ruleset-template/build.gradle, pom.xml
As the title says, updated kotlin to 1.3.0.
=> Update kotlin version to 1.3.0

README.md
Thank you for this repository.
I fixed it because I needed tap when running brew install.
=> fix brew install step

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/CommentSpacingRuleTest.kt
=> Escape comment space for "Inject Language"

ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCurlyRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundCurlyRuleTest.kt
=> Make new line after function return type declaration fail.

LICENSE, README.md
Updating to add Pinterest into copyright
=> Add Pinterest, Inc. to license + readme

ktlint-core/pom.xml, ktlint-reporter-checkstyle/pom.xml, ktlint-reporter-json/pom.xml, ktlint-reporter-plain/pom.xml, ktlint-ruleset-experimental/pom.xml, ktlint-ruleset-standard/pom.xml, ktlint-test/pom.xml, ktlint/pom.xml, pom.xml
* Also updated various `shyiko` -> `pinterest` refs
=> Update groupId to com.pinterest.ktlint

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt, ktlint-ruleset-experimental/src/test/resources/spec/indent/format-parameter-list-expected.kt.spec, ktlint-ruleset-experimental/src/test/resources/spec/indent/format-parameter-list.kt.spec
Fixes https://github.com/pinterest/ktlint/issues/374
=> Include annotations in parameter indentation checks. 

README.md, ktlint-ruleset-template/build.gradle
`.announce` script not working; manually updating.
=> Updating README refs to 0.32.0

README.md
* More version updates
* More `shyiko` -> `pinterest`
=> Updating more refs in the README

CHANGELOG.md
=> Fix 0.32.0 changelog

ADOPTERS.md
Thanks for taking ownership and for your commitment to this project. We at Freeletics use and love Ktlint to and have with @gabrielittner and @Tapchicoma already two contributors and would like to continue do that in the future.
=> Added Freeletics to Adopters.md

ADOPTERS.md
- Added Ellation company to `ADOPTERS.md`
See #417.
=> Add Ellation to ADOPTERS.md

ADOPTERS.md
Evidence: https://github.com/gradle/kotlin-dsl-conventions/blob/8e954bd46a85e5d28dd9741661d0146337180f19/src/main/kotlin/org/gradle/kotlin/dsl/experiments/plugins/GradleKotlinDslKtlintConventionPlugin.kt
=> Add Gradle to Adopters

ADOPTERS.md
As per https://github.com/pinterest/ktlint/issues/417, add Shopify as an adopter. We're currently using ktlint across our Android monorepo.
=> Add Shopify to ADOPTERS.md

ADOPTERS.md
Thanks for taking over ownership of this library :) we have found it to be very helpful at Airbnb!
=> Add Airbnb to adopters file

ADOPTERS.md
We've been using ktlint for almost 2 years now!
=> Add Tinder to adopters list

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MultiLineIfElseRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/PackageNameRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/PackageNameRuleTest.kt
=> remove author

pom.xml, settings.gradle
#445
@shashachu
Sort modules in `settings.gradle` and in top level `pom.xml`.
=> Process of migrating to gradle - sort module names

.travis.yml
#445
@shashachu
Start building this project with Gradle as well. This will help to make sure to prevent any regressions building with Gradle.
=> Process of migrating to gradle - start building with gradle

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
And made command line options style consistent.
=> Replace usage of arrayOf with array literal.

.travis.yml
@shashachu
Build with JDK8 and build with JDK11.
=> Build with JDK8 and JDK11

ktlint-core/build.gradle, ktlint-reporter-checkstyle/build.gradle, ktlint-reporter-json/build.gradle, ktlint-reporter-plain/build.gradle, ktlint-ruleset-experimental/build.gradle, ktlint-ruleset-standard/build.gradle, ktlint-test/build.gradle, ktlint/build.gradle
=> Use newer Gradle configurations - implementation, testImplementation

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt, ktlint/src/main/kotlin/com/pinterest/ktlint/internal/KtlintVersionProvider.kt
This removes explicit version and help fields.
Version detection was moved to separate class.
More info about mixin: https://picocli.info/#_mixin_standard_help_options
=> Use picoli help mixin.

.travis.yml, build.gradle
Closes #463
@shashachu 
This runs ktlint on the entire project similar to how Maven is running ktlint on the project.
=> Process of migrating to gradle - Run ktlint on itself

build.gradle, ktlint-ruleset-template/build.gradle, ktlint/build.gradle
Fix ktlint build and configure language compatibility from root level
@shashachu
=> Fix ktlint build and configure language compatibility from root level

.buildscript/deploy_snapshot.sh, build.gradle, gradle.properties, ktlint-core/build.gradle, ktlint-core/gradle.properties, ktlint-reporter-checkstyle/build.gradle, ktlint-reporter-checkstyle/gradle.properties, ktlint-reporter-json/build.gradle, ktlint-reporter-json/gradle.properties, ktlint-reporter-plain/build.gradle, ktlint-reporter-plain/gradle.properties, ktlint-ruleset-experimental/build.gradle, ktlint-ruleset-experimental/gradle.properties, ktlint-ruleset-standard/build.gradle, ktlint-ruleset-standard/gradle.properties, ktlint-test/build.gradle, ktlint-test/gradle.properties, ktlint/build.gradle, ktlint/gradle.properties
@shashachu 
Add support for publish Ktlint via Gradle
I used @vanniktech's plugin and here is an example of integrating it: https://github.com/square/okhttp/commit/c53f8db73d53eb8fc1c5d426568d35e9b99c2fa2.
=> Process of migrating to gradle - Add maven publish

build.gradle, pom.xml
Changelog: https://github.com/JetBrains/kotlin/releases/tag/v1.3.41
=> Update Kotlin to 1.3.41 version.

build.gradle, pom.xml
Resolves dependency check report https://ossindex.sonatype.org/vuln/206ca2c3-5cae-41e0-9c8a-c696212b9956
=> Upgrade AssertJ to 3.12.2

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
Fixes https://github.com/pinterest/ktlint/issues/533
Note: command line flag will override `.editorconfig`
=> Add --disabled_rules flag to CLI

ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundAngleBracketRuleTest.kt, ktlint-ruleset-standard/src/test/resources/spec/angle-bracket-spacing/format-expected.kt.spec, ktlint-ruleset-standard/src/test/resources/spec/angle-bracket-spacing/format.kt.spec, ktlint-ruleset-standard/src/test/resources/spec/angle-bracket-spacing/lint.kt.spec
https://github.com/pinterest/ktlint/issues/580
=> Failing test for generics formatting

ktlint/build.gradle
```
$ ./ktlint/build/run/ktlint --version
0.35.0-SNAPSHOT
```
=> Add version into gradle-built JARs

build.gradle, pom.xml
Changelog: https://github.com/JetBrains/kotlin/blob/v1.3.60/ChangeLog.md
=> Update Kotlin to 1.3.60 version.

.announce, RELEASING.md, build.gradle
Sync of changelog to Github release would be done later separately.
=> Setup project publishing in Gradle.

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRuleTest.kt
=> Fix indentation with new line before return type

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Adapted version of [detekt bug-report template](https://github.com/arturbosch/detekt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
=> Add Github issue template for bug reports.

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoMultipleSpacesRuleTest.kt
=> NoMultipleSpacesRule: Allow multiple spaces in KDoc 

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRuleTest.kt
=> Allow trailing comment in multiline param for experimental:indent

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRuleTest.kt
=> FinalNewlineRule: don't report for empty files

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleIdeaTest.kt
=> ImportOrderingRule: Fix imports containing "as" being removed

CHANGELOG.md, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/importordering/ImportOrderingRuleIdeaTest.kt
=> Fix import ordering distinction

build.gradle, ktlint/build.gradle
Set `dryRun` to `true` and run `githubRelease` task, then check output of the task.
=> Fix githubRelease is not generating proper release information.

CHANGELOG.md, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt
=> Don't mark provideDelegate as unused for any import path

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoWildcardImportsRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoWildcardImportsRuleTest.kt
=> NoWildcardImportsRule: don't report it if asterisk with backticks

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRuleTest.kt
=> SpacingAroundKeywordRule: don't report it if right brace is not part of 'if' statement

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt, ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt
=> Preserves properties assigned to unset

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt, ktlint-ruleset-standard/src/test/resources/spec/indent/format-expected-tabs.kt.spec
=> Initial support for tab-based indentation

CHANGELOG.md, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/KotlinPsiFileFactory.kt
=> Extract PsiFileFactory initialization to internal file.

CHANGELOG.md, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/PositionInTextLocator.kt
Moved related code to internal.
=> Deprecate 'calculateLineColByOffset()' public method.

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt
AST extensions has the same method.
=> Remove duplicated method.

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/SupressedRegionLocator.kt
=> Extract suppressed region locator into internal file.

CHANGELOG.md, ktlint/src/main/kotlin/com/pinterest/ktlint/internal/IntellijIDEAIntegration.kt
The current version of ```ktlint --apply-to-idea``` only finds the old Intellij 2019 config:
```
The following files are going to be updated:
/Users/michaeljohansen/Library/Preferences/IdeaIC2019.3/codestyles/ktlint.xml
/Users/michaeljohansen/Library/Preferences/IdeaIC2019.3/options/code.style.schemes.xml
/Users/michaeljohansen/Library/Preferences/IdeaIC2019.3/inspection/ktlint.xml
/Users/michaeljohansen/Library/Preferences/IdeaIC2019.3/options/editor.codeinsight.xml
/Users/michaeljohansen/Library/Preferences/IntelliJIdea2019.2/codestyles/ktlint.xml
/Users/michaeljohansen/Library/Preferences/IntelliJIdea2019.2/options/code.style.schemes.xml
/Users/michaeljohansen/Library/Preferences/IntelliJIdea2019.2/inspection/ktlint.xml
/Users/michaeljohansen/Library/Preferences/IntelliJIdea2019.2/optio …
```
=> applyToIDEA location for IDEA 2020.1.x and above on MacOs

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt
=> NoUnusedImportsRule: fix false positive for sub class imports

ADOPTERS.md
=> Add Flickr to ADOPTERS.md

CHANGELOG.md, README.md
* Added rule ids into README (#879)
* Added changelog entry for #868
=> Small doc updates

.announce, .homebrew, build.gradle
* Added task to run Homebrew `bump-formula-pr`
* Modified `.announce` script to push refs to a new branch rather than master; as master is protected branch
=> Updating release scripts

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoUnusedImportsRuleTest.kt
=> NoUnusedImportsRule: fix false positive when import directive has backticks and alias

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationRuleTest.kt
=> Fix false positive "File annotations should be separated from file contents with a blank line" in script

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
=> ArgumentListWrappingRule: allow an inline block comment

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/MultiLineIfElseRuleTest.kt
=> MultiLineIfElseRule: place end of line comments in block

ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/ParameterListWrappingRuleTest.kt
Fixes #938
https://github.com/pinterest/ktlint/issues/938 has been resolved by https://github.com/pinterest/ktlint/pull/950.
=> ParameterListWrappingRule: add test for https://github.com/pinterest/ktlint/issues/938

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
=> IndentationRule: correctly indent  property delegates

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
=> IndentationRule: fix wrong indentation in delegation

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
=> IndentationRule: fix wrong indentation in named arguments

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithAnnotationsRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/SpacingBetweenDeclarationsWithAnnotationsRuleTest.kt
=> SpacingBetweenDeclarationsWithAnnotationsRule: don't report if not between declarations

README.md
IDE version info:
```
IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
macOS 10.15.7
```
=> Update "for Integration with IntelliJ IDEA"

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundKeywordRuleTest.kt
=> SpacingAroundKeywordRule: don't report when right brace is after try-catch block

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/SpacingAroundCommaRuleTest.kt
=> SpacingAroundCommaRule: don't report when comma is before right parenthesis

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
=> IndentationRule: fix incorrect indentation with multiple interfaces

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
=>  ArgumentListWrappingRule: fix false positive when max_line_length in EditorConfig is set

CHANGELOG.md, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
Closes #877 
Turns out this has been already fixed - just added a test and updated the changelog accordignly
=> Add test for #877

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
=> Fix indentation for lines at expected indentation level but with wrong indentation style (#425)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/new_rule_proposal.yml, .github/PULL_REQUEST_TEMPLATE.md
This PR will add:
- pull request template
- new "enhancement" issue type template
- new "New rule" issue type template
=> Additional pull request and issues templates

CHANGELOG.md, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
=> Fix false positive after `else` keyword (`argument-list-wrapping`)

.github/workflows/gradle-pr-build.yml
=> Run CI checks addintionally on Windows OS.

CHANGELOG.md, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
=> Fix IndexOutOfBoundsException in `argument-list-wrapping-rule` formatting file with many corrections

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/KotlinPsiFileFactory.kt
=> Fix Kotlin compiler may be released not in all cases.

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MaxLineLengthRule.kt
=> Fix editorconfig property for max-line-length rule

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/NoConsecutiveBlankLinesRuleTest.kt
=> Fix NPE in NoConsecutiveBlankLinesRule.

README.md
Updating README refs to point to new release.
=> Updated refs to latest (0.41.0) release

gradle.properties
=> Update snapshot version to 0.42.0

CONTRIBUTING.md
=> [FIX] Fix CONTRIBUTING.md typo

gradle/verification-metadata.xml
Explicitly add gnupg keyserver for dependency verification.
=> Fix dependency verification.

CHANGELOG.md, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRuleTest.kt
=> Fix false positive with eol comment (`annotation-spacing`)

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/AnnotationSpacingRuleTest.kt
=> Additional fixes for #1168

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/EnumEntryNameCaseRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/EnumEntryNameCaseRuleTest.kt
- Use the same regex as IntelliJ
- Added tests for failures
- Removed formatting code/test
=> Simplify implementation of enum case rule

README.md
=> Updated refs to latest (0.42.0) release

ktlint-reporter-sarif/src/test/kotlin/com/pinterest/ktlint/reporter/sarif/SarifReporterTest.kt
Temporarily ignoring this test to unblock other PRs from merging.
=> Ignoring Sarif reporter test to unblock PRs

.github/workflows/gradle-pr-build.yml
Uploading test artifacts to more easily debug CI-only test failures.
=> Upload test artifacts on build failure

CHANGELOG.md, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
Fixed a regression in the experimental argument-list-wrapping rule that was introduced in 0.41 
- [ x ] tests are added
- [ x ] `CHANGELOG.md` is updated
=> Argument list wrapping

ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRule.kt, ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/ArgumentListWrappingRuleTest.kt
Tweak to previous argument-list-wrapping fix
- [ x ] tests are added
=> Followup tweak to argument-list-wrapping rule

CHANGELOG.md, ktlint/src/main/kotlin/com/pinterest/ktlint/internal/IntellijIDEAIntegration.kt
=> Move .idea folder presence check to the right place

ktlint/src/main/kotlin/com/pinterest/ktlint/Main.kt
Will make bug reports clearer.
=> Update Internal Error message to include information about getting stacktrace

.github/workflows/gradle-pr-build.yml, .github/workflows/gradle-snapshot-build.yml
=> Bump github actions

.editorconfig, CHANGELOG.md, README.md, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/EditorConfig.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/ReporterProvider.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/RuleSetProvider.kt, ktlint-ruleset-template/build.gradle, ktlint/build.gradle
Replace part of http with https.
=> Update docs to use https

README.md
Adds link to third-party reporter https://github.com/musichin/ktlint-github-reporter
=> add third-party reporter link

CHANGELOG.md
=> Changelog for 0.43.0

CHANGELOG.md, README.md
Pulling in 0.43.2 changelog info
=> Update CHANGELOG and README in master branch

ktlint/src/main/resources/ktlint-git-pre-commit-hook-android.sh, ktlint/src/main/resources/ktlint-git-pre-commit-hook.sh, ktlint/src/main/resources/ktlint-git-pre-push-hook-android.sh, ktlint/src/main/resources/ktlint-git-pre-push-hook.sh
Ktlint should run on modified files only.
Fixes https://github.com/pinterest/ktlint/issues/1339
=> Fix git hooks: do not run ktlint on all files of the current directory

ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRuleTest.kt
Fix  lint violations which somehow have been merged to master without being detected by build.
=> Fix lint violations in master

README.md
Added proposed configurations for IntelliJ IDEA with `editorconfig`
=> Added IDEA settings with editorconfig on README

README.md
=> Update README ktlint version to 0.43.2

README.md
=> Update README.md with all rules

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/new_rule_proposal.md, .github/PULL_REQUEST_TEMPLATE.md
The updated templates aim to assist the creation of better issues and pull requests.
- [N/A] `CHANGELOG.md` is updated
=> Update github templates which are used when creating a new issue or pull request

ktlint-ruleset-experimental/src/test/kotlin/com/pinterest/ktlint/ruleset/experimental/FunctionTypeReferenceSpacingRuleTest.kt
Rename test class so that it name is aligned with the product code.
- [N/A] `CHANGELOG.md` is updated
- [N/A] `README.md` is updated
- [N/A] Rule has been applied on Ktlint itself and violations are fixed
=> Align name of Test class with production class

build.gradle
=> Fix warning on setting main class

CHANGELOG.md, buildSrc/build.gradle.kts
Set Kotlin dev version to `1.6.20-M1`
Closes #1436
=> Set kotlin dev version to 1.6.20-M1

.github/workflows/gradle-pr-build.yml, .github/workflows/gradle-snapshot-build.yml, CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/ktlint-kotlin-common.gradle.kts
=> Bump Kotlin to 1.6.20

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/VisitorProvider.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGenerator.kt, ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigGeneratorTest.kt, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/BlockCommentInitialStarAlignmentRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt
I am not good at English, so I apologize if I am rude.
This PR summarizes minor performance improvements.
=> Minor performance improvements.

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/Rule.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/api/UsesEditorConfigProperties.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleSorter.kt, ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/trailingcomma/TrailingCommaRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/NoWildcardImportsRule.kt, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/DumpAST.kt
Cleanup of several (unrelated) deprecations.
=> Cleanup more deprecations

CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/ktlint-kotlin-common.gradle.kts, gradle/libs.versions.toml
https://github.com/JetBrains/kotlin/releases/tag/v1.7.0
=> Adopt Kotlin 1.7.0

CHANGELOG.md, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/QualifiedRuleId.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/VisitorProvider.kt, ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/VisitorProviderTest.kt, ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/QualifiedRuleIdKtTest.kt
Improve readability and maintainability (follow-up on #1508)
=> 1508 follow up

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/contributing/guidelines.md, docs/extensions/custom-reporter.md, docs/extensions/custom-rule-set.md, docs/mkdocs.yml, docs/readme.md
=> Fix links in docs

.github/PULL_REQUEST_TEMPLATE.md, docs/install/cli.md
Extend CLI usage documentation
- [-] tests are added
- [-] `CHANGELOG.md` is updated
- [-] `README.md` is updated
- [-] Rule has been applied on Ktlint itself and violations are fixed
=> Cli usage documentation

.github/workflows/gradle-docs-publish.yml
=> Disable deploy job in forked repository

.announce
The announce script needed tweaks now that we update docs instead of README.md
=> Fixing bug with update-refs step of .announce script

CHANGELOG.md, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnCallSiteRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/TrailingCommaOnDeclarationSiteRuleTest.kt
=> Trailing comma rule: don't report an empty parameter/argument list with comments

.github/workflows/gradle-pr-build.yml, .github/workflows/gradle-snapshot-build.yml, buildSrc/src/main/kotlin/ToolchainForTests.kt
Follow up https://github.com/pinterest/ktlint/pull/1453#discussion_r857934649.
=> Build on JDK 18

ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/RuleRunnerSorter.kt, ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/VisitorProvider.kt
Write warning and debug messages to logger instead of to console
=> Write warning and debug messages to logger instead of to console

build.gradle
See https://github.com/BreadMoirai/github-release-gradle-plugin/issues/44
=> Fix githubRelease

CHANGELOG.md, gradle/libs.versions.toml
https://github.com/JetBrains/kotlin/releases/tag/v1.7.20
=> Bump Kotlin to 1.7.20

gradle/libs.versions.toml
https://github.com/Kotlin/dokka/releases/tag/v1.7.20
=> Bump Dokka to 1.7.20

docs/index.md
This PR fixes a minor typo on the main documentation page.
=> Fix minor typo on main docs page

docs/rules/experimental.md
Added missing double quotes in the documentation.
https://pinterest.github.io/ktlint/rules/experimental/#unnecessary-parenthesis-before-trailing-lambda
=> Fix missing quotes

README.md
=> docs(readme): update standard repo name and link

mkdocs.yml
=> Change base-url of docs site

CHANGELOG.md
=> Fix date of 0.48.0 release

build.gradle.kts, gradle/verification-metadata.xml, ktlint-ruleset-template/build.gradle.kts
=> Minor tweaks

docs/install/overview.md
Update link to diktat-ktlint online compare tool
=> Update link to diktat-ktlint online compare tool

CHANGELOG.md, gradle.properties
=> Prepare release 0.48.2

docs/install/cli.md, docs/install/integrations.md
=> Updated refs to latest (0.48.2) release

gradle/verification-metadata.xml
=> Trust the key of org.codehaus.groovy:groovy:3.0.13

.github/workflows/gradle-pr-build.yml
A comment with reference to PR which describes how to update the repository configuration after changing the list of JDK's
Follow-up on #1787 
=> Parallel build repository configuration

docs/install/integrations.md
=> Clarify how to run "ktlint --format" on Java16+ with maven-antrun-plugin

CHANGELOG.md, docs/faq.md, ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt, ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtensionTest.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ArgumentListWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlockCommentInitialStarAlignmentRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ContextReceiverWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionSignatureRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IfElseBracingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultiLineIfElseRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoEmptyFirstLineInClassBodyRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterListWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ParameterWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlockCommentInitialStarAlignmentRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt
Wrap annotations on type arguments in same way as with other constructs
Closes #1725 
=> Annotations on type parameters

.github/workflows/gradle-pr-build.yml, .github/workflows/gradle-snapshot-build.yml, .github/workflows/release.yml
=> Speed up builds a bit on CI

docs/faq.md
This PR adds an entry to the FAQ about directly formatting generated code (e.g. code generated via KotlinPoet).
This PR [was requested](https://kotlinlang.slack.com/archives/CKS3XG0LS/p1679395416238039?thread_ts=1679247941.369609&cid=CKS3XG0LS) by @paul-dingemans.
=> Add FAQ about directly formatting generated code

.github/workflows/gradle-pr-build.yml, build.gradle.kts, docs/install/integrations.md, ktlint-ruleset-template/build.gradle.kts
- Defer task configurations.
- Rename `ktlint` task to `ktlintCheck`.
- More idiomatic Gradle dsl.
=> Polish Gradle integration docs

build.gradle.kts, docs/install/integrations.md, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/CommandLineTestRunner.kt
Remove unneeded `--add-opens=java.base/java.util=ALL-UNNAMED`
Closes #1886
=> Remove unneeded `--add-opens=java.base/java.util=ALL-UNNAMED`

build.gradle.kts, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/CommandLineTestRunner.kt
Follow up https://github.com/pinterest/ktlint/pull/1887#issuecomment-1483794763.
=> Remove Jvm arg for Security Manager

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/ReporterAggregator.kt
Fix regression bug which was not yet released.
=> Respect the baseline file in consecutive invocations

build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts
https://docs.gradle.org/8.0/userguide/performance.html#execute_tests_in_parallel
=> Execute tests in parallel

CHANGELOG.md
Update changelog (fix typos and other textual changes)
=> Update changelog (fix typos and other textual changes)

CHANGELOG.md, docs/faq.md, docs/rules/experimental.md, docs/rules/standard.md, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlockCommentInitialStarAlignmentRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ClassNamingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/CommentWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunKeywordSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionReturnTypeSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionStartOfBodySpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionTypeReferenceSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/KdocWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ModifierListSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NullableTypeSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingBetweenFunctionNameAndOpeningParenthesisRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/PropertyNamingRuleTest.kt
Promote experimental rules to non-experimental. Improve documentation by adding examples to all rules.
=> Promote experimental rules

docs/faq.md
=> Docs: Fix typo in FAQ

CHANGELOG.md, gradle.properties
=> Prepare release 0.49.0

ktlint-cli/build.gradle.kts
Fix order of build tasks for signing
=> Fix order of build tasks for signing

gradle.properties, ktlint-cli/build.gradle.kts
Recreating PR #1951 with the version change merged in.
=> Exclude asc from list of signed files

ktlint-cli/build.gradle.kts
Add logging to ktlint-cli publication to find NPE during publication
=> Add logging to ktlint-cli publication

ktlint-cli/build.gradle.kts
Use logger.lifecycle to print logging
=> Use logger.lifecycle to print logging

.github/workflows/release.yml, build-logic/src/main/kotlin/ktlint-publication.gradle.kts, ktlint-bom/build.gradle.kts, ktlint-cli/build.gradle.kts
Add --no-build-cache to release workflow + refactor + add additional logging
=> Add --no-build-cache to release workflow + refactor + add additional logging

.github/workflows/gradle-pr-build.yml, .github/workflows/gradle-snapshot-build.yml, .github/workflows/release.yml, build-logic/src/main/kotlin/ktlint-publication.gradle.kts, ktlint-bom/build.gradle.kts, ktlint-cli/build.gradle.kts
Publication fix + prevent ktlint self-executable jar from growing when conssecutive builds without `clean` goal are run
=> Publication fix + prevent ktlint self-executable jar from growing

.github/workflows/release.yml, .homebrew, RELEASE_TESTING.MD
Fix references to ktlint-cli module (previously 'ktlint' module)
=> Fix references to ktlint-cli module (previously 'ktlint' module)

docs/install/cli.md, docs/install/integrations.md
Updated refs to latest (0.49.0) release
=> Updated refs to latest (0.49.0) release

CHANGELOG.md, gradle.properties
=> Prepare for 0.49.1-snapshot

gradle.properties
=> Add comment why the configuration cache is disabled

.github/workflows/build-pull-request.yml, documentation/readme.md, documentation/release-latest/run-mkdocs-server.sh, documentation/release-latest/serve-docs-locally.sh, documentation/snapshot/run-mkdocs-server.sh, documentation/snapshot/serve-docs-locally.sh
=> Documentation how to

CHANGELOG.md, gradle.properties
=> Prepare release 0.49.1

.announce
=> Fix announce script

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (0.49.1) release
=> Updated refs to latest (0.49.1) release

CHANGELOG.md, gradle.properties
=> Prepare 0.49.2-SNAPSHOT

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/internal/IdNamingPolicy.kt, ktlint-rule-engine-core/src/test/kotlin/com/pinterest/ktlint/rule/engine/core/api/RuleKtTest.kt, ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilder.kt, ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocatorBuilderTest.kt
Updated the error msg to make it more meaningful. 
Closes #1974
=> Update the error msg

documentation/release-latest/docs/rules/experimental.md, documentation/snapshot/docs/rules/experimental.md
Fix icons on the tabs for disallowed code samples
=> Fix icons on the tabs for disallowed code samples

documentation/release-latest/docs/faq.md, documentation/release-latest/docs/rules/configuration-ktlint.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/faq.md, documentation/snapshot/docs/rules/configuration-ktlint.md, documentation/snapshot/docs/rules/experimental.md, documentation/snapshot/docs/rules/standard.md
Clarify use of experimental rules
Closes #2032
=> Clarify use of experimental rules

.github/workflows/pull-request-with-code.yml, .github/workflows/pull-request-without-code.yml
=> Try to fix split of workflow for pull request with and without code

ktlint-cli/build.gradle.kts, ktlint-cli/src/main/scripts/ktlint.bat
Add windows batch file 'ktlint.bat' to published files
Closes #1986
=> Add windows batch file 'ktlint.bat' to published files

documentation/release-latest/docs/install/cli.md, documentation/snapshot/docs/install/cli.md
Adding extra info to help guide the user to installing ktlint on Windows.
This was confirmed on Windows 10 on my workstation.
=> Updating `cli.md` to make slightly more clear on how to install this for windows

documentation/release-latest/docs/faq.md, documentation/snapshot/docs/faq.md
Add faq "Can a new toggle be added to optionally (enable/disable) format code in a particular way?"
Closes #2071
=> Add FAQ "Can a new toggle be added?"

documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/rules/standard.md
Annotated parameters in ktlint_official codestyle are wrapped in order to be consistent with Annotationrule.
Closes #2080
=> Clarify parameter list wrapping documentation

CHANGELOG.md, gradle.properties
=> Prepare 0.50.0 release

documentation/release-latest/docs/faq.md, documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (0.50.0) release
=> Updated refs to latest (0.50.0) release

CHANGELOG.md, RELEASING.md, gradle.properties
Prepare 0.50.0-SNAPSHOT, update releasing notes
=> Prepare 0.50.0-SNAPSHOT, update releasing notes

CHANGELOG.md, ktlint-cli-reporter-baseline/src/main/kotlin/com/pinterest/ktlint/cli/reporter/baseline/BaselineReporter.kt
Store relative path of file in baseline file
Closes #2146
=> Store relative path of file in baseline file

documentation/release-latest/docs/index.md, documentation/snapshot/docs/index.md
Fix workflow name in build status badge
Closes #2159
=> Fix build status badge

documentation/release-latest/docs/index.md, documentation/snapshot/docs/index.md
Fix url of build status badge
Closes #2159 
=> Fix url of build status badge

CHANGELOG.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/integrations.md
=> :memo: update integrations md

.github/workflows/generate-changelog.yml
Add release-changelog-builder-action to temporary workflow
=> Add release-changelog-builder-action to temporary workflow

.github/workflows/generate-changelog.yml
Try to fix printing of changelog
=> Fix printing of changelog

.github/workflows/generate-changelog.yml
=> Try to print changelog

.github/workflows/generate-changelog.yml
=> Generate changelog 3

.github/workflows/generate-changelog.yml
Add configuration to ensure that uncategorized PR's are added to changelog
=> Add configuration to ensure that uncategorized PR's are added to changelog

.github/workflows/generate-changelog.yml
Upgrade mikepenz/release-changelog-builder-action to v4
=> Upgrade mikepenz/release-changelog-builder-action to v4

.github/workflows/generate-changelog.yml
=> Replace reference "${{CHANGELOG}}" with "#{{CHANGELOG}}"

.github/workflows/generate-changelog.yml
=> Replace references "${{..}}" in Json configuration with "#{{..}}"

.github/workflows/generate-changelog.yml
Fix retrieval of last released version
=> Fix retrieval of last released version

.github/workflows/generate-changelog.yml
Fetch all commits/branches/tag
Resolves error "fatal: No names found, cannot describe anything." when tags not being found in a shallow git clone
=> Fetch all commits/branches/tag

.github/workflows/generate-changelog.yml
Replace label_extractor with rules on dependencies category
=> Replace label_extractor with rules on dependencies category

.github/workflows/generate-changelog.yml
Move filtering on dependency category from "labels" to "rules"
=> Move filtering on dependency category from "labels" to "rules"

.github/workflows/generate-changelog.yml
Use environment variable for collecting generated changelog before printing it
=> Use environment variable for collecting generated changelog before printing it

.github/workflows/generate-changelog.yml
Replace icons and use distinct icons for each category. Add newline at start of pr_template to add blank line between PR's in same category. Add two spaces before linebreak in pr_template to insert a newline with indentation.
=> Improve layout of changelog

CHANGELOG.md, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt, ktlint-test/api/ktlint-test.api, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/ReplaceStringTemplatePlaceholder.kt, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/TestLiterals.kt
Replace string template placeholder
=> Replace string template placeholder

RELEASE_TESTING.MD
=> Update release testing guide

.github/workflows/generate-changelog.yml
Exclude PR's labeled with "exclude from changelog" from all categories
=> Exclude PR's labeled with "exclude from changelog" from all categories

CHANGELOG.md, RELEASING.md, gradle.properties
=> Prepare 1.0.0 release

documentation/release-latest/docs/faq.md, documentation/release-latest/docs/rules/configuration-ktlint.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md
Updated refs to latest (1.0.0) release
=> Updated refs to latest (1.0.0) release

CHANGELOG.md, gradle.properties
Set version to `1.0.1-SNAPSHOT`
=> Prepare for next snapshot release

RELEASING.md
Update releasing notes with learnings of latest release
=> Update releasing notes

README.md
<a href="https://search.maven.org/artifact/com.pinterest.ktlint/ktlint-cli"><img src="https://img.shields.io/maven-central/v/com.pinterest.ktlint/ktlint-cli.svg" alt="Maven Central"></a>
=> Update badge for Maven Central

CHANGELOG.md, documentation/release-latest/docs/faq.md, documentation/snapshot/docs/faq.md
Fix maven coordinates in documentation and changelog
Closes #2264
=> Fix maven coordinates in documentation and changelog

documentation/snapshot/docs/rules/experimental.md, documentation/snapshot/docs/rules/standard.md
Examples showing code that is allowed by ktlint are now correctly formatted with code style `ktlint_official` and experimental rules enabled
=> Reformat (and adjust) examples in documentation

.github/workflows/publish-release-build.yml
Fix checking of heading in release notes - negate expression
=> Fix checking of heading in release notes - negate expression

.github/workflows/publish-release-build.yml, CHANGELOG.md
Disable sdkMan as it fails again
=> Disable sdkMan as it fails again

documentation/release-latest/docs/faq.md, documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/release-latest/mkdocs.yml, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
=> Updated refs to latest (1.0.1) release

ktlint-cli/build.gradle.kts
Delete blank line just to retrigger new snapshot build (follow-up #2314)
=> Delete blank line just to retrigger new snapshot build (follow-up #2314)

ktlint-cli-reporter-baseline/build.gradle.kts, ktlint-cli-reporter-checkstyle/build.gradle.kts, ktlint-cli-reporter-core/build.gradle.kts, ktlint-cli-reporter-format/build.gradle.kts, ktlint-cli-reporter-html/build.gradle.kts, ktlint-cli-reporter-json/build.gradle.kts, ktlint-cli-reporter-plain-summary/build.gradle.kts, ktlint-cli-reporter-plain/build.gradle.kts, ktlint-cli-reporter-sarif/build.gradle.kts, ktlint-cli/build.gradle.kts
Upload relocation publications to ReleaseRepo instead of SnapshotRepo (follow-up on #2315)
=> Upload relocation publications to ReleaseRepo instead of SnapshotRepo (follow-up #2315)

ktlint-cli/build.gradle.kts
Add log statement for ktlint-cli relocation
=> Add log statement for ktlint-cli relocation

documentation/release-latest/docs/faq.md, documentation/snapshot/docs/faq.md
Add FAQ's "Why is a rule skipped when I disable some other rule?" and "## Why does ktlint discourage certain comment locations?"
Relates: #2338
Relates: #2354 
=> Add FAQ's skipping rules and discouraged comment locations

ktlint-ruleset-standard/api/ktlint-ruleset-standard.api, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRuleTest.kt
Move curly brace before all consecutive comments preceding that curly brace
Closes #2355
=> Move curly brace before all consecutive comments preceding that curly brace

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt
Prevent stack overflow exception when code provided via stdin can not be parsed as Kotlin, nor Kotlin script
Closes #2379
=> Prevent stack overflow exception when code provided via stdin can not be parsed as Kotlin, nor Kotlin script

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineLoopRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/MultilineLoopRuleTest.kt
Ignore loop's without body in `multiline-loop` rule
=> Ignore loop's without body in `multiline-loop` rule

documentation/release-latest/docs/install/cli.md, documentation/release-latest/serve-docs-locally.sh, documentation/snapshot/docs/install/cli.md, documentation/snapshot/serve-docs-locally.sh
Fix broken formatting in docs
Closes #2434 
=> Fix broken formatting in docs

CODE_OF_CONDUCT.md
Update the code of conduct with correct path.
=> Update CODE_OF_CONDUCT with correct path

CHANGELOG.md, gradle.properties
=> Prepare for 1.1.0 release

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.1.0) release
=> Updated refs to latest (1.1.0) release

CHANGELOG.md, gradle.properties
=> Prepare 1.2.0-SNAPSHOT

documentation/release-latest/docs/rules/configuration-ktlint.md, documentation/snapshot/docs/rules/configuration-ktlint.md
=> Fix links in documentation

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/configuration-ktlint.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.1.1) release
=> Updated refs to latest (1.1.1) release

CHANGELOG.md, gradle.properties
Finish 1.1.1 release. Set 1.2.0-SNAPSHOT
=> Finish 1.1.1 release

documentation/snapshot/docs/rules/experimental.md, ktlint-ruleset-standard/api/ktlint-ruleset-standard.api, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/StandardRuleSetProvider.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundSquareBracketsRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundSquareBracketsRuleTest.kt
Add rule to check spacing around square brackets 'square-brackets-spacing'
Closes #2543
=> Add rule to check spacing around square brackets 'square-brackets-spacing'

CHANGELOG.md, gradle.properties
=> Prepare release 1.2.0

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.2.0) release
=> Updated refs to latest (1.2.0) release

RELEASING.md, gradle.properties
Prepare release 1.2.1-SNAPSHOT
=> Prepare release 1.2.1-SNAPSHOT

ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/KtlintCommandLine.kt, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/SimpleCLITest.kt
Fix handling of "--reporter" CLI parameter
Closes #2576
=> 2576 reporter

CHANGELOG.md, gradle.properties
=> Prepare 1.2.1 release

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.2.1) release
=> Updated refs to latest (1.2.1) release

CHANGELOG.md, documentation/release-latest/docs/rules/experimental.md, documentation/snapshot/docs/rules/experimental.md, gradle.properties, ktlint-cli-reporter-core/src/main/kotlin/com/pinterest/ktlint/cli/reporter/core/api/ReporterV2.kt, ktlint-cli/src/main/kotlin/com/pinterest/ktlint/cli/internal/FileUtils.kt, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/internal/FileUtilsTest.kt, ktlint-rule-engine/src/test/kotlin/com/pinterest/ktlint/rule/engine/internal/ThreadSafeEditorConfigCacheTest.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ImportOrderingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoLineBreakBeforeAssignmentRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BinaryExpressionWrappingRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainMethodContinuationRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/FunctionExpressionBodyRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoLineBreakAfterElseRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StatementWrappingRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/WrappingRuleTest.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/importordering/ImportOrderingRuleTest.kt, ktlint-test-ruleset-provider-v2-deprecated/README.md, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtLintAssertThat.kt, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/KtlintTestFileSystem.kt, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/README.MD, ktlint-test/src/main/kotlin/com/pinterest/ktlint/test/ReplaceStringTemplatePlaceholder.kt
Command used:
```
codespell --skip="**/build/*" --ignore-words-list afterall,testng,optin --write-changes
```
See https://pypi.org/project/codespell/
=> Fix typo's

documentation/release-latest/docs/rules/configuration-intellij-idea.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/rules/configuration-intellij-idea.md, documentation/snapshot/docs/rules/standard.md
Improve documentation about prevent conflicts with Intellij IDEA formatting
Closes #2639
=> Improve documentation about prevent conflicts with Intellij IDEA formatting

ktlint-cli-ruleset-core/src/main/kotlin/com/pinterest/ktlint/cli/ruleset/core/api/RuleSetProviderV3.kt
In the getRuleProviders documentation, I fixed an incorrect argument type.
=> Fix KDoc for RuleSetProviderV3

documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/rules/standard.md
Simplify Expressions and Enhance Grammar for Clarity.
=> Simplify Expressions and Enhance Grammar for Clarity

documentation/release-latest/docs/faq.md, documentation/snapshot/docs/faq.md
Fix FAQ "How do I suppress errors for a line/block/file?"
Closes #2681
=> Fix FAQ "How do I suppress errors for a line/block/file?"

CHANGELOG.md, gradle.properties
=> Prepare release 1.3.0

ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/BlankLineBeforeDeclarationRuleTest.kt
Fix false positive when anonymous function is used as value argument
Closes #2694
=> Fix false positive when anonymous function is used as value argument

CHANGELOG.md, RELEASE_TESTING.MD, gradle.properties
=> Prepare release `1.3.1`

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.3.1) release
=> Updated refs to latest (1.3.1) release

gradle.properties
Update version to 1.4.0-SNAPSHOT
=> Update version to 1.4.0-SNAPSHOT

gradle/libs.versions.toml
We land it!
https://github.com/GradleUp/shadow/releases/tag/8.3.0
=> Migrate to com.gradleup.shadow

gradle/libs.versions.toml
Upgrade Kotlin dev version to `2.1.0-Beta1`
Closes #2809
=> Upgrade Kotlin dev version to `2.1.0-Beta1`

CHANGELOG.md, gradle.properties
=> Prepare release 1.4.0

.github/workflows/publish-release-build.yml
Set git "user.email" to "ktlint@github.com"
=> Set git "user.email" to "ktlint@github.com"

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.4.0) release
=> Updated refs to latest (1.4.0) release

documentation/release-latest/docs/install/cli.md, documentation/snapshot/docs/install/cli.md
Remove dead links to https://aur.archlinux.org/packages/ktlint/
=> Remove dead links to https://aur.archlinux.org/packages/ktlint/

gradle.properties
=> Set version to 1.4.1-SNAPSHOT

CHANGELOG.md, gradle.properties
=> Prepare release 1.4.1

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.4.1) release
=> Updated refs to latest (1.4.1) release

gradle.properties
=> Set version to 1.4.2-SNAPSHOT

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.5.0) release
=> Updated refs to latest (1.5.0) release

gradle.properties
=> Set version to 1.5.1-SNAPSHOT

ktlint-rule-engine-core/api/ktlint-rule-engine-core.api, ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/ASTNodeExtension.kt, ktlint-rule-engine/src/main/kotlin/com/pinterest/ktlint/rule/engine/internal/SuppressionLocator.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/AnnotationSpacingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/ChainWrappingRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/IndentationRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/NoSemicolonsRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundColonRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCommaRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundCurlyRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundKeywordRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/SpacingAroundOperatorsRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateIndentRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRule.kt, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt, ktlint-ruleset-standard/src/test/kotlin/com/pinterest/ktlint/ruleset/standard/rules/StringTemplateRuleTest.kt
Reduces the number of conversions between "psi" and ASTNode
=> Reduces the number of conversions between "psi" and ASTNode

gradle/libs.versions.toml
https://github.com/JetBrains/kotlin/releases/tag/v2.2.0-Beta1
=> Upgrade kotlin dev version to 2.2.0-Beta1

ktlint-rule-engine-core/src/main/kotlin/com/pinterest/ktlint/rule/engine/core/api/KtlintKotlinCompiler.kt
Set system properties to prevent failure when running in ktlint-intellij-plugin with custom installation
Ktlint contains the embedded Kotlin compiler. When running in a process in Intellij IDEA, the initialization of the compiler requires some system properties to be set. When not set, this results in the exception reported, but only when running as (sub)process in context of Intellij IDEA. When using as standalone version, the exception is not run (because it is not running inside the IDEA).
Setting the properties to a non-null value during initialization of the embedded Kotlin compiler, prevents the exception from being thrown.
Closes #2969 …
=> Set system properties to prevent failure when running in ktlint-intellij-plugin with custom installation

CHANGELOG.md, RELEASE_TESTING.MD, gradle.properties, ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/rules/TrailingCommaOnDeclarationSiteRule.kt
=> 1.6.0 prep

gradle.properties
=> Set version to 1.6.1-SNAPSHOT

documentation/snapshot/docs/rules/experimental.md
Grammatical errors were fixed in multiple lines in the experimental rules section to improve understandability. Some commas were added while other words were modified to fix grammar.
=> Fixed Grammatical Errors in Experimental Rules

build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts, build.gradle.kts, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/integrations.md, ktlint-cli/build.gradle.kts, ktlint-cli/src/main/scripts/ktlint.bat, ktlint-cli/src/test/kotlin/com/pinterest/ktlint/cli/CommandLineTestRunner.kt
Remove unneeded "--add-opens=java.base/java.lang=ALL-UNNAMED"
Closes #2997
=> Remove unneeded "--add-opens=java.base/java.lang=ALL-UNNAMED"

build-logic/src/main/kotlin/PublicationPlugin.kt
Followup to #3059
This PR actually adds the jars to the artifacts so they're published to Central Portal.
Tested by running `./gradlew publishToMavenLocal -Pktlint.publication.signing.enable=false` and examining the output
=> Fix source/doc jar publication

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/release-latest/docs/install/snapshot-build.md, documentation/release-latest/docs/rules/configuration-ktlint.md, documentation/release-latest/docs/rules/dependencies.md, documentation/release-latest/docs/rules/experimental.md, documentation/release-latest/docs/rules/standard.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.7.0) release
=> Updated refs to latest (1.7.0) release

documentation/release-latest/docs/install/cli.md, documentation/release-latest/docs/install/integrations.md, documentation/snapshot/docs/install/cli.md, documentation/snapshot/docs/install/integrations.md
Updated refs to latest (1.7.1) release
=> Updated refs to latest (1.7.1) release

.github/workflows/publish-release-docs.yml, .github/workflows/publish-snapshot-docs.yml
Allow publication documents workflow to write to Github pages
=> Allow publication documents workflow to write to Github pages

.github/workflows/publish-release-docs.yml, .github/workflows/publish-snapshot-docs.yml
Allow manual dispatch of workflow for publishing documentation
=> Allow manual dispatch of workflow for publishing documentation

documentation/release-latest/docs/api/custom-rule-set.md, documentation/snapshot/docs/api/custom-rule-set.md
I found a typo in custom-rule-set.md that appears to be an unintended change introduced in https://github.com/pinterest/ktlint/pull/3118 and have fixed it in this PR. 
Thank you.
=> Fix typo in custom-rule-set.md
